// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e29bfa82ae72453bf9665b272c80f00db1783d12dd2a5017788bb362398473c2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
import { defineConfig } from "vitest/config";

export default defineConfig({
	test: {
		include: ["tests/**/*.test.ts"],
		testTimeout: 60000,
		hookTimeout: 120000,
		teardownTimeout: 30000,
		globalSetup: "./globalSetup.ts",
	},
});
