name: Setup Rust Environment
description: Install Rust toolchain with caching for build artifacts
inputs:
  toolchain:
    description: Rust toolchain to install (stable, nightly, beta, or specific version)
    required: false
    default: stable
  components:
    description: Comma-separated list of Rust components to install
    required: false
    default: rustfmt, clippy, llvm-tools-preview
  cache-key-prefix:
    description: Prefix for cache keys
    required: false
    default: rust-build
  cache-cargo-home:
    description: Whether to cache cargo home directory
    required: false
    default: 'true'
  use-sccache:
    description: Enable sccache as the Rust compiler wrapper
    required: false
    default: 'true'
outputs:
  cache-hit:
    description: Whether the Rust cache was restored
    value: ${{ steps.cache-rust.outputs.cache-hit }}
runs:
  using: composite
  steps:
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}
        cache: false

    - name: Setup sccache
      if: inputs.use-sccache == 'true'
      uses: mozilla-actions/sccache-action@v0.0.9

    - name: Verify sccache installation (Unix)
      if: inputs.use-sccache == 'true' && runner.os != 'Windows'
      shell: bash
      run: |
        set -euo pipefail
        if ! command -v sccache &> /dev/null; then
          echo "WARNING: sccache is not available on PATH after mozilla-actions/sccache-action; continuing without cache"
          echo "SCCACHE_GHA_ENABLED=false" >> "$GITHUB_ENV"
          echo "RUSTC_WRAPPER=" >> "$GITHUB_ENV"
        else
          echo "sccache version:"
          sccache --version
          echo "sccache location: $(which sccache)"
        fi

    - name: Verify sccache installation (Windows)
      if: inputs.use-sccache == 'true' && runner.os == 'Windows'
      shell: pwsh
      run: |
        if (-not (Get-Command sccache -ErrorAction SilentlyContinue)) {
          Write-Output "WARNING: sccache is not available on PATH after mozilla-actions/sccache-action; continuing without cache"
          "SCCACHE_GHA_ENABLED=false" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "RUSTC_WRAPPER=" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        } else {
          Write-Output "sccache version:"
          sccache --version
          Write-Output "sccache location: $(Get-Command sccache | Select-Object -ExpandProperty Source)"
        }

    - name: Configure Rust flags (Unix)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        set -euo pipefail
        if [ "${{ inputs.use-sccache }}" = "true" ]; then
          echo "SCCACHE_GHA_ENABLED=true" >> "$GITHUB_ENV"
          echo "RUSTC_WRAPPER=sccache" >> "$GITHUB_ENV"
          # Configure sccache settings for optimal CI performance
          echo "SCCACHE_CACHE_SIZE=2G" >> "$GITHUB_ENV"
          echo "SCCACHE_IDLE_TIMEOUT=0" >> "$GITHUB_ENV"
          echo "SCCACHE_LOG=info" >> "$GITHUB_ENV"
        else
          echo "SCCACHE_GHA_ENABLED=false" >> "$GITHUB_ENV"
          echo "RUSTC_WRAPPER=" >> "$GITHUB_ENV"
        fi

    - name: Configure Rust flags (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        if ("${{ inputs.use-sccache }}" -eq "true") {
          "SCCACHE_GHA_ENABLED=true" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "RUSTC_WRAPPER=sccache" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          # Configure sccache settings for optimal CI performance
          "SCCACHE_CACHE_SIZE=2G" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "SCCACHE_IDLE_TIMEOUT=0" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "SCCACHE_LOG=info" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        } else {
          "SCCACHE_GHA_ENABLED=false" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "RUSTC_WRAPPER=" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        }


    - name: Cache Rust build artifacts
      if: inputs.use-sccache != 'true'
      id: cache-rust
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
          target/
        key: ${{ inputs.cache-key-prefix }}-${{ runner.os }}
        restore-keys: |
          ${{ inputs.cache-key-prefix }}-${{ runner.os }}-

    - name: Cache cargo home (when sccache enabled)
      if: inputs.use-sccache == 'true' && inputs.cache-cargo-home == 'true'
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index
          ~/.cargo/registry/cache
          ~/.cargo/git/db
        key: cargo-home-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-home-${{ runner.os }}-

    - name: Cache cargo-llvm-cov
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin/cargo-llvm-cov
        key: cargo-llvm-cov-${{ runner.os }}

    - name: Install cargo-llvm-cov if not cached (Unix)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        if ! command -v cargo-llvm-cov &> /dev/null; then
          echo "Installing cargo-llvm-cov..."
          cargo install cargo-llvm-cov
        else
          echo "cargo-llvm-cov already installed"
        fi

    - name: Install cargo-llvm-cov if not cached (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        if (-not (Get-Command cargo-llvm-cov -ErrorAction SilentlyContinue)) {
          Write-Output "Installing cargo-llvm-cov..."
          cargo install cargo-llvm-cov
        } else {
          Write-Output "cargo-llvm-cov already installed"
        }
