name: Setup Benchmark Tools
description: Download and install benchmark harness + oha

inputs:
  artifact-name:
    description: "Benchmark tools artifact name"
    required: false
    default: "benchmark-tools"
  install-dir:
    description: "Destination directory to place binaries"
    required: false
    default: "~/.cargo/bin"
  extra-binaries:
    description: "Additional binary names to chmod (space-separated)"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Download benchmark tools
      shell: bash
      run: |
        install_dir="${{ inputs.install-dir }}"
        install_dir="${install_dir/#\~/$HOME}"
        mkdir -p "$install_dir"
        echo "BENCHMARK_INSTALL_DIR=$install_dir" >> $GITHUB_ENV

    - uses: actions/download-artifact@v7
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ env.BENCHMARK_INSTALL_DIR }}

    - name: Make benchmark tools executable
      shell: bash
      run: |
        install_dir="${{ env.BENCHMARK_INSTALL_DIR }}"
        extra="${{ inputs.extra-binaries }}"
        chmod +x "$install_dir/benchmark-harness" "$install_dir/oha"
        if [ -n "$extra" ]; then
          for bin in $extra; do
            chmod +x "$install_dir/${bin}"
          done
        fi

    - name: Add tools to PATH
      shell: bash
      run: echo "${{ env.BENCHMARK_INSTALL_DIR }}" >> $GITHUB_PATH
