name: Benchmark Single Framework
description: Run benchmark for a single framework

inputs:
  framework:
    description: 'Framework name (e.g., spikard-python, fastapi, hono)'
    required: true
  suite:
    description: 'Workload suite to run'
    required: false
    default: 'all'
  duration:
    description: 'Duration per workload in seconds'
    required: false
    default: '30'
  concurrency:
    description: 'Concurrent connections'
    required: false
    default: '100'
  warmup:
    description: 'Warmup requests'
    required: false
    default: '1000'

runs:
  using: composite
  steps:
    - name: Setup Rust (needed for maturin and wasm-pack)
      uses: ./.github/actions/setup-rust

    - name: Install oha load generator
      shell: bash
      run: |
        if ! command -v oha &> /dev/null; then
          cargo install oha
        fi

    - name: Detect framework language
      id: detect
      shell: bash
      run: |
        framework="${{ inputs.framework }}"

        # Determine language based on framework name patterns
        # Patterns: rust (-rust, axum-baseline), php (phalcon, trongate, spikard-php),
        # python (fastapi*, litestar*, robyn*, spikard-python, spikard-raw),
        # node (fastify*, hono*, express*, elysia, morojs, spikard-node, spikard-wasm),
        # ruby (-ruby, hanami-api*, roda*), wasm (-wasm)
        if [[ "$framework" == *"-rust" ]] || [[ "$framework" == "axum-baseline" ]]; then
          echo "language=rust" >> $GITHUB_OUTPUT
        elif [[ "$framework" == "phalcon" ]] || [[ "$framework" == "trongate" ]] || [[ "$framework" == "spikard-php" ]]; then
          echo "language=php" >> $GITHUB_OUTPUT
        elif [[ "$framework" == fastapi* ]] || [[ "$framework" == litestar* ]] || [[ "$framework" == robyn* ]] || [[ "$framework" == "spikard-python" ]] || [[ "$framework" == "spikard-raw" ]]; then
          echo "language=python" >> $GITHUB_OUTPUT
        elif [[ "$framework" == *"-node" ]] || [[ "$framework" == fastify* ]] || [[ "$framework" == hono* ]] || [[ "$framework" == express* ]] || [[ "$framework" == "elysia" ]] || [[ "$framework" == "morojs" ]] || [[ "$framework" == "spikard-wasm" ]]; then
          echo "language=node" >> $GITHUB_OUTPUT
        elif [[ "$framework" == *"-ruby" ]] || [[ "$framework" == hanami-api* ]] || [[ "$framework" == roda* ]]; then
          echo "language=ruby" >> $GITHUB_OUTPUT
        elif [[ "$framework" == *"-wasm" ]]; then
          echo "language=wasm" >> $GITHUB_OUTPUT
        else
          echo "language=unknown" >> $GITHUB_OUTPUT
        fi

    - name: Setup Python environment
      if: steps.detect.outputs.language == 'python'
      uses: ./.github/actions/setup-python-env
      with:
        python-version: "3.14"
        cache-prefix: benchmark-${{ inputs.framework }}

    - name: Install framework-specific dependencies
      if: steps.detect.outputs.language == 'python'
      shell: bash
      working-directory: tools/benchmark-harness/apps/${{ inputs.framework }}
      run: |
        # Install dependencies from the benchmark app's pyproject.toml
        uv pip install -e .

    - name: Install pnpm
      if: steps.detect.outputs.language == 'node'
      uses: pnpm/action-setup@v4

    - name: Setup Node environment
      if: steps.detect.outputs.language == 'node'
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'pnpm'

    - name: Setup Ruby environment
      if: steps.detect.outputs.language == 'ruby'
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true

    - name: Install Node dependencies
      if: steps.detect.outputs.language == 'node'
      shell: bash
      working-directory: tools/benchmark-harness/apps/${{ inputs.framework }}
      run: pnpm install --frozen-lockfile

    - name: Build Python binding (if needed)
      if: steps.detect.outputs.language == 'python' && (inputs.framework == 'spikard' || inputs.framework == 'spikard-python' || inputs.framework == 'spikard-raw')
      shell: bash
      run: |
        # maturin is already installed via uv sync from the root pyproject.toml dev dependencies
        # Use uv run to execute maturin from the uv-managed virtual environment
        uv run maturin --version || { echo "maturin not found in uv environment"; exit 1; }
        # Build and install the Python binding in development mode
        cd crates/spikard-py && uv run maturin develop --release --features extension-module || { echo "Failed to build Python binding"; exit 1; }

    - name: Build Node binding (if needed)
      if: steps.detect.outputs.language == 'node' && inputs.framework == 'spikard-node'
      shell: bash
      run: |
        # Clean old bindings in both locations to avoid platform mismatches
        rm -f crates/spikard-node/*.node
        rm -f packages/node/*.node

        cd crates/spikard-node
        pnpm install
        # Build for current platform using napi --platform flag
        pnpm exec napi build --platform --release

        # Copy built binding to packages/node where the benchmark app expects it
        cp *.node ../../packages/node/ || true

    - name: Build Ruby binding (if needed)
      if: steps.detect.outputs.language == 'ruby' && inputs.framework == 'spikard-ruby'
      shell: bash
      working-directory: crates/spikard-rb
      run: |
        bundle install
        bundle exec rake compile

    - name: Install Ruby benchmark app dependencies
      if: steps.detect.outputs.language == 'ruby'
      shell: bash
      working-directory: tools/benchmark-harness/apps/${{ inputs.framework }}
      run: bundle install

    - name: Install pnpm for WASM builds
      if: steps.detect.outputs.language == 'wasm'
      uses: pnpm/action-setup@v4

    - name: Setup Node for WASM
      if: steps.detect.outputs.language == 'wasm'
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'pnpm'

    - name: Build WASM binding (if needed)
      if: steps.detect.outputs.language == 'wasm' && inputs.framework == 'spikard-wasm'
      shell: bash
      run: |
        # Build the WASM module using wasm-pack
        cd crates/spikard-wasm
        pnpm install
        pnpm run build:node

        # Install framework benchmark app dependencies
        # Use --force to ensure workspace dependencies are properly linked
        cd ../../tools/benchmark-harness/apps/spikard-wasm
        pnpm install --force

    - name: Create results directory
      shell: bash
      run: mkdir -p results/${{ inputs.framework }}

    - name: Run benchmark
      shell: bash
      run: |
        benchmark-harness profile \
          --framework "${{ inputs.framework }}" \
          --app-dir "tools/benchmark-harness/apps/${{ inputs.framework }}" \
          --suite "${{ inputs.suite }}" \
          --duration "${{ inputs.duration }}" \
          --concurrency "${{ inputs.concurrency }}" \
          --warmup "${{ inputs.warmup }}" \
          --output "results/${{ inputs.framework }}"

    - name: Upload benchmark results
      uses: actions/upload-artifact@v5
      if: always()
      with:
        name: benchmark-results-${{ inputs.framework }}
        path: results/${{ inputs.framework }}/
        retention-days: 30
