name: Benchmark Single Framework
description: Run benchmark for a single framework

inputs:
  framework:
    description: 'Framework name (e.g., spikard-python, fastapi, hono)'
    required: true
  suite:
    description: 'Workload suite to run'
    required: false
    default: 'all'
  duration:
    description: 'Duration per workload in seconds'
    required: false
    default: '30'
  concurrency:
    description: 'Concurrent connections'
    required: false
    default: '100'
  warmup:
    description: 'Warmup requests'
    required: false
    default: '1000'

runs:
  using: composite
  steps:
    - name: Setup Rust (needed for maturin and wasm-pack)
      uses: ./.github/actions/setup-rust

    - name: Install oha load generator
      shell: bash
      run: |
        if ! command -v oha &> /dev/null; then
          cargo install oha
        fi

    - name: Detect framework language
      id: detect
      shell: bash
      run: |
        framework="${{ inputs.framework }}"

        # Determine language based on framework name patterns
        # Patterns: rust (-rust, axum-baseline), php (phalcon, trongate, spikard-php),
        # python (fastapi*, litestar*, robyn*, spikard-python, spikard-raw),
        # node (fastify*, hono*, express*, elysia, morojs, spikard-node, spikard-wasm),
        # ruby (-ruby, hanami-api*, roda*), wasm (-wasm)
        if [[ "$framework" == *"-rust" ]] || [[ "$framework" == "axum-baseline" ]]; then
          echo "language=rust" >> $GITHUB_OUTPUT
        elif [[ "$framework" == "phalcon" ]] || [[ "$framework" == "trongate" ]] || [[ "$framework" == "spikard-php" ]]; then
          echo "language=php" >> $GITHUB_OUTPUT
        elif [[ "$framework" == fastapi* ]] || [[ "$framework" == litestar* ]] || [[ "$framework" == robyn* ]] || [[ "$framework" == "spikard-python" ]] || [[ "$framework" == "spikard-raw" ]]; then
          echo "language=python" >> $GITHUB_OUTPUT
        elif [[ "$framework" == *"-node" ]] || [[ "$framework" == fastify* ]] || [[ "$framework" == hono* ]] || [[ "$framework" == express* ]] || [[ "$framework" == "elysia" ]] || [[ "$framework" == "morojs" ]] || [[ "$framework" == "spikard-wasm" ]]; then
          echo "language=node" >> $GITHUB_OUTPUT
        elif [[ "$framework" == *"-ruby" ]] || [[ "$framework" == hanami-api* ]] || [[ "$framework" == roda* ]]; then
          echo "language=ruby" >> $GITHUB_OUTPUT
        elif [[ "$framework" == *"-wasm" ]]; then
          echo "language=wasm" >> $GITHUB_OUTPUT
        else
          echo "language=unknown" >> $GITHUB_OUTPUT
        fi

    - name: Build Python binding (if needed)
      if: steps.detect.outputs.language == 'python' && (inputs.framework == 'spikard' || inputs.framework == 'spikard-python' || inputs.framework == 'spikard-raw')
      uses: ./.github/actions/build-python-binding

    - name: Setup Python environment for non-spikard apps
      if: steps.detect.outputs.language == 'python' && !(inputs.framework == 'spikard' || inputs.framework == 'spikard-python' || inputs.framework == 'spikard-raw')
      uses: ./.github/actions/setup-python-env
      with:
        python-version: "3.14"
        cache-prefix: benchmark-${{ inputs.framework }}

    - name: Install Python benchmark app dependencies
      if: steps.detect.outputs.language == 'python'
      shell: bash
      working-directory: tools/benchmark-harness/apps/${{ inputs.framework }}
      run: uv pip install -e .

    - name: Build Node binding (if needed)
      if: steps.detect.outputs.language == 'node' && inputs.framework == 'spikard-node'
      uses: ./.github/actions/build-node-binding

    - name: Setup Node environment for non-spikard apps
      if: steps.detect.outputs.language == 'node' && inputs.framework != 'spikard-node'
      uses: ./.github/actions/setup-node-workspace
      with:
        node-version: '24'

    - name: Install Node benchmark app dependencies
      if: steps.detect.outputs.language == 'node'
      shell: bash
      working-directory: tools/benchmark-harness/apps/${{ inputs.framework }}
      run: pnpm install --frozen-lockfile

    - name: Build Ruby binding (if needed)
      if: steps.detect.outputs.language == 'ruby' && inputs.framework == 'spikard-ruby'
      uses: ./.github/actions/build-ruby-binding

    - name: Setup Ruby environment for non-spikard apps
      if: steps.detect.outputs.language == 'ruby' && inputs.framework != 'spikard-ruby'
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler-cache: false

    - name: Install Ruby benchmark app dependencies
      if: steps.detect.outputs.language == 'ruby'
      shell: bash
      working-directory: tools/benchmark-harness/apps/${{ inputs.framework }}
      run: bundle install

    - name: Setup PHP with Phalcon extension
      if: steps.detect.outputs.language == 'php' && inputs.framework == 'phalcon'
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: phalcon5
        tools: composer

    - name: Setup PHP for Trongate
      if: steps.detect.outputs.language == 'php' && inputs.framework == 'trongate'
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        tools: composer
        coverage: none

    - name: Build spikard-php binding
      if: steps.detect.outputs.language == 'php' && inputs.framework == 'spikard-php'
      uses: ./.github/actions/build-php-extension
      with:
        php-version: '8.4'

    - name: Install PHP package dependencies
      if: steps.detect.outputs.language == 'php' && inputs.framework == 'spikard-php'
      shell: bash
      run: |
        cd packages/php
        composer install

    - name: Install pnpm for WASM builds
      if: steps.detect.outputs.language == 'wasm'
      uses: pnpm/action-setup@v4

    - name: Setup Node for WASM
      if: steps.detect.outputs.language == 'wasm'
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'pnpm'

    - name: Build WASM binding (if needed)
      if: steps.detect.outputs.language == 'wasm' && inputs.framework == 'spikard-wasm'
      shell: bash
      run: |
        # Build the WASM module using wasm-pack
        cd crates/spikard-wasm
        pnpm install
        pnpm run build:node

        # Copy built WASM files to benchmark app directory
        cp -v dist-node/spikard_wasm.js dist-node/spikard_wasm_bg.wasm dist-node/spikard_wasm.d.ts \
          ../../tools/benchmark-harness/apps/spikard-wasm/ || true

        # Install framework benchmark app dependencies
        # Use --force to ensure workspace dependencies are properly linked
        cd ../../tools/benchmark-harness/apps/spikard-wasm
        pnpm install --force

    - name: Create results directory
      shell: bash
      run: mkdir -p results/${{ inputs.framework }}

    - name: Run benchmark
      shell: bash
      run: |
        benchmark-harness profile \
          --framework "${{ inputs.framework }}" \
          --app-dir "tools/benchmark-harness/apps/${{ inputs.framework }}" \
          --suite "${{ inputs.suite }}" \
          --duration "${{ inputs.duration }}" \
          --concurrency "${{ inputs.concurrency }}" \
          --warmup "${{ inputs.warmup }}" \
          --output "results/${{ inputs.framework }}"

    - name: Upload benchmark results
      uses: actions/upload-artifact@v5
      if: always()
      with:
        name: benchmark-results-${{ inputs.framework }}
        path: results/${{ inputs.framework }}/
        retention-days: 30
