name: Benchmark Single Framework
description: Run benchmark for a single framework

inputs:
  framework:
    description: 'Framework name (e.g., spikard-python-validation, fastapi-uvicorn-raw, hono-raw)'
    required: true
  suite:
    description: 'Workload suite to run'
    required: false
    default: 'all'
  duration:
    description: 'Duration per workload in seconds'
    required: false
    default: '30'
  concurrency:
    description: 'Concurrent connections'
    required: false
    default: '100'
  warmup:
    description: 'Warmup requests'
    required: false
    default: '1000'

runs:
  using: composite
  steps:
    - name: Setup Rust (needed for maturin and wasm-pack)
      uses: ./.github/actions/setup-rust

    - name: Install oha load generator
      shell: bash
      run: |
        if ! command -v oha &> /dev/null; then
          cargo install oha
        fi
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Detect framework language
      id: detect
      shell: bash
      run: |
        framework="${{ inputs.framework }}"

        # Determine language based on framework name patterns
        # Patterns: rust (-rust, axum-baseline, spikard-rust-*),
        # php (phalcon-raw, trongate-raw, spikard-php-*),
        # python (fastapi*, robyn*, spikard-python-*),
        # node (fastify*, hono*, express*, elysia*, morojs*, kito*, spikard-node-*, spikard-bun-*),
        # ruby (spikard-ruby-*, hanami-api*, roda*), wasm (spikard-wasm-*)
        if [[ "$framework" == *"-rust" ]] || [[ "$framework" == "axum-baseline" ]] || [[ "$framework" == "spikard-rust-"* ]]; then
          echo "language=rust" >> $GITHUB_OUTPUT
        elif [[ "$framework" == "phalcon-raw" ]] || [[ "$framework" == "trongate-raw" ]] || [[ "$framework" == "spikard-php-"* ]]; then
          echo "language=php" >> $GITHUB_OUTPUT
        elif [[ "$framework" == fastapi* ]] || [[ "$framework" == robyn* ]] || [[ "$framework" == "spikard-python-"* ]]; then
          echo "language=python" >> $GITHUB_OUTPUT
        elif [[ "$framework" == "spikard-node-"* ]] || [[ "$framework" == "spikard-bun-"* ]] || [[ "$framework" == fastify* ]] || [[ "$framework" == hono* ]] || [[ "$framework" == express* ]] || [[ "$framework" == elysia* ]] || [[ "$framework" == morojs* ]] || [[ "$framework" == kito* ]]; then
          echo "language=node" >> $GITHUB_OUTPUT
        elif [[ "$framework" == "spikard-ruby-"* ]] || [[ "$framework" == hanami-api* ]] || [[ "$framework" == roda* ]]; then
          echo "language=ruby" >> $GITHUB_OUTPUT
        elif [[ "$framework" == "spikard-wasm-"* ]]; then
          echo "language=wasm" >> $GITHUB_OUTPUT
        else
          echo "language=unknown" >> $GITHUB_OUTPUT
        fi

    - name: Build Python binding (if needed)
      if: steps.detect.outputs.language == 'python' && startsWith(inputs.framework, 'spikard-python-')
      uses: ./.github/actions/build-python-binding

    - name: Setup Python environment for non-spikard apps
      if: steps.detect.outputs.language == 'python' && !startsWith(inputs.framework, 'spikard-python-')
      uses: ./.github/actions/setup-python-env
      with:
        python-version: "3.14"
        cache-prefix: benchmark-${{ inputs.framework }}

    - name: Install Python benchmark app dependencies
      if: steps.detect.outputs.language == 'python'
      shell: bash
      working-directory: tools/benchmark-harness/apps/${{ inputs.framework }}
      run: uv pip install -e .

    - name: Setup Node environment
      if: steps.detect.outputs.language == 'node'
      uses: ./.github/actions/setup-node-workspace
      with:
        node-version: '24'

    - name: Build Node binding (if needed)
      if: steps.detect.outputs.language == 'node' && (startsWith(inputs.framework, 'spikard-node-') || startsWith(inputs.framework, 'spikard-bun-'))
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/packages/node
        pnpm build:native

    - name: Setup Bun runtime
      if: steps.detect.outputs.language == 'node' && (startsWith(inputs.framework, 'elysia') || startsWith(inputs.framework, 'spikard-bun-'))
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install Node benchmark app dependencies
      if: steps.detect.outputs.language == 'node' && !startsWith(inputs.framework, 'elysia') && !startsWith(inputs.framework, 'spikard-bun-')
      shell: bash
      working-directory: tools/benchmark-harness/apps/${{ inputs.framework }}
      run: pnpm install --frozen-lockfile

    - name: Install Bun benchmark app dependencies
      if: steps.detect.outputs.language == 'node' && startsWith(inputs.framework, 'elysia')
      shell: bash
      working-directory: tools/benchmark-harness/apps/${{ inputs.framework }}
      run: bun install

    - name: Build Ruby binding (if needed)
      if: steps.detect.outputs.language == 'ruby' && startsWith(inputs.framework, 'spikard-ruby-')
      uses: ./.github/actions/build-ruby-binding

    - name: Copy Ruby binding to packages
      if: steps.detect.outputs.language == 'ruby' && startsWith(inputs.framework, 'spikard-ruby-')
      shell: bash
      run: |
        mkdir -p $GITHUB_WORKSPACE/packages/ruby/lib/spikard
        cp -v $GITHUB_WORKSPACE/packages/ruby/lib/spikard_rb.* $GITHUB_WORKSPACE/packages/ruby/lib/spikard/ || true

    - name: Setup Ruby environment for non-spikard apps
      if: steps.detect.outputs.language == 'ruby' && !startsWith(inputs.framework, 'spikard-ruby-')
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler: "4.0.0"
        bundler-cache: false

    - name: Install Ruby benchmark app dependencies
      if: steps.detect.outputs.language == 'ruby' && !startsWith(inputs.framework, 'spikard-ruby-')
      shell: bash
      working-directory: tools/benchmark-harness/apps/${{ inputs.framework }}
      run: bundle install

    - name: Setup PHP with Phalcon extension
      if: steps.detect.outputs.language == 'php' && inputs.framework == 'phalcon-raw'
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: phalcon5
        tools: composer

    - name: Setup PHP for Trongate
      if: steps.detect.outputs.language == 'php' && inputs.framework == 'trongate-raw'
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        tools: composer
        coverage: none

    - name: Build spikard-php binding
      if: steps.detect.outputs.language == 'php' && startsWith(inputs.framework, 'spikard-php-')
      uses: ./.github/actions/build-php-extension
      with:
        php-version: '8.4'

    - name: Enable PHP extension
      if: steps.detect.outputs.language == 'php' && startsWith(inputs.framework, 'spikard-php-')
      shell: bash
      run: |
        EXT_FILE=$(find target/release -name "libspikard_php.*" -o -name "spikard_php.*" | head -1)
        if [ -n "$EXT_FILE" ]; then
          EXT_DIR=$(php-config --extension-dir)
          sudo cp "$EXT_FILE" "$EXT_DIR/spikard_php.so"
          echo "extension=spikard_php.so" | sudo tee /etc/php/8.4/cli/conf.d/99-spikard.ini
          php -m | grep spikard
        fi

    - name: Install PHP package dependencies
      if: steps.detect.outputs.language == 'php' && startsWith(inputs.framework, 'spikard-php-')
      shell: bash
      working-directory: packages/php
      run: composer install

    - name: Setup Deno for WASM
      if: steps.detect.outputs.language == 'wasm'
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x

    - name: Build WASM binding (if needed)
      if: steps.detect.outputs.language == 'wasm' && startsWith(inputs.framework, 'spikard-wasm-')
      shell: bash
      run: |
        # Build the WASM module using wasm-pack for Deno
        cd $GITHUB_WORKSPACE/crates/spikard-wasm
        rustup target add wasm32-unknown-unknown
        cargo install wasm-pack || true
        # Build with deno target, which outputs to dist-deno
        wasm-pack build --target deno --out-dir dist-deno --release
        # Copy the deno build to the benchmark app pkg directories
        for app in spikard-wasm-raw spikard-wasm-validation; do
          mkdir -p "$GITHUB_WORKSPACE/tools/benchmark-harness/apps/${app}/pkg"
          cp -r dist-deno/* "$GITHUB_WORKSPACE/tools/benchmark-harness/apps/${app}/pkg/"
        done

    - name: Install WASM benchmark app dependencies
      if: steps.detect.outputs.language == 'wasm'
      shell: bash
      working-directory: tools/benchmark-harness/apps/${{ inputs.framework }}
      run: |
        # Deno doesn't need explicit install, dependencies are cached on first run
        echo "Deno will fetch dependencies on first run"

    - name: Create results directory
      shell: bash
      run: mkdir -p results/${{ inputs.framework }}

    - name: Run benchmark
      shell: bash
      run: |
        benchmark-harness profile \
          --framework "${{ inputs.framework }}" \
          --app-dir "tools/benchmark-harness/apps/${{ inputs.framework }}" \
          --suite "${{ inputs.suite }}" \
          --duration "${{ inputs.duration }}" \
          --concurrency "${{ inputs.concurrency }}" \
          --warmup "${{ inputs.warmup }}" \
          --output "results/${{ inputs.framework }}/profile.json"

    - name: Upload benchmark results
      uses: actions/upload-artifact@v5
      if: always()
      with:
        name: benchmark-results-${{ inputs.framework }}
        path: results/${{ inputs.framework }}/
        retention-days: 30
