# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1838bf28a17b12ab85ba2a0f7da55900106423c0267323fb1b6163b1d5164ef3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: openapi
defmodule E2e.OpenapiTest do
  use ExUnit.Case, async: true

  defp mock_server_url do
    System.get_env("MOCK_SERVER_URL") || "http://localhost:8080"
  end

  describe "openapi_basic_spec_generation" do
    test "Tests OpenAPI specification is generated from route definitions" do
      {:ok, response} = Req.get(url: "#{mock_server_url()}/fixtures/openapi_basic_spec_generation", connect_options: [protocols: [:http1]])
      assert response.status == 200
      assert Enum.find_value(response.headers, fn {k, v} -> if String.downcase(k) == "content-type", do: List.first(List.wrap(v)) end) == "application/json"
      body_decoded = if is_binary(response.body), do: Jason.decode!(response.body), else: response.body
      assert body_decoded == %{"info" => %{"title" => "API"}, "openapi" => "3.0.0"}
    end
  end

  describe "openapi_contact_information" do
    test "Tests OpenAPI spec includes contact information" do
      {:ok, response} = Req.get(url: "#{mock_server_url()}/fixtures/openapi_contact_information", connect_options: [protocols: [:http1]])
      assert response.status == 200
      body_decoded = if is_binary(response.body), do: Jason.decode!(response.body), else: response.body
      assert body_decoded == %{"info" => %{"contact" => %{"name" => "API Support", "url" => "https://example.com/support"}}}
    end
  end

  describe "openapi_disabled_returns_404" do
    test "Tests OpenAPI returns 404 when explicitly disabled" do
      {:ok, response} = Req.get(url: "#{mock_server_url()}/fixtures/openapi_disabled_returns_404", connect_options: [protocols: [:http1]])
      assert response.status == 404
    end
  end

  describe "openapi_enabled_flag_true" do
    test "Tests OpenAPI can be explicitly enabled" do
      {:ok, response} = Req.get(url: "#{mock_server_url()}/fixtures/openapi_enabled_flag_true", connect_options: [protocols: [:http1]])
      assert response.status == 200
      body_decoded = if is_binary(response.body), do: Jason.decode!(response.body), else: response.body
      assert body_decoded == %{"openapi" => "3.0.0"}
    end
  end

  describe "openapi_json_endpoint_path" do
    test "Tests OpenAPI JSON is served at configured endpoint" do
      {:ok, response} = Req.get(url: "#{mock_server_url()}/fixtures/openapi_json_endpoint_path", connect_options: [protocols: [:http1]])
      assert response.status == 200
      assert Enum.find_value(response.headers, fn {k, v} -> if String.downcase(k) == "content-type", do: List.first(List.wrap(v)) end) == "application/json"
      body_decoded = if is_binary(response.body), do: Jason.decode!(response.body), else: response.body
      assert body_decoded == %{"openapi" => "3.0.0"}
    end
  end

  describe "openapi_license_information" do
    test "Tests OpenAPI spec includes license information" do
      {:ok, response} = Req.get(url: "#{mock_server_url()}/fixtures/openapi_license_information", connect_options: [protocols: [:http1]])
      assert response.status == 200
      body_decoded = if is_binary(response.body), do: Jason.decode!(response.body), else: response.body
      assert body_decoded == %{"info" => %{"license" => %{"name" => "MIT"}}}
    end
  end

  describe "openapi_redoc_path" do
    test "Tests ReDoc UI is served at configured path" do
      {:ok, response} = Req.get(url: "#{mock_server_url()}/fixtures/openapi_redoc_path", connect_options: [protocols: [:http1]])
      assert response.status == 200
      assert Enum.find_value(response.headers, fn {k, v} -> if String.downcase(k) == "content-type", do: List.first(List.wrap(v)) end) == "text/html"
    end
  end

  describe "openapi_security_schemes_definition" do
    test "Tests OpenAPI spec includes security schemes" do
      {:ok, response} = Req.get(url: "#{mock_server_url()}/fixtures/openapi_security_schemes_definition", connect_options: [protocols: [:http1]])
      assert response.status == 200
      body_decoded = if is_binary(response.body), do: Jason.decode!(response.body), else: response.body
      assert body_decoded == %{"components" => %{"securitySchemes" => %{"bearerAuth" => %{"scheme" => "bearer", "type" => "http"}}}}
    end
  end

  describe "openapi_servers_configuration" do
    test "Tests OpenAPI spec includes configured servers" do
      {:ok, response} = Req.get(url: "#{mock_server_url()}/fixtures/openapi_servers_configuration", connect_options: [protocols: [:http1]])
      assert response.status == 200
      body_decoded = if is_binary(response.body), do: Jason.decode!(response.body), else: response.body
      assert body_decoded == %{"servers" => [%{"url" => "https://api.example.com"}, %{"url" => "https://staging-api.example.com"}]}
    end
  end

  describe "openapi_swagger_ui_path" do
    test "Tests Swagger UI is served at configured path" do
      {:ok, response} = Req.get(url: "#{mock_server_url()}/fixtures/openapi_swagger_ui_path", connect_options: [protocols: [:http1]])
      assert response.status == 200
      assert Enum.find_value(response.headers, fn {k, v} -> if String.downcase(k) == "content-type", do: List.first(List.wrap(v)) end) == "text/html"
    end
  end
end
