packages:
  - "packages/node"
  - "packages/wasm"
  - "crates/spikard-node"
  - "crates/spikard-wasm"
  - "e2e/node"
  - "e2e/wasm"
  - "e2e/deno"
  - "e2e/cloudflare"
  - "examples/*"
  - "tools/benchmark-harness/apps/*"
