version: "3"

env:
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: plain

tasks:
  setup:
    desc: "Install dependencies with uv and build Rust components"
    cmds:
      - uv sync --all-extras --all-groups
      - uv tool install cargo-binstall
      - uv tool install cargo-upgrade
      - task: build:py
      - prek install
      - prek install --hook-type commit-msg

  update:
    desc: "Update Python and Rust dependencies"
    cmds:
      - uv run uv-bump
      - cargo upgrade --workspace --incompatible
      - cargo update --workspace
      - uv sync --all-extras --all-groups --upgrade
      - task: build:py
      - prek autoupdate

  test:python:
    desc: "Run Python tests with pytest"
    cmds:
      - PYTHONPATH=. uv run pytest packages/python/tests -v

  test:rust:
    desc: "Run Rust tests"
    cmds:
      - cargo test --workspace --release

  check:rust:
    desc: "Fast check of Rust code (no codegen)"
    cmds:
      - cargo check --workspace --all-features

  clippy:rust:
    desc: "Run Rust linter (clippy)"
    cmds:
      - cargo clippy --workspace --all-features -- -D warnings

  fmt:rust:
    desc: "Format Rust code"
    cmds:
      - cargo fmt --all

  fmt:rust:check:
    desc: "Check Rust formatting without modifying files"
    cmds:
      - cargo fmt --all --check

  build:rust:
    desc: "Build Rust workspace in release mode"
    cmds:
      - cargo build --workspace --release

  build:rust:debug:
    desc: "Build Rust workspace in debug mode"
    cmds:
      - cargo build --workspace

  test:
    desc: "Run both Rust and Python tests"
    cmds:
      - task: test:rust
      - task: test:python

  lint:
    desc: "Lint Python code with ruff/prek and Rust code with clippy/fmt"
    cmds:
      - task: clippy:rust
      - prek run --all-files

  fmt:
    desc: "Format Python and Rust code"
    cmds:
      - task: fmt:rust
      - prek run ruff-format --all-files

  check:
    desc: "Fast check of Python and Rust code"
    cmds:
      - task: check:rust
      - uv run ruff check .

  build:py:
    desc: "Build Python bindings for development"
    dir: crates/spikard-py
    cmds:
      - uv run maturin develop --release

  build:py:debug:
    desc: "Build Python bindings in debug mode"
    dir: crates/spikard-py
    cmds:
      - uv run maturin develop

  build:py:wheel:
    desc: "Build Python bindings as wheel for testing (release mode)"
    dir: crates/spikard-py
    cmds:
      - uv run maturin build --release --out ../../target/wheels
      - uv pip install --force-reinstall ../../target/wheels/spikard_bindings-0.1.0-cp310-abi3-macosx_11_0_arm64.whl

  build:local:python:
    desc: "Clean rebuild Python bindings for local testing (removes cached .so files)"
    cmds:
      - cargo clean
      - rm -rf crates/spikard-py/.venv/lib/python*/site-packages/_spikard
      - task: build:py:debug

  build:
    desc: "Build Rust components for development"
    cmds:
      - task: build:py

  build:debug:
    desc: "Build Rust components in debug mode"
    cmds:
      - task: build:py:debug

  build:cli:
    desc: "Build CLI binary"
    cmds:
      - cargo build --release --package spikard-cli

  build:http:
    desc: "Build HTTP server binary"
    cmds:
      - cargo build --release --package spikard-http

  build:node:
    desc: "Build Node.js native bindings with NAPI-RS"
    dir: crates/spikard-node
    cmds:
      - pnpm run build

  build:wasm:
    desc: "Build WebAssembly bindings with wasm-bindgen"
    dir: crates/spikard-wasm
    cmds:
      - pnpm run build:all

  build:js:
    desc: "Build all JavaScript/TypeScript packages (node, wasm)"
    cmds:
      - task: build:node
      - task: build:wasm

  run:cli:
    desc: "Run the CLI tool"
    cmds:
      - cargo run --package spikard-cli -- {{.CLI_ARGS}}

  run:http:
    desc: "Run the HTTP server"
    cmds:
      - cargo run --package spikard-http

  cov:rust:
    desc: "Generate Rust code coverage report (requires cargo-llvm-cov)"
    cmds:
      - cargo llvm-cov --workspace --lcov --output-path rust-coverage.lcov
      - echo "Rust coverage report generated at rust-coverage.lcov"
      - cargo llvm-cov --workspace --summary-only

  cov:python:
    desc: "Generate Python code coverage report"
    cmds:
      - uv run pytest tests/ --cov=spikard --cov-report=lcov:coverage.lcov --cov-report=term
      - echo "Python coverage report generated at coverage.lcov"

  cov:all:
    desc: "Generate both Rust and Python coverage reports"
    cmds:
      - task: cov:rust
      - task: cov:python

  clean:
    desc: "Clean build artifacts"
    cmds:
      - cargo clean
      - rm -rf target/
      - rm -rf .pytest_cache/
      - rm -rf .mypy_cache/
      - rm -rf .ruff_cache/
      - find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
      - find . -type f -name "*.pyc" -delete
      - find crates -type d -name "dist" -exec rm -rf {} + 2>/dev/null || true
      - find crates -type d -name "node_modules" -exec rm -rf {} + 2>/dev/null || true

  default:
    desc: "Show available tasks"
    cmds:
      - task --list
