version: "3"

vars:
  BUNDLER_VERSION: "2.7.2"
  RBENV_BIN: "/opt/homebrew/bin/rbenv"
  RBENV_VERSION: "3.4.7"
  RBENV_RUBY:
    sh: RBENV_VERSION={{.RBENV_VERSION}} {{.RBENV_BIN}} which ruby

env:
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: plain
  RUBY: "{{.RBENV_RUBY}}"

tasks:
  setup:
    desc: "Install language dependencies, developer tooling, and hooks"
    cmds:
      - task: python:install
      - task: rust:install-tools
      - task: node:install
      - task: ruby:install
      - task: pre-commit:install
      - task: build:py

  update:
    desc: "Update workspace dependencies across languages"
    cmds:
      - task: python:update
      - task: rust:update
      - corepack up
      - corepack enable
      - task: node:update
      - task: ruby:update
      - task: build:py
      - task: pre-commit:update

  python:install:
    desc: "Install Python dependencies with uv"
    cmds:
      - uv sync --all-extras --all-groups

  python:update:
    desc: "Upgrade Python dependencies"
    cmds:
      - uv run uv-bump
      - uv sync --all-extras --all-groups --upgrade

  rust:install-tools:
    desc: "Install Rust developer tooling"
    cmds:
      - uv tool install cargo-binstall
      - uv tool install cargo-upgrade

  rust:update:
    desc: "Upgrade Rust dependencies"
    cmds:
      - cargo upgrade --incompatible
      - cargo update

  ruby:install:
    desc: "Install Ruby dependencies"
    dir: packages/ruby
    cmds:
      - RBENV_VERSION={{.RBENV_VERSION}} {{.RBENV_BIN}} exec bundle _{{.BUNDLER_VERSION}}_ check || RBENV_VERSION={{.RBENV_VERSION}} {{.RBENV_BIN}} exec bundle _{{.BUNDLER_VERSION}}_ install --jobs 4 --retry 3

  ruby:update:
    desc: "Update Ruby dependencies"
    dir: packages/ruby
    cmds:
      - RBENV_VERSION={{.RBENV_VERSION}} {{.RBENV_BIN}} exec bundle _{{.BUNDLER_VERSION}}_ update

  ruby:build:
    desc: "Build Ruby native extension"
    deps:
      - ruby:install
    dir: packages/ruby
    cmds:
      - RBENV_VERSION={{.RBENV_VERSION}} {{.RBENV_BIN}} exec bundle _{{.BUNDLER_VERSION}}_ exec rake ext:build

  ruby:test:
    desc: "Run Ruby specs"
    deps:
      - ruby:build
    dir: packages/ruby
    cmds:
      - RBENV_VERSION={{.RBENV_VERSION}} {{.RBENV_BIN}} exec bundle _{{.BUNDLER_VERSION}}_ exec rspec

  pre-commit:install:
    desc: "Install pre-commit hooks via Prek"
    cmds:
      - prek install
      - prek install --hook-type commit-msg

  pre-commit:update:
    desc: "Update Prek hooks"
    cmds:
      - prek autoupdate

  python:test:
    desc: "Run Python integration tests"
    deps:
      - build:py
    cmds:
      - PYTHONPATH=packages/python uv run pytest packages/python/tests -v

  test:python:
    desc: "Alias for python:test"
    cmds:
      - task: python:test

  python:lint:
    desc: "Run Python linters"
    cmds:
      - uv run ruff check .
      - uv run mypy benchmarks tools packages/python

  python:format:
    desc: "Format Python code with Ruff"
    cmds:
      - uv run ruff check --fix .
      - uv run ruff format .

  rust:test:
    desc: "Run Rust workspace tests"
    cmds:
      - cargo test --workspace --release

  test:rust:
    desc: "Alias for rust:test"
    cmds:
      - task: rust:test

  check:rust:
    desc: "Fast check of Rust code (no codegen)"
    cmds:
      - cargo check --workspace --all-features

  clippy:rust:
    desc: "Run Rust linter (clippy)"
    cmds:
      - cargo clippy --workspace --all-features -- -D warnings

  fmt:rust:
    desc: "Format Rust code"
    cmds:
      - cargo fmt --all

  fmt:rust:check:
    desc: "Check Rust formatting without modifying files"
    cmds:
      - cargo fmt --all --check

  node:install:
    desc: "Install Node.js dependencies with pnpm"
    cmds:
      - corepack enable
      - pnpm install --frozen-lockfile

  node:update:
    desc: "Update Node.js dependencies with pnpm"
    cmds:
      - corepack enable
      - pnpm up --latest -r

  node:lint:
    desc: "Lint TypeScript code with biome and oxlint"
    cmds:
      - pnpm biome check packages/node/src crates/spikard-node/src e2e/node --log-level=warn
      - pnpm oxlint packages/node/src crates/spikard-node/src e2e/node

  ruby:lint:
    desc: "Lint Ruby bindings with Rubocop"
    deps:
      - ruby:install
    dir: packages/ruby
    cmds:
      - RBENV_VERSION={{.RBENV_VERSION}} {{.RBENV_BIN}} exec bundle _{{.BUNDLER_VERSION}}_ exec rubocop

  node:format:
    desc: "Format TypeScript code with biome"
    cmds:
      - pnpm biome format --write packages/node/src crates/spikard-node/src e2e/node

  node:format:check:
    desc: "Check TypeScript formatting without modifying files"
    cmds:
      - pnpm biome format packages/node/src crates/spikard-node/src e2e/node

  node:test:
    desc: "Run vitest unit tests in packages/node"
    dir: packages/node
    cmds:
      - pnpm test

  build:rust:
    desc: "Build Rust workspace in release mode"
    cmds:
      - cargo build --workspace --release

  build:rust:debug:
    desc: "Build Rust workspace in debug mode"
    cmds:
      - cargo build --workspace

  test:
    desc: "Run core language test suites"
    cmds:
      - task: test:rust
      - task: test:python
      - task: node:test
      - task: ruby:test

  lint:
    desc: "Run workspace linters for Rust, Python, TypeScript, and Ruby"
    cmds:
      - task: fmt:rust:check
      - task: clippy:rust
      - task: python:lint
      - task: node:lint
      - task: ruby:lint

  fmt:
    desc: "Format Python, Rust, and TypeScript code"
    cmds:
      - task: fmt:rust
      - task: python:format
      - task: node:format

  check:
    desc: "Fast check of Python and Rust code"
    cmds:
      - task: check:rust
      - uv run ruff check .

  build:py:
    desc: "Build Python bindings for development"
    cmds:
      - uv pip install -e crates/spikard-py --config-settings='--build-option=--release'

  build:py:debug:
    desc: "Build Python bindings in debug mode"
    cmds:
      - uv pip install -e crates/spikard-py

  build:py:wheel:
    desc: "Build Python bindings as wheel for testing (release mode)"
    dir: crates/spikard-py
    cmds:
      - uv run maturin build --release --out ../../target/wheels
      - uv pip install --force-reinstall ../../target/wheels/spikard_bindings-0.1.0-cp310-abi3-macosx_11_0_arm64.whl

  build:local:python:
    desc: "Clean rebuild Python bindings for local testing (removes cached .so files)"
    cmds:
      - cargo clean
      - rm -rf .venv/lib/python*/site-packages/_spikard
      - task: build:py:debug

  build:
    desc: "Build Rust components for development"
    cmds:
      - task: build:py

  build:debug:
    desc: "Build Rust components in debug mode"
    cmds:
      - task: build:py:debug

  build:cli:
    desc: "Build CLI binary"
    cmds:
      - cargo build --release --package spikard-cli

  build:http:
    desc: "Build HTTP server binary"
    cmds:
      - cargo build --release --package spikard-http

  build:node:
    desc: "Build Node.js native bindings with NAPI-RS"
    dir: crates/spikard-node
    cmds:
      - pnpm run build

  build:wasm:
    desc: "Build WebAssembly bindings with wasm-bindgen"
    dir: crates/spikard-wasm
    cmds:
      - pnpm run build:all

  generate:openapi:
    desc: "Generate OpenAPI spec from test fixtures"
    cmds:
      - mkdir -p openapi-specs
      - cargo run --manifest-path tools/test-generator/Cargo.toml -- openapi --fixtures testing_data --output openapi-specs/full.yaml --title "Spikard Test API" --version "1.0.0"

  generate:tests:rust:
    desc: "Generate Rust e2e test suite from fixtures"
    cmds:
      - rm -rf e2e/rust
      - cargo run --manifest-path tools/test-generator/Cargo.toml -- tests --lang rust --output e2e/rust
      - cargo fmt --manifest-path e2e/rust/Cargo.toml

  generate:tests:python:
    desc: "Generate Python e2e test suite from fixtures"
    cmds:
      - rm -rf e2e/python
      - cargo run --manifest-path tools/test-generator/Cargo.toml -- tests --lang python --output e2e/python

  generate:tests:node:
    desc: "Generate Node.js e2e test suite from fixtures (vitest)"
    cmds:
      - rm -rf e2e/node
      - cargo run --manifest-path tools/test-generator/Cargo.toml -- tests --lang node --output e2e/node

  generate:tests:ruby:
    desc: "Generate Ruby e2e test suite from fixtures"
    cmds:
      - cargo run --manifest-path tools/test-generator/Cargo.toml -- tests --lang ruby --output e2e/ruby

  generate:tests:
    desc: "Generate all e2e test suites from fixtures"
    cmds:
      - task: generate:tests:rust
      - task: generate:tests:python
      - task: generate:tests:node
      - task: generate:tests:ruby

  verify:tests:rust:
    desc: "Regenerate and run Rust e2e suite, ensuring no diff"
    cmds:
      - task: generate:tests:rust
      - task: test:e2e:rust
      - git diff --exit-code

  verify:tests:python:
    desc: "Regenerate and run Python e2e suite, ensuring no diff"
    cmds:
      - task: generate:tests:python
      - task: test:e2e:python
      - git diff --exit-code

  verify:tests:node:
    desc: "Regenerate and run Node e2e suite, ensuring no diff"
    cmds:
      - task: generate:tests:node
      - task: test:e2e:node
      - git diff --exit-code

  verify:tests:ruby:
    desc: "Regenerate and run Ruby e2e suite, ensuring no diff"
    cmds:
      - task: generate:tests:ruby
      - task: test:e2e:ruby
      - git diff --exit-code

  verify:tests:
    desc: "Verify all e2e suites are up to date and pass"
    cmds:
      - task: verify:tests:rust
      - task: verify:tests:python
      - task: verify:tests:node
      - task: verify:tests:ruby

  clean:generated:
    desc: "Remove all generated e2e test infrastructure"
    cmds:
      - rm -rf e2e/
      - rm -rf openapi-specs/

  test:e2e:rust:
    desc: "Run Rust e2e tests (fixture-driven integration tests)"
    cmds:
      - PYTHONPATH=packages/python cargo test --manifest-path e2e/rust/Cargo.toml

  test:e2e:python:
    desc: "Run Python e2e tests (fixture-driven integration tests)"
    dir: e2e/python
    cmds:
      - PYTHONPATH=../../packages/python uv run pytest tests/ -v

  test:e2e:node:
    desc: "Run Node.js e2e tests (fixture-driven integration tests with vitest)"
    dir: e2e/node
    deps:
      - build:node
    cmds:
      - pnpm test

  test:e2e:ruby:
    desc: "Run Ruby e2e tests (fixture-driven integration tests)"
    dir: e2e/ruby
    cmds:
      - BUNDLE_GEMFILE=../../packages/ruby/Gemfile RBENV_VERSION={{.RBENV_VERSION}} {{.RBENV_BIN}} exec bundle _{{.BUNDLER_VERSION}}_ check || BUNDLE_GEMFILE=../../packages/ruby/Gemfile RBENV_VERSION={{.RBENV_VERSION}} {{.RBENV_BIN}} exec bundle _{{.BUNDLER_VERSION}}_ install --jobs 4 --retry 3
      - BUNDLE_GEMFILE=../../packages/ruby/Gemfile RBENV_VERSION={{.RBENV_VERSION}} {{.RBENV_BIN}} exec bundle _{{.BUNDLER_VERSION}}_ exec rake -C ../../packages/ruby ext:build
      - BUNDLE_GEMFILE=../../packages/ruby/Gemfile RBENV_VERSION={{.RBENV_VERSION}} {{.RBENV_BIN}} exec bundle _{{.BUNDLER_VERSION}}_ exec rspec

  test:e2e:
    desc: "Run all e2e fixture-driven integration tests"
    cmds:
      - task: test:e2e:rust
      - task: test:e2e:python
      - task: test:e2e:node
      - task: test:e2e:ruby

  build:js:
    desc: "Build all JavaScript/TypeScript packages (node, wasm)"
    cmds:
      - task: build:node
      - task: build:wasm

  run:cli:
    desc: "Run the CLI tool"
    cmds:
      - cargo run --package spikard-cli -- {{.CLI_ARGS}}

  run:http:
    desc: "Run the HTTP server"
    cmds:
      - cargo run --package spikard-http

  cov:rust:
    desc: "Generate Rust code coverage report (requires cargo-llvm-cov)"
    cmds:
      - cargo llvm-cov --workspace --lcov --output-path rust-coverage.lcov
      - echo "Rust coverage report generated at rust-coverage.lcov"
      - cargo llvm-cov --workspace --summary-only

  cov:python:
    desc: "Generate Python code coverage report"
    cmds:
      - uv run pytest tests/ --cov=spikard --cov-report=lcov:coverage.lcov --cov-report=term
      - echo "Python coverage report generated at coverage.lcov"

  cov:all:
    desc: "Generate both Rust and Python coverage reports"
    cmds:
      - task: cov:rust
      - task: cov:python

  clean:
    desc: "Clean build artifacts"
    cmds:
      - cargo clean
      - rm -rf target/
      - rm -rf .pytest_cache/
      - rm -rf .mypy_cache/
      - rm -rf .ruff_cache/
      - find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
      - find . -type f -name "*.pyc" -delete
      - find crates -type d -name "dist" -exec rm -rf {} + 2>/dev/null || true
      - find crates -type d -name "node_modules" -exec rm -rf {} + 2>/dev/null || true

  # ============================================================================
  # Benchmark Generation & Execution
  # ============================================================================

  bench:generator:build:
    desc: "Build the app-generator tool"
    cmds:
      - cargo build --release --manifest-path tools/app-generator/Cargo.toml

  bench:harness:build:
    desc: "Build the benchmark-harness tool"
    cmds:
      - cargo build --release --manifest-path tools/benchmark-harness/Cargo.toml

  bench:tools:build:
    desc: "Build both benchmark tools (generator + harness)"
    cmds:
      - task: bench:generator:build
      - task: bench:harness:build

  bench:generate:python:
    desc: "Generate Spikard-Python benchmark server from fixtures"
    deps:
      - bench:generator:build
    cmds:
      - rm -rf tools/benchmark-harness/apps/spikard-python
      - ./tools/app-generator/target/release/app-generator generate --framework spikard-python --fixtures testing_data --categories query_params,json_bodies,path_params --output tools/benchmark-harness/apps/spikard-python
      - task: bench:format:python
      - task: bench:lint:python

  bench:generate:rust:
    desc: "Generate Spikard-Rust benchmark server from fixtures"
    deps:
      - bench:generator:build
    cmds:
      - rm -rf tools/benchmark-harness/apps/spikard-rust-gen
      - ./tools/app-generator/target/release/app-generator generate --framework spikard-rust --fixtures testing_data --categories query_params,json_bodies,path_params --output tools/benchmark-harness/apps/spikard-rust-gen
      - task: bench:format:rust:gen
      - task: bench:lint:rust:gen

  bench:generate:node:
    desc: "Generate Spikard-Node benchmark server from fixtures"
    deps:
      - bench:generator:build
    cmds:
      - rm -rf tools/benchmark-harness/apps/spikard-node
      - ./tools/app-generator/target/release/app-generator generate --framework spikard-node --fixtures testing_data --categories query_params,json_bodies,path_params --output tools/benchmark-harness/apps/spikard-node
      - task: bench:format:node
      - task: bench:lint:node

  bench:generate:ruby:
    desc: "Generate Spikard-Ruby benchmark server from fixtures"
    deps:
      - bench:generator:build
    cmds:
      - rm -rf tools/benchmark-harness/apps/spikard-ruby
      - ./tools/app-generator/target/release/app-generator generate --framework spikard-ruby --fixtures testing_data --categories query_params,json_bodies,path_params --output tools/benchmark-harness/apps/spikard-ruby
      - task: bench:lint:ruby

  bench:generate:all:
    desc: "Generate all benchmark servers (Python, Rust, Node, Ruby)"
    cmds:
      - task: bench:generate:python
      - task: bench:generate:rust
      - task: bench:generate:node
      - task: bench:generate:ruby

  bench:format:python:
    desc: "Format generated Python benchmark code"
    cmds:
      - uv run ruff format tools/benchmark-harness/apps/spikard-python/ || true
      - uv run ruff check --fix tools/benchmark-harness/apps/spikard-python/ || true

  bench:lint:python:
    desc: "Lint generated Python benchmark code"
    cmds:
      - uv run ruff check tools/benchmark-harness/apps/spikard-python/
      - uv run mypy tools/benchmark-harness/apps/spikard-python/ || true

  bench:format:rust:gen:
    desc: "Format generated Rust benchmark code"
    cmds:
      - cargo fmt --manifest-path tools/benchmark-harness/apps/spikard-rust-gen/Cargo.toml || true

  bench:lint:rust:gen:
    desc: "Lint generated Rust benchmark code"
    cmds:
      - cargo clippy --manifest-path tools/benchmark-harness/apps/spikard-rust-gen/Cargo.toml -- -D warnings || true

  bench:format:node:
    desc: "Format generated Node benchmark code"
    cmds:
      - pnpm biome format --write tools/benchmark-harness/apps/spikard-node/ || true

  bench:lint:node:
    desc: "Lint generated Node benchmark code"
    cmds:
      - pnpm biome check tools/benchmark-harness/apps/spikard-node/ || true
      - pnpm oxlint tools/benchmark-harness/apps/spikard-node/ || true

  bench:lint:ruby:
    desc: "Lint generated Ruby benchmark code"
    deps:
      - ruby:install
    cmds:
      - RBENV_VERSION={{.RBENV_VERSION}} {{.RBENV_BIN}} exec bundle _{{.BUNDLER_VERSION}}_ exec rubocop tools/benchmark-harness/apps/spikard-ruby/ || true

  bench:build:python:
    desc: "Verify generated Python benchmark app loads"
    deps:
      - build:py
    cmds:
      - PYTHONPATH=packages/python uv run python -m py_compile tools/benchmark-harness/apps/spikard-python/server.py

  bench:build:rust:
    desc: "Build generated Rust benchmark server"
    cmds:
      - cargo build --release --manifest-path tools/benchmark-harness/apps/spikard-rust/Cargo.toml

  bench:build:rust:gen:
    desc: "Build generated Rust benchmark server (from generator)"
    cmds:
      - cargo build --release --manifest-path tools/benchmark-harness/apps/spikard-rust-gen/Cargo.toml

  bench:build:all:
    desc: "Build all benchmark servers"
    cmds:
      - task: bench:build:python
      - task: bench:build:rust
      - task: bench:build:rust:gen

  bench:run:python:
    desc: "Run benchmark against Spikard-Python server"
    deps:
      - bench:harness:build
      - bench:build:python
    cmds:
      - ./target/release/benchmark-harness run --framework spikard-python --app-dir tools/benchmark-harness/apps/spikard-python --workload query-params --duration 10 --concurrency 50 --warmup 3 --output tools/benchmark-harness/results/spikard-python.json

  bench:run:rust:
    desc: "Run benchmark against Spikard-Rust server"
    deps:
      - bench:harness:build
      - bench:build:rust
    cmds:
      - ./target/release/benchmark-harness run --framework spikard-rust --app-dir tools/benchmark-harness/apps/spikard-rust --workload baseline --duration 10 --concurrency 50 --warmup 3 --output tools/benchmark-harness/results/spikard-rust.json

  bench:run:all:
    desc: "Run benchmarks for all frameworks"
    cmds:
      - task: bench:run:python
      - task: bench:run:rust

  bench:analyze:
    desc: "Analyze fixtures and show statistics"
    deps:
      - bench:generator:build
    cmds:
      - ./tools/app-generator/target/release/app-generator analyze --fixtures testing_data

  bench:clean:
    desc: "Clean generated benchmark apps and results"
    cmds:
      - rm -rf tools/benchmark-harness/apps/spikard-python
      - rm -rf tools/benchmark-harness/apps/spikard-rust-gen
      - rm -rf tools/benchmark-harness/apps/spikard-node
      - rm -rf tools/benchmark-harness/apps/spikard-ruby
      - rm -rf tools/benchmark-harness/results/*.json

  bench:
    desc: "Full benchmark workflow: generate, lint, build, and run"
    cmds:
      - task: bench:generate:all
      - task: bench:build:all
      - task: bench:run:all
      - echo "Benchmark results in tools/benchmark-harness/results/"

  default:
    desc: "Show available tasks"
    cmds:
      - task --list
