# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:99f07149635b12bdf67640e73e74931cf039fb6ce73f40f59e4afdb9a467375c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'spec_helper'
require 'spikard'
require 'json'

RSpec.describe 'auth' do
  let(:mock_server_url) { ENV.fetch('MOCK_SERVER_URL', 'http://localhost:8080') }
  describe 'api_key_authentication_invalid_key' do
    it 'Tests API key authentication failure when provided key is not in the valid keys list.' do
      require 'net/http'
      require 'uri'
      require 'json'
      base_url = ENV.fetch('SUT_URL', 'http://127.0.0.1:8000')
      uri = URI.parse("#{base_url}/fixtures/api_key_authentication_invalid_key/api/data")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == 'https'
      _headers = {
      'X-API-Key' => 'invalid_key_12345',
    }.dup
      _req = Net::HTTP::Get.new(uri.request_uri, _headers)
      response = http.request(_req)
      expect(response.code.to_i).to eq(401)
      _body = response.body && !response.body.empty? ? JSON.parse(response.body) : nil
      expect(_body).to eq({ 'detail' => 'The provided API key is not valid', 'status' => 401, 'title' => 'Invalid API key', 'type' => 'https://spikard.dev/errors/unauthorized' })
    end
  end

  describe 'api_key_authentication_missing_header' do
    it 'Tests API key authentication failure when required header is not provided.' do
      require 'net/http'
      require 'uri'
      require 'json'
      base_url = ENV.fetch('SUT_URL', 'http://127.0.0.1:8000')
      uri = URI.parse("#{base_url}/fixtures/api_key_authentication_missing_header/api/data")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == 'https'
      _headers = {}.dup
      _req = Net::HTTP::Get.new(uri.request_uri, _headers)
      response = http.request(_req)
      expect(response.code.to_i).to eq(401)
      _body = response.body && !response.body.empty? ? JSON.parse(response.body) : nil
      expect(_body).to eq({ 'detail' => "Expected 'X-API-Key' header or 'api_key' query parameter with valid API key", 'status' => 401, 'title' => 'Missing API key', 'type' => 'https://spikard.dev/errors/unauthorized' })
    end
  end

  describe 'api_key_authentication_valid_key' do
    it 'Tests API key authentication with a valid API key in custom header.' do
      require 'net/http'
      require 'uri'
      require 'json'
      base_url = ENV.fetch('SUT_URL', 'http://127.0.0.1:8000')
      uri = URI.parse("#{base_url}/fixtures/api_key_authentication_valid_key/api/data")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == 'https'
      _headers = {
      'X-API-Key' => 'sk_test_123456',
    }.dup
      _req = Net::HTTP::Get.new(uri.request_uri, _headers)
      response = http.request(_req)
      expect(response.code.to_i).to eq(200)
      _body = response.body && !response.body.empty? ? JSON.parse(response.body) : nil
      expect(_body).to eq({ 'data' => 'sensitive information', 'message' => 'Access granted' })
    end
  end

  describe 'api_key_custom_header_x_api_token' do
    it 'Tests API key authentication with custom X-API-Token header.' do
      require 'net/http'
      require 'uri'
      require 'json'
      base_url = ENV.fetch('SUT_URL', 'http://127.0.0.1:8000')
      uri = URI.parse("#{base_url}/fixtures/api_key_custom_header_x_api_token/api/resource")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == 'https'
      _headers = {
      'X-API-Token' => 'token_xyz789',
    }.dup
      _req = Net::HTTP::Get.new(uri.request_uri, _headers)
      response = http.request(_req)
      expect(response.code.to_i).to eq(200)
      _body = response.body && !response.body.empty? ? JSON.parse(response.body) : nil
      expect(_body).to eq({ 'resource' => 'data' })
    end
  end

  describe 'api_key_in_query_parameter' do
    it 'Tests API key authentication when key is provided as query parameter instead of header.' do
      require 'net/http'
      require 'uri'
      require 'json'
      base_url = ENV.fetch('SUT_URL', 'http://127.0.0.1:8000')
      uri = URI.parse("#{base_url}/fixtures/api_key_in_query_parameter/api/data?api_key=sk_test_123456")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == 'https'
      _headers = {}.dup
      _req = Net::HTTP::Get.new(uri.request_uri, _headers)
      response = http.request(_req)
      expect(response.code.to_i).to eq(200)
      _body = response.body && !response.body.empty? ? JSON.parse(response.body) : nil
      expect(_body).to eq({ 'data' => 'sensitive information', 'message' => 'Access granted' })
    end
  end

  describe 'api_key_multiple_valid_keys' do
    it 'Tests API key authentication accepts multiple valid keys.' do
      require 'net/http'
      require 'uri'
      require 'json'
      base_url = ENV.fetch('SUT_URL', 'http://127.0.0.1:8000')
      uri = URI.parse("#{base_url}/fixtures/api_key_multiple_valid_keys/api/endpoint")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == 'https'
      _headers = {
      'X-API-Key' => 'key_staging_001',
    }.dup
      _req = Net::HTTP::Get.new(uri.request_uri, _headers)
      response = http.request(_req)
      expect(response.code.to_i).to eq(200)
      _body = response.body && !response.body.empty? ? JSON.parse(response.body) : nil
      expect(_body).to eq({ 'message' => 'Authenticated with staging key' })
    end
  end

  describe 'api_key_rotation_old_key_still_valid' do
    it 'Tests API key authentication during rotation period when old key remains valid alongside new key.' do
      require 'net/http'
      require 'uri'
      require 'json'
      base_url = ENV.fetch('SUT_URL', 'http://127.0.0.1:8000')
      uri = URI.parse("#{base_url}/fixtures/api_key_rotation_old_key_still_valid/api/data")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == 'https'
      _headers = {
      'X-API-Key' => 'sk_test_old_123456',
    }.dup
      _req = Net::HTTP::Get.new(uri.request_uri, _headers)
      response = http.request(_req)
      expect(response.code.to_i).to eq(200)
      expect(response['X-API-Key-Deprecated']).to eq('true')
      _body = response.body && !response.body.empty? ? JSON.parse(response.body) : nil
      expect(_body).to eq({ 'data' => 'sensitive information', 'message' => 'Access granted' })
    end
  end

  describe 'api_key_with_custom_header_name' do
    it 'Tests API key authentication with a custom header name (X-API-Token instead of X-API-Key).' do
      require 'net/http'
      require 'uri'
      require 'json'
      base_url = ENV.fetch('SUT_URL', 'http://127.0.0.1:8000')
      uri = URI.parse("#{base_url}/fixtures/api_key_with_custom_header_name/api/data")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == 'https'
      _headers = {
      'X-API-Token' => 'sk_test_123456',
    }.dup
      _req = Net::HTTP::Get.new(uri.request_uri, _headers)
      response = http.request(_req)
      expect(response.code.to_i).to eq(200)
      _body = response.body && !response.body.empty? ? JSON.parse(response.body) : nil
      expect(_body).to eq({ 'data' => 'sensitive information', 'message' => 'Access granted' })
    end
  end

  describe 'bearer_token_without_prefix' do
    it "Tests JWT rejection when token is provided without 'Bearer ' prefix in Authorization header." do
      require 'net/http'
      require 'uri'
      require 'json'
      base_url = ENV.fetch('SUT_URL', 'http://127.0.0.1:8000')
      uri = URI.parse("#{base_url}/fixtures/bearer_token_without_prefix/api/protected")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == 'https'
      _headers = {
      'Authorization' => 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMTIzIiwiZXhwIjoyNjI2NzgzOTQ2LCJpYXQiOjE3NjI3ODM5NDZ9.8yXqZ9jKCR0BwqJc7pN_QvD3mYLxHfWzUeIaGkTnOsA',
    }.dup
      _req = Net::HTTP::Get.new(uri.request_uri, _headers)
      response = http.request(_req)
      expect(response.code.to_i).to eq(401)
      _body = response.body && !response.body.empty? ? JSON.parse(response.body) : nil
      expect(_body).to eq({ 'detail' => "Authorization header must use Bearer scheme: 'Bearer <token>'", 'status' => 401, 'title' => 'Invalid Authorization header format', 'type' => 'https://spikard.dev/errors/unauthorized' })
    end
  end

  describe 'jwt_audience_claim_aud_field' do
    it 'Tests JWT validation of audience (aud) claim.' do
      require 'net/http'
      require 'uri'
      require 'json'
      base_url = ENV.fetch('SUT_URL', 'http://127.0.0.1:8000')
      uri = URI.parse("#{base_url}/fixtures/jwt_audience_claim_aud_field/api/protected")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == 'https'
      _headers = {
      'Authorization' => 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMTIzIiwiZXhwIjoyNjI2NzgzOTQ2LCJpYXQiOjE3NjI3ODM5NDYsImF1ZCI6WyJodHRwczovL2FwaS5leGFtcGxlLmNvbSJdfQ.test',
    }.dup
      _req = Net::HTTP::Get.new(uri.request_uri, _headers)
      response = http.request(_req)
      expect(response.code.to_i).to eq(200)
      _body = response.body && !response.body.empty? ? JSON.parse(response.body) : nil
      expect(_body).to eq({ 'message' => 'Access granted' })
    end
  end

  describe 'jwt_authentication_expired_token' do
    it 'Tests JWT authentication failure when token has expired (exp claim in the past).' do
      require 'net/http'
      require 'uri'
      require 'json'
      base_url = ENV.fetch('SUT_URL', 'http://127.0.0.1:8000')
      uri = URI.parse("#{base_url}/fixtures/jwt_authentication_expired_token/protected/user")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == 'https'
      _headers = {
      'Authorization' => 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMTIzIiwiZXhwIjoxNjAwMDAwMDAwLCJpYXQiOjE1OTAwMDAwMDB9.n4oBw9XuO2aAJWi1e4Bz9Y_m2iEyJHGAODcetNuwYFo',
    }.dup
      _req = Net::HTTP::Get.new(uri.request_uri, _headers)
      response = http.request(_req)
      expect(response.code.to_i).to eq(401)
      _body = response.body && !response.body.empty? ? JSON.parse(response.body) : nil
      expect(_body).to eq({ 'detail' => 'Token has expired', 'status' => 401, 'title' => 'JWT validation failed', 'type' => 'https://spikard.dev/errors/unauthorized' })
    end
  end

  describe 'jwt_authentication_invalid_audience' do
    it 'Tests JWT authentication failure when token audience claim does not match required audience.' do
      require 'net/http'
      require 'uri'
      require 'json'
      base_url = ENV.fetch('SUT_URL', 'http://127.0.0.1:8000')
      uri = URI.parse("#{base_url}/fixtures/jwt_authentication_invalid_audience/protected/user")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == 'https'
      _headers = {
      'Authorization' => 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMTIzIiwiZXhwIjoyNTM0MDIzMDA3OTk5LCJpYXQiOjE3MzEyNTIwMDAsImF1ZCI6WyJodHRwczovL3dyb25nLXNlcnZpY2UuY29tIl19.YR2a9fSJjhen7ksYFI2djSBSC7Pc29FDCloBGhkj3kU',
    }.dup
      _req = Net::HTTP::Get.new(uri.request_uri, _headers)
      response = http.request(_req)
      expect(response.code.to_i).to eq(401)
      _body = response.body && !response.body.empty? ? JSON.parse(response.body) : nil
      expect(_body).to eq({ 'detail' => 'Token audience is invalid', 'status' => 401, 'title' => 'JWT validation failed', 'type' => 'https://spikard.dev/errors/unauthorized' })
    end
  end

  describe 'jwt_authentication_invalid_signature' do
    it 'Tests JWT authentication failure when token signature does not match the secret.' do
      require 'net/http'
      require 'uri'
      require 'json'
      base_url = ENV.fetch('SUT_URL', 'http://127.0.0.1:8000')
      uri = URI.parse("#{base_url}/fixtures/jwt_authentication_invalid_signature/protected/user")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == 'https'
      _headers = {
      'Authorization' => 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMTIzIiwiZXhwIjoyNTM0MDIzMDA3OTksImlhdCI6MTczMTI1MjAwMH0.invalid_signature_here',
    }.dup
      _req = Net::HTTP::Get.new(uri.request_uri, _headers)
      response = http.request(_req)
      expect(response.code.to_i).to eq(401)
      _body = response.body && !response.body.empty? ? JSON.parse(response.body) : nil
      expect(_body).to eq({ 'detail' => 'Token signature is invalid', 'status' => 401, 'title' => 'JWT validation failed', 'type' => 'https://spikard.dev/errors/unauthorized' })
    end
  end

  describe 'jwt_authentication_missing_authorization_header' do
    it 'Tests JWT authentication failure when Authorization header is not provided.' do
      require 'net/http'
      require 'uri'
      require 'json'
      base_url = ENV.fetch('SUT_URL', 'http://127.0.0.1:8000')
      uri = URI.parse("#{base_url}/fixtures/jwt_authentication_missing_authorization_header/protected/user")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == 'https'
      _headers = {}.dup
      _req = Net::HTTP::Get.new(uri.request_uri, _headers)
      response = http.request(_req)
      expect(response.code.to_i).to eq(401)
      _body = response.body && !response.body.empty? ? JSON.parse(response.body) : nil
      expect(_body).to eq({ 'detail' => "Expected 'Authorization: Bearer <token>'", 'status' => 401, 'title' => 'Missing or invalid Authorization header', 'type' => 'https://spikard.dev/errors/unauthorized' })
    end
  end

  describe 'jwt_authentication_valid_token' do
    it 'Tests JWT authentication with a valid token containing correct signature and claims.' do
      require 'net/http'
      require 'uri'
      require 'json'
      base_url = ENV.fetch('SUT_URL', 'http://127.0.0.1:8000')
      uri = URI.parse("#{base_url}/fixtures/jwt_authentication_valid_token/protected/user")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == 'https'
      _headers = {
      'Authorization' => 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMTIzIiwiZXhwIjoyNjI2NzgzOTQ2LCJpYXQiOjE3NjI3ODM5NDYsImF1ZCI6WyJodHRwczovL2FwaS5leGFtcGxlLmNvbSJdLCJpc3MiOiJodHRwczovL2F1dGguZXhhbXBsZS5jb20ifQ.TpRpCJeXROQ12-ehRCVZm6EgN7Dn6QpfoekxJvnzgQg',
    }.dup
      _req = Net::HTTP::Get.new(uri.request_uri, _headers)
      response = http.request(_req)
      expect(response.code.to_i).to eq(200)
      _body = response.body && !response.body.empty? ? JSON.parse(response.body) : nil
      expect(_body).to eq({ 'message' => 'Access granted', 'user_id' => 'user123' })
    end
  end

  describe 'jwt_config_algorithm_rs256' do
    it 'Tests JWT validation with RS256 asymmetric algorithm.' do
      require 'net/http'
      require 'uri'
      require 'json'
      base_url = ENV.fetch('SUT_URL', 'http://127.0.0.1:8000')
      uri = URI.parse("#{base_url}/fixtures/jwt_config_algorithm_rs256/api/secure")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == 'https'
      _headers = {
      'Authorization' => 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMTIzIiwiZXhwIjoyNjI2NzgzOTQ2LCJpYXQiOjE3NjI3ODM5NDZ9.test_signature',
    }.dup
      _req = Net::HTTP::Get.new(uri.request_uri, _headers)
      response = http.request(_req)
      expect(response.code.to_i).to eq(200)
      _body = response.body && !response.body.empty? ? JSON.parse(response.body) : nil
      expect(_body).to eq({ 'message' => 'Access granted' })
    end
  end

  describe 'jwt_config_leeway_seconds' do
    it 'Tests JWT validation with leeway for clock skew.' do
      require 'net/http'
      require 'uri'
      require 'json'
      base_url = ENV.fetch('SUT_URL', 'http://127.0.0.1:8000')
      uri = URI.parse("#{base_url}/fixtures/jwt_config_leeway_seconds/api/protected")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == 'https'
      _headers = {
      'Authorization' => 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMTIzIiwiZXhwIjoxNzYyNzgzOTQ2LCJpYXQiOjE2MDAwMDAwMDB9.test',
    }.dup
      _req = Net::HTTP::Get.new(uri.request_uri, _headers)
      response = http.request(_req)
      expect(response.code.to_i).to eq(200)
      _body = response.body && !response.body.empty? ? JSON.parse(response.body) : nil
      expect(_body).to eq({ 'message' => 'Access granted with leeway' })
    end
  end

  describe 'jwt_expiration_claim_exp_field' do
    it 'Tests JWT validation of expiration (exp) claim.' do
      require 'net/http'
      require 'uri'
      require 'json'
      base_url = ENV.fetch('SUT_URL', 'http://127.0.0.1:8000')
      uri = URI.parse("#{base_url}/fixtures/jwt_expiration_claim_exp_field/api/protected")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == 'https'
      _headers = {
      'Authorization' => 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMTIzIiwiZXhwIjoyNjI2NzgzOTQ2LCJpYXQiOjE3NjI3ODM5NDZ9.test',
    }.dup
      _req = Net::HTTP::Get.new(uri.request_uri, _headers)
      response = http.request(_req)
      expect(response.code.to_i).to eq(200)
      _body = response.body && !response.body.empty? ? JSON.parse(response.body) : nil
      expect(_body).to eq({ 'message' => 'Access granted' })
    end
  end

  describe 'jwt_invalid_issuer' do
    it "Tests JWT rejection when issuer claim doesn't match expected value." do
      require 'net/http'
      require 'uri'
      require 'json'
      base_url = ENV.fetch('SUT_URL', 'http://127.0.0.1:8000')
      uri = URI.parse("#{base_url}/fixtures/jwt_invalid_issuer/api/protected")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == 'https'
      _headers = {
      'Authorization' => 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMTIzIiwiZXhwIjoyNjI2NzgzOTQ2LCJpYXQiOjE2MDAwMDAwMDAsImF1ZCI6WyJodHRwczovL2FwaS5leGFtcGxlLmNvbSJdLCJpc3MiOiJodHRwczovL2V2aWwuY29tIn0.mbL5L04_hpaaiz0SPABap6ZWfBLu18aiexBjzwQ1nnA',
    }.dup
      _req = Net::HTTP::Get.new(uri.request_uri, _headers)
      response = http.request(_req)
      expect(response.code.to_i).to eq(401)
      _body = response.body && !response.body.empty? ? JSON.parse(response.body) : nil
      expect(_body).to eq({ 'detail' => "Token issuer is invalid, expected 'https://auth.example.com'", 'status' => 401, 'title' => 'JWT validation failed', 'type' => 'https://spikard.dev/errors/unauthorized' })
    end
  end

  describe 'jwt_issuer_claim_iss_field' do
    it 'Tests JWT validation of issuer (iss) claim.' do
      require 'net/http'
      require 'uri'
      require 'json'
      base_url = ENV.fetch('SUT_URL', 'http://127.0.0.1:8000')
      uri = URI.parse("#{base_url}/fixtures/jwt_issuer_claim_iss_field/api/protected")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == 'https'
      _headers = {
      'Authorization' => 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMTIzIiwiZXhwIjoyNjI2NzgzOTQ2LCJpYXQiOjE3NjI3ODM5NDYsImlzcyI6Imh0dHBzOi8vYXV0aC5leGFtcGxlLmNvbSJ9.test',
    }.dup
      _req = Net::HTTP::Get.new(uri.request_uri, _headers)
      response = http.request(_req)
      expect(response.code.to_i).to eq(200)
      _body = response.body && !response.body.empty? ? JSON.parse(response.body) : nil
      expect(_body).to eq({ 'message' => 'Access granted' })
    end
  end

  describe 'jwt_malformed_token_format' do
    it "Tests JWT rejection when token doesn't have the required 3-part structure (header.payload.signature)." do
      require 'net/http'
      require 'uri'
      require 'json'
      base_url = ENV.fetch('SUT_URL', 'http://127.0.0.1:8000')
      uri = URI.parse("#{base_url}/fixtures/jwt_malformed_token_format/api/protected")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == 'https'
      _headers = {
      'Authorization' => 'Bearer invalid.token',
    }.dup
      _req = Net::HTTP::Get.new(uri.request_uri, _headers)
      response = http.request(_req)
      expect(response.code.to_i).to eq(401)
      _body = response.body && !response.body.empty? ? JSON.parse(response.body) : nil
      expect(_body).to eq({ 'detail' => 'Malformed JWT token: expected 3 parts separated by dots, found 2', 'status' => 401, 'title' => 'Malformed JWT token', 'type' => 'https://spikard.dev/errors/unauthorized' })
    end
  end

  describe 'jwt_missing_required_custom_claims' do
    it 'Tests JWT rejection when required custom claims (role, permissions) are missing.' do
      require 'net/http'
      require 'uri'
      require 'json'
      base_url = ENV.fetch('SUT_URL', 'http://127.0.0.1:8000')
      uri = URI.parse("#{base_url}/fixtures/jwt_missing_required_custom_claims/api/admin")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == 'https'
      _headers = {
      'Authorization' => 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMTIzIiwiZXhwIjoyNjI2NzgzOTQ2LCJpYXQiOjE3NjI3ODM5NDYsImF1ZCI6WyJodHRwczovL2FwaS5leGFtcGxlLmNvbSJdLCJpc3MiOiJodHRwczovL2F1dGguZXhhbXBsZS5jb20ifQ.TpRpCJeXROQ12-ehRCVZm6EgN7Dn6QpfoekxJvnzgQg',
    }.dup
      _req = Net::HTTP::Get.new(uri.request_uri, _headers)
      response = http.request(_req)
      expect(response.code.to_i).to eq(403)
      _body = response.body && !response.body.empty? ? JSON.parse(response.body) : nil
      expect(_body).to eq({ 'detail' => "Required claims 'role' and 'permissions' missing from JWT", 'status' => 403, 'title' => 'Forbidden', 'type' => 'https://spikard.dev/errors/forbidden' })
    end
  end

  describe 'jwt_not_before_claim_in_future' do
    it 'Tests JWT rejection when nbf (not before) claim is in the future.' do
      require 'net/http'
      require 'uri'
      require 'json'
      base_url = ENV.fetch('SUT_URL', 'http://127.0.0.1:8000')
      uri = URI.parse("#{base_url}/fixtures/jwt_not_before_claim_in_future/api/protected")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == 'https'
      _headers = {
      'Authorization' => 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMTIzIiwiZXhwIjoyNjI2NzgzOTQ2LCJpYXQiOjE2MDAwMDAwMDAsIm5iZiI6MjYyNjc4Mzk0NiwiYXVkIjpbImh0dHBzOi8vYXBpLmV4YW1wbGUuY29tIl0sImlzcyI6Imh0dHBzOi8vYXV0aC5leGFtcGxlLmNvbSJ9.hG4I76_3kJfsbJ_jmxoP1NSYnkcqdyBFcPpdo-jYU4E',
    }.dup
      _req = Net::HTTP::Get.new(uri.request_uri, _headers)
      response = http.request(_req)
      expect(response.code.to_i).to eq(401)
      _body = response.body && !response.body.empty? ? JSON.parse(response.body) : nil
      expect(_body).to eq({ 'detail' => 'JWT not valid yet, not before claim is in the future', 'status' => 401, 'title' => 'JWT validation failed', 'type' => 'https://spikard.dev/errors/unauthorized' })
    end
  end

  describe 'jwt_subject_claim_sub_field' do
    it 'Tests JWT validation with subject (sub) claim.' do
      require 'net/http'
      require 'uri'
      require 'json'
      base_url = ENV.fetch('SUT_URL', 'http://127.0.0.1:8000')
      uri = URI.parse("#{base_url}/fixtures/jwt_subject_claim_sub_field/api/user")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == 'https'
      _headers = {
      'Authorization' => 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyLWFiYzEyMyIsImV4cCI6MjYyNjc4Mzk0NiwiaWF0IjoxNzYyNzgzOTQ2fQ.xYz9QaJkL5M2NpQ8RsT1UvW3XyZ4AaBbCcDdEeFfGgHhIiJ',
    }.dup
      _req = Net::HTTP::Get.new(uri.request_uri, _headers)
      response = http.request(_req)
      expect(response.code.to_i).to eq(200)
      _body = response.body && !response.body.empty? ? JSON.parse(response.body) : nil
      expect(_body).to eq({ 'user_id' => 'user-abc123' })
    end
  end

  describe 'jwt_with_multiple_audiences' do
    it 'Tests JWT validation when token has multiple audiences and one must match.' do
      require 'net/http'
      require 'uri'
      require 'json'
      base_url = ENV.fetch('SUT_URL', 'http://127.0.0.1:8000')
      uri = URI.parse("#{base_url}/fixtures/jwt_with_multiple_audiences/api/protected")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == 'https'
      _headers = {
      'Authorization' => 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMTIzIiwiZXhwIjoyNjI2NzgzOTQ2LCJpYXQiOjE2MDAwMDAwMDAsImF1ZCI6WyJodHRwczovL2FwaS5leGFtcGxlLmNvbSIsImh0dHBzOi8vYWRtaW4uZXhhbXBsZS5jb20iXSwiaXNzIjoiaHR0cHM6Ly9hdXRoLmV4YW1wbGUuY29tIn0.9MBL_XccGXfu9cDUnCpQruDMOl2hHYydzeGn-20dQOs',
    }.dup
      _req = Net::HTTP::Get.new(uri.request_uri, _headers)
      response = http.request(_req)
      expect(response.code.to_i).to eq(200)
      _body = response.body && !response.body.empty? ? JSON.parse(response.body) : nil
      expect(_body).to eq({ 'message' => 'Access granted', 'user_id' => 'user123' })
    end
  end

  describe 'multiple_authentication_schemes_jwt_precedence' do
    it 'Tests authentication when both JWT and API key are provided, JWT takes precedence.' do
      require 'net/http'
      require 'uri'
      require 'json'
      base_url = ENV.fetch('SUT_URL', 'http://127.0.0.1:8000')
      uri = URI.parse("#{base_url}/fixtures/multiple_authentication_schemes_jwt_precedence/api/data")
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = uri.scheme == 'https'
      _headers = {
      'Authorization' => 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMTIzIiwiZXhwIjoyNjI2NzgzOTQ2LCJpYXQiOjE3NjI3ODM5NDYsImF1ZCI6WyJodHRwczovL2FwaS5leGFtcGxlLmNvbSJdLCJpc3MiOiJodHRwczovL2F1dGguZXhhbXBsZS5jb20ifQ.TpRpCJeXROQ12-ehRCVZm6EgN7Dn6QpfoekxJvnzgQg',
      'X-API-Key' => 'sk_test_123456',
    }.dup
      _req = Net::HTTP::Get.new(uri.request_uri, _headers)
      response = http.request(_req)
      expect(response.code.to_i).to eq(200)
      _body = response.body && !response.body.empty? ? JSON.parse(response.body) : nil
      expect(_body).to eq({ 'auth_method' => 'jwt', 'message' => 'Access granted', 'user_id' => 'user123' })
    end
  end
end
