// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c6bfc917af56583bd6addddd2125727646ad562727339da086dbf3e2222bfaae
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: request_id
package e2e_test

import (
	"encoding/json"
	"io"
	"net/http"
	"os"
	"reflect"
	"strings"
	"testing"
)

func Test_RequestIdHeaderIsPreserved(t *testing.T) {
	// When the client supplies X-Request-ID the same value should appear on the response.
	baseURL := os.Getenv("SUT_URL")
	if baseURL == "" {
		baseURL = "http://127.0.0.1:8012"
	}
	body := strings.NewReader("")
	req, err := http.NewRequest("GET", baseURL+"/fixtures/request_id_header_is_preserved/request-id/preserved", body)
	if err != nil {
		t.Fatalf("new request failed: %v", err)
	}
	req.Header.Set(`X-Request-ID`, `trace-123`)
	noRedirectClient := &http.Client{
		CheckRedirect: func(req *http.Request, via []*http.Request) error {
			return http.ErrUseLastResponse
		},
	}
	resp, err := noRedirectClient.Do(req)
	if err != nil {
		t.Fatalf("request failed: %v", err)
	}
	defer func() { _ = resp.Body.Close() }()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		t.Fatalf("read body failed: %v", err)
	}
	_ = bodyBytes
	if resp.StatusCode != 200 {
		t.Fatalf("status: got %d want 200", resp.StatusCode)
	}
	if !strings.Contains(resp.Header.Get(`x-request-id`), `trace-123`) {
		t.Fatalf("header %s mismatch: got %q want to contain %q", `x-request-id`, resp.Header.Get(`x-request-id`), `trace-123`)
	}
	var got any
	var want any
	if err := json.Unmarshal(bodyBytes, &got); err != nil {
		t.Fatalf("json unmarshal got: %v", err)
	}
	if err := json.Unmarshal([]byte(`{"echo":"trace-123","status":"preserved"}`), &want); err != nil {
		t.Fatalf("json unmarshal want: %v", err)
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("body mismatch: got %v want %v", got, want)
	}
}

func Test_RequestIdIsGeneratedWhenNotProvided(t *testing.T) {
	// Ensures the request ID middleware attaches a UUID to responses when the client does not send one.
	baseURL := os.Getenv("SUT_URL")
	if baseURL == "" {
		baseURL = "http://127.0.0.1:8012"
	}
	body := strings.NewReader("")
	req, err := http.NewRequest("GET", baseURL+"/fixtures/request_id_is_generated_when_not_provided/request-id/generated", body)
	if err != nil {
		t.Fatalf("new request failed: %v", err)
	}
	noRedirectClient := &http.Client{
		CheckRedirect: func(req *http.Request, via []*http.Request) error {
			return http.ErrUseLastResponse
		},
	}
	resp, err := noRedirectClient.Do(req)
	if err != nil {
		t.Fatalf("request failed: %v", err)
	}
	defer func() { _ = resp.Body.Close() }()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		t.Fatalf("read body failed: %v", err)
	}
	_ = bodyBytes
	if resp.StatusCode != 200 {
		t.Fatalf("status: got %d want 200", resp.StatusCode)
	}
	if !strings.Contains(resp.Header.Get(`x-request-id`), `a4c20a2c-3b1f-4e2d-8b1d-3c9a1f2e4d5a`) {
		t.Fatalf("header %s mismatch: got %q want to contain %q", `x-request-id`, resp.Header.Get(`x-request-id`), `a4c20a2c-3b1f-4e2d-8b1d-3c9a1f2e4d5a`)
	}
	var got any
	var want any
	if err := json.Unmarshal(bodyBytes, &got); err != nil {
		t.Fatalf("json unmarshal got: %v", err)
	}
	if err := json.Unmarshal([]byte(`{"status":"generated"}`), &want); err != nil {
		t.Fatalf("json unmarshal want: %v", err)
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("body mismatch: got %v want %v", got, want)
	}
}

func Test_RequestIdMiddlewareCanBeDisabled(t *testing.T) {
	// When request ID generation is disabled the response should not contain X-Request-ID even if the client sends a header.
	baseURL := os.Getenv("SUT_URL")
	if baseURL == "" {
		baseURL = "http://127.0.0.1:8012"
	}
	body := strings.NewReader("")
	req, err := http.NewRequest("GET", baseURL+"/fixtures/request_id_middleware_can_be_disabled/request-id/disabled", body)
	if err != nil {
		t.Fatalf("new request failed: %v", err)
	}
	req.Header.Set(`X-Request-ID`, `external-id`)
	noRedirectClient := &http.Client{
		CheckRedirect: func(req *http.Request, via []*http.Request) error {
			return http.ErrUseLastResponse
		},
	}
	resp, err := noRedirectClient.Do(req)
	if err != nil {
		t.Fatalf("request failed: %v", err)
	}
	defer func() { _ = resp.Body.Close() }()
	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		t.Fatalf("read body failed: %v", err)
	}
	_ = bodyBytes
	if resp.StatusCode != 200 {
		t.Fatalf("status: got %d want 200", resp.StatusCode)
	}
	var got any
	var want any
	if err := json.Unmarshal(bodyBytes, &got); err != nil {
		t.Fatalf("json unmarshal got: %v", err)
	}
	if err := json.Unmarshal([]byte(`{"status":"no-request-id"}`), &want); err != nil {
		t.Fatalf("json unmarshal want: %v", err)
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("body mismatch: got %v want %v", got, want)
	}
}
