// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:70d6afb04d5fecb0ab2f4ebe104a87ee02bf617fd393e24a5daaaa0b5ba34da1
#nullable enable

using System;

namespace Spikard;

/// <summary>
/// Authorization error
///
/// Occurs when user lacks required permissions.
/// </summary>
public class AuthorizationErrorException : GraphQLErrorException
{
    public AuthorizationErrorException(string message) : base(message) { }

    public AuthorizationErrorException(string message, Exception innerException) : base(message, innerException) { }
}
