// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7af34a1d6da5f42d2667add5eb94cf3433a98632a55b7d515dcaa4331c41b3fb
#nullable enable

using System;

namespace Spikard;

/// <summary>
/// Generic schema building error
/// </summary>
public class BuildingFailedException : SchemaErrorException
{
    public BuildingFailedException(string message) : base(message) { }

    public BuildingFailedException(string message, Exception innerException) : base(message, innerException) { }
}
