// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:d21ff790be741044dee23524f8f57dacdfa9bbdc96f9a7562f0cc8f756725237
#nullable enable

using System;

namespace Spikard;

/// <summary>
/// Complexity limit exceeded
/// </summary>
public class ComplexityLimitExceededException : SchemaErrorException
{
    public ComplexityLimitExceededException(string message) : base(message) { }

    public ComplexityLimitExceededException(string message, Exception innerException) : base(message, innerException) { }
}
ion(string message, Exception innerException) : base(message, innerException) { }
}
