// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:25945609773117fe16dad951ff7c2b463ca36ee2f642a055611ceb789c46651b
#nullable enable

using System;

namespace Spikard;

/// <summary>
/// Query complexity limit exceeded
///
/// Occurs when a GraphQL query exceeds the configured complexity limit.
/// </summary>
public class ComplexityLimitExceededException : GraphQLErrorException
{
    public ComplexityLimitExceededException(string message) : base(message) { }

    public ComplexityLimitExceededException(string message, Exception innerException) : base(message, innerException) { }
}
