// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:522db12d796bdc8a9d0fa4c5e205a4f7487df4b3f987a58dd797200301c49d95
#nullable enable

using System;

namespace Spikard;

/// <summary>
/// Failed to extract DTO from the request context.
/// </summary>
public class DecodeException : AppErrorException
{
    public DecodeException(string message) : base(message) { }

    public DecodeException(string message, Exception innerException) : base(message, innerException) { }
}
