// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:fa06b403270e3c3da4cd204fb21e3c1a52cfd79563d9c34ce969edd497378eee
#nullable enable

using System;

namespace Spikard;

/// <summary>
/// Failed to extract DTO from the request context.
/// </summary>
public class DecodeException : AppErrorException
{
    public DecodeException(string message) : base(message) { }

    public DecodeException(string message, Exception innerException) : base(message, innerException) { }
}
