// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:5cda43db8f64def53c461be782227b0c2751e8ca01fcd213209ceb6324872e09
#nullable enable

using System;

namespace Spikard;

/// <summary>
/// Failed to extract DTO from the request context.
/// </summary>
public class DecodeException : AppErrorException
{
    public DecodeException(string message) : base(message) { }

    public DecodeException(string message, Exception innerException) : base(message, innerException) { }
}
