// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:4b3e466ea6f7bf68fe2b67b3aef8370b34caf7170416b2bf9063f6a5206333ca
#nullable enable

using System;

namespace Spikard;

/// <summary>
/// Query depth limit exceeded
///
/// Occurs when a GraphQL query exceeds the configured depth limit.
/// </summary>
public class DepthLimitExceededException : GraphQLErrorException
{
    public DepthLimitExceededException(string message) : base(message) { }

    public DepthLimitExceededException(string message, Exception innerException) : base(message, innerException) { }
}
