// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b8b369dfc79dfacd0d9771fbe3d352bdb78c32e5250af81afc44f0cbe8d283bc
#nullable enable

using System;

namespace Spikard;

/// <summary>
/// Query depth limit exceeded
///
/// Occurs when a GraphQL query exceeds the configured depth limit.
/// </summary>
public class DepthLimitExceededException : GraphQLErrorException
{
    public DepthLimitExceededException(string message) : base(message) { }

    public DepthLimitExceededException(string message, Exception innerException) : base(message, innerException) { }
}
