// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9d871803d888378d6bd6b4890d1e6940bd6dbc1b9356a2b17b755ee50eb71976
#nullable enable

using System;

namespace Spikard;

/// <summary>
/// Query depth limit exceeded
///
/// Occurs when a GraphQL query exceeds the configured depth limit.
/// </summary>
public class DepthLimitExceededException : GraphQLErrorException
{
    public DepthLimitExceededException(string message) : base(message) { }

    public DepthLimitExceededException(string message, Exception innerException) : base(message, innerException) { }
}
