// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:2d52f3f3ace4969b27d64f1c96278f5159bdcb297a4c8aea8492b6907ccc4327
#nullable enable

using System;
using Microsoft.Win32.SafeHandles;
using System.Runtime.InteropServices;

namespace Spikard;

internal sealed class HandlerResultSafeHandle : SafeHandle
{
    internal HandlerResultSafeHandle(IntPtr handle) : base(IntPtr.Zero, true)
    {
        SetHandle(handle);
    }

    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        NativeMethods.HandlerResultFree(handle);
        return true;
    }
}

public sealed class HandlerResult : IDisposable
{
    private readonly HandlerResultSafeHandle _safeHandle;

    internal HandlerResult(IntPtr handle)
    {
        _safeHandle = new HandlerResultSafeHandle(handle);
    }

    internal IntPtr Handle => _safeHandle.DangerousGetHandle();

    public void Dispose() => _safeHandle.Dispose();

}
