// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:73303505764dea065bbb66505f9931304c9ede70802389e3f5dea1de08253a4f
#nullable enable

using System;

namespace Spikard;

/// <summary>
/// Internal server error
///
/// Occurs when an unexpected internal error happens.
/// </summary>
public class InternalErrorException : GraphQLErrorException
{
    public InternalErrorException(string message) : base(message) { }

    public InternalErrorException(string message, Exception innerException) : base(message, innerException) { }
}
