// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:059d0b466bb3ce8ad08140b7e0721a1e0c0fed5ef09e12c835620d726544a19b
#nullable enable

using System;

namespace Spikard;

/// <summary>
/// Introspection query rejected because introspection is disabled
///
/// Occurs when a query selects `__schema` or `__type` while the schema was
/// configured with introspection disabled.
/// </summary>
public class IntrospectionDisabledException : GraphQLErrorException
{
    public IntrospectionDisabledException(string message) : base(message) { }

    public IntrospectionDisabledException(string message, Exception innerException) : base(message, innerException) { }
}
