// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:cc7e4a2a83ea67babc302fa0acfcffc108022a618f9cdb13c5812c591609b668
#nullable enable

using System;

namespace Spikard;

/// <summary>
/// Invalid input error with validation details
///
/// Occurs during input validation with detailed error information.
/// </summary>
public class InvalidInputException : GraphQLErrorException
{
    public InvalidInputException(string message) : base(message) { }

    public InvalidInputException(string message, Exception innerException) : base(message, innerException) { }
}
