// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c5701627144272d5a6d29dc50cfe1d6c754a1817b58235868c944b2f80a9ef52
#nullable enable

using System;

namespace Spikard;

/// <summary>
/// JSON parsing error
///
/// Occurs when JSON input cannot be parsed.
/// </summary>
public class JsonErrorException : GraphQLErrorException {
  public JsonErrorException(string message) : base(message) {}

  public JsonErrorException(string message, Exception innerException)
      : base(message, innerException) {}
}
