// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ad945baf4e9b1e14ce5dfec13f5ff80ebba31239f3d170fb1c15674547b888a0
#nullable enable

using System;

namespace Spikard;

/// <summary>
/// Not found error
///
/// Occurs when a requested resource is not found.
/// </summary>
public class NotFoundException : GraphQLErrorException
{
    public NotFoundException(string message) : base(message) { }

    public NotFoundException(string message, Exception innerException) : base(message, innerException) { }
}
