// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:f0cddb4006bbb6a98fd836b578d3d3189ce3a529ccd4eca224b64adddb062bb5
#nullable enable

using System;

namespace Spikard;

/// <summary>
/// Rate limit error
///
/// Occurs when rate limit is exceeded.
/// </summary>
public class RateLimitExceededException : GraphQLErrorException
{
    public RateLimitExceededException(string message) : base(message) { }

    public RateLimitExceededException(string message, Exception innerException) : base(message, innerException) { }
}
