// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0a4b0150f2c44891176004614268f0a6d22856951c8b6084bd18ab019587063e
#nullable enable

using System;

namespace Spikard;

/// <summary>
/// Error type for schema building operations
/// </summary>
public class SchemaErrorException : SpikardException
{
    public SchemaErrorException(string message) : base(message) { }

    public SchemaErrorException(string message, Exception innerException) : base(message, innerException) { }
}
