// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4d7c171c177dfe5cbdf2c0b1205cf2c28d98a9b35709bbe73674cd1718031454
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Spikard;

/// <summary>
/// Static file serving configuration
/// </summary>
public sealed record StaticFilesConfig
{
    /// <summary>
    /// Directory path to serve
    /// </summary>
    [JsonPropertyName("directory")]
    public required string Directory { get; init; }

    /// <summary>
    /// URL path prefix (e.g., "/static")
    /// </summary>
    [JsonPropertyName("route_prefix")]
    public required string RoutePrefix { get; init; }

    /// <summary>
    /// Fallback to index.html for directories
    /// </summary>
    [JsonPropertyName("index_file")]
    public bool IndexFile { get; init; } = false;

    /// <summary>
    /// Cache-Control header value
    /// </summary>
    [JsonPropertyName("cache_control")]
    public string? CacheControl { get; init; } = null;


    /// <summary>
    /// Parse a <see cref="StaticFilesConfig"/> from a JSON string.
    /// </summary>
    /// <exception cref="SpikardException">When the JSON cannot be deserialised.</exception>
    public static StaticFilesConfig FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<StaticFilesConfig>(json, JsonOptions)
                ?? throw new SpikardException($"Failed to parse StaticFilesConfig from JSON: deserializer returned null");
        }
        catch (SpikardException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new SpikardException($"Failed to parse StaticFilesConfig from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
