// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:d09a78f4a9bd131bc0158b123a7c58f95c84fb311186c45d9b8640a44534e2dc
#nullable enable

using System;

namespace Spikard;

/// <summary>
/// GraphQL validation error
///
/// Occurs when a GraphQL query fails schema validation.
/// </summary>
public class ValidationErrorException : GraphQLErrorException
{
    public ValidationErrorException(string message) : base(message) { }

    public ValidationErrorException(string message, Exception innerException) : base(message, innerException) { }
}
