// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9790a7b54ad6f37ea9cf211271d7bae038ef4a721802696074bfe89e546f5795
#nullable enable

using System;

namespace Spikard;

/// <summary>
/// GraphQL validation error
///
/// Occurs when a GraphQL query fails schema validation.
/// </summary>
public class ValidationErrorException : GraphQLErrorException
{
    public ValidationErrorException(string message) : base(message) { }

    public ValidationErrorException(string message, Exception innerException) : base(message, innerException) { }
}
