// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:fdad3957aca9c770729ae3f8a2bf85ea9b75453417e5d37b935eb57d7efa235d
#nullable enable

using System;

namespace Spikard;

/// <summary>
/// GraphQL validation error
///
/// Occurs when a GraphQL query fails schema validation.
/// </summary>
public class ValidationErrorException : GraphQLErrorException
{
    public ValidationErrorException(string message) : base(message) { }

    public ValidationErrorException(string message, Exception innerException) : base(message, innerException) { }
}
