// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:104e77ed6b7d55a4ca108230e21df7c46d0f2b76eb520d2b42b74ac456c11fd5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: graphql_operations

mod common;
mod mock_server;
#[allow(unused_imports)]
use mock_server::{MockRoute, MockServer};

#[tokio::test]
async fn test_graphql_field_level_error_partial_data() {
    // Tests that a field-level resolver error returns partial data alongside an errors array
    let expected_body =
        r#"{"data":{"status":"ok","user":null},"errors":[{"message":"User not found","path":["user"]}]}"#.to_string();
    let mut app = spikard::App::new();
    app.route(spikard::post("/graphql"), move |_ctx: spikard::RequestContext| {
        let body = expected_body.clone();
        async move {
            Ok(axum::http::Response::builder()
                .status(200u16)
                .header("content-type", "application/json")
                .body(axum::body::Body::from(body))
                .unwrap())
        }
    })
    .unwrap();
    let router = app.into_router().unwrap();
    let server = axum_test::TestServer::new(router);
    let response = server
        .post("/graphql")
        .add_header(r#"Content-Type"#, r#"application/json"#)
        .bytes(bytes::Bytes::copy_from_slice(
            r#"{"query":"{ user(id: \"missing-user\") { id name avatar } status }"}"#.as_bytes(),
        ))
        .await;
    assert_eq!(response.status_code().as_u16(), 200u16);
}

#[tokio::test]
async fn test_graphql_introspection_query() {
    // Tests that the __schema introspection query returns the schema type list
    let expected_body = r#"{"data":{"__schema":{"queryType":{"name":"Query"},"types":[{"kind":"OBJECT","name":"Query"},{"kind":"SCALAR","name":"String"},{"kind":"SCALAR","name":"Boolean"}]}}}"#.to_string();
    let mut app = spikard::App::new();
    app.route(spikard::post("/graphql"), move |_ctx: spikard::RequestContext| {
        let body = expected_body.clone();
        async move {
            Ok(axum::http::Response::builder()
                .status(200u16)
                .header("content-type", "application/json")
                .body(axum::body::Body::from(body))
                .unwrap())
        }
    })
    .unwrap();
    let router = app.into_router().unwrap();
    let server = axum_test::TestServer::new(router);
    let response = server
        .post("/graphql")
        .add_header(r#"Content-Type"#, r#"application/json"#)
        .bytes(bytes::Bytes::copy_from_slice(
            r#"{"query":"{ __schema { queryType { name } types { name kind } } }"}"#.as_bytes(),
        ))
        .await;
    assert_eq!(response.status_code().as_u16(), 200u16);
}

#[tokio::test]
async fn test_graphql_invalid_syntax_rejected() {
    // Tests that a query with invalid GraphQL syntax returns a syntax error in the errors array
    let expected_body = r#"{"errors":[{"locations":[{"column":10,"line":1}],"message":"Syntax Error"}]}"#.to_string();
    let mut app = spikard::App::new();
    app.route(spikard::post("/graphql"), move |_ctx: spikard::RequestContext| {
        let body = expected_body.clone();
        async move {
            Ok(axum::http::Response::builder()
                .status(200u16)
                .header("content-type", "application/json")
                .body(axum::body::Body::from(body))
                .unwrap())
        }
    })
    .unwrap();
    let router = app.into_router().unwrap();
    let server = axum_test::TestServer::new(router);
    let response = server
        .post("/graphql")
        .add_header(r#"Content-Type"#, r#"application/json"#)
        .bytes(bytes::Bytes::copy_from_slice(
            r#"{"query":"{ hello { this is not valid syntax {{{"}"#.as_bytes(),
        ))
        .await;
    assert_eq!(response.status_code().as_u16(), 200u16);
}

#[tokio::test]
async fn test_graphql_multi_operation_with_operation_name() {
    // Tests executing a specific named operation from a document containing multiple operations
    let expected_body = r#"{"data":{"version":"1.0.0"}}"#.to_string();
    let mut app = spikard::App::new();
    app.route(spikard::post("/graphql"), move |_ctx: spikard::RequestContext| {
        let body = expected_body.clone();
        async move {
            Ok(axum::http::Response::builder()
                .status(200u16)
                .header("content-type", "application/json")
                .body(axum::body::Body::from(body))
                .unwrap())
        }
    })
    .unwrap();
    let router = app.into_router().unwrap();
    let server = axum_test::TestServer::new(router);
    let response = server
        .post("/graphql")
        .add_header(r#"Content-Type"#, r#"application/json"#)
        .bytes(bytes::Bytes::copy_from_slice(
            r#"{"operationName":"Version","query":"query Ping { ping } query Version { version }"}"#.as_bytes(),
        ))
        .await;
    assert_eq!(response.status_code().as_u16(), 200u16);
}

#[tokio::test]
async fn test_graphql_mutation_create_object() {
    // Tests GraphQL mutation with an input type that returns the newly created object
    let expected_body =
        r#"{"data":{"createUser":{"email":"carol@example.com","id":"new-user-id","name":"Carol"}}}"#.to_string();
    let mut app = spikard::App::new();
    app.route(spikard::post("/graphql"), move |_ctx: spikard::RequestContext| {
        let body = expected_body.clone();
        async move {
            Ok(axum::http::Response::builder()
                .status(200u16)
                .header("content-type", "application/json")
                .body(axum::body::Body::from(body))
                .unwrap())
        }
    })
    .unwrap();
    let router = app.into_router().unwrap();
    let server = axum_test::TestServer::new(router);
    let response = server.post("/graphql")
        .add_header(r#"Content-Type"#, r#"application/json"#)
        .bytes(bytes::Bytes::copy_from_slice(r#"{"query":"mutation CreateUser($input: CreateUserInput!) { createUser(input: $input) { id name email } }","variables":{"input":{"email":"carol@example.com","name":"Carol"}}}"#.as_bytes()))
        .await;
    assert_eq!(response.status_code().as_u16(), 200u16);
}

#[tokio::test]
async fn test_graphql_ops_complexity_limit_exceeded() {
    // Tests that a query exceeding the configured complexity limit returns an error
    let expected_body =
        r#"{"errors":[{"message":"Query complexity exceeds maximum allowed complexity of 10"}]}"#.to_string();
    let mut app = spikard::App::new();
    app.route(spikard::post("/graphql"), move |_ctx: spikard::RequestContext| {
        let body = expected_body.clone();
        async move {
            Ok(axum::http::Response::builder()
                .status(200u16)
                .header("content-type", "application/json")
                .body(axum::body::Body::from(body))
                .unwrap())
        }
    })
    .unwrap();
    let router = app.into_router().unwrap();
    let server = axum_test::TestServer::new(router);
    let response = server
        .post("/graphql")
        .add_header(r#"Content-Type"#, r#"application/json"#)
        .bytes(bytes::Bytes::copy_from_slice(
            r#"{"query":"{ users { id friends { id friends { id friends { id friends { id } } } } } }"}"#.as_bytes(),
        ))
        .await;
    assert_eq!(response.status_code().as_u16(), 200u16);
}

#[tokio::test]
async fn test_graphql_ops_depth_limit_exceeded() {
    // Tests that a query exceeding the configured depth limit returns an error
    let expected_body = r#"{"errors":[{"message":"Query depth exceeds maximum allowed depth of 3"}]}"#.to_string();
    let mut app = spikard::App::new();
    app.route(spikard::post("/graphql"), move |_ctx: spikard::RequestContext| {
        let body = expected_body.clone();
        async move {
            Ok(axum::http::Response::builder()
                .status(200u16)
                .header("content-type", "application/json")
                .body(axum::body::Body::from(body))
                .unwrap())
        }
    })
    .unwrap();
    let router = app.into_router().unwrap();
    let server = axum_test::TestServer::new(router);
    let response = server
        .post("/graphql")
        .add_header(r#"Content-Type"#, r#"application/json"#)
        .bytes(bytes::Bytes::copy_from_slice(
            r#"{"query":"{ a { b { c { d { e } } } } }"}"#.as_bytes(),
        ))
        .await;
    assert_eq!(response.status_code().as_u16(), 200u16);
}

#[tokio::test]
async fn test_graphql_query_nested_fields() {
    // Tests GraphQL query selecting nested fields at depth 2-3
    let expected_body = r#"{"data":{"order":{"customer":{"address":{"city":"Springfield"},"name":"Bob"},"id":"ORD-1","items":[{"quantity":2,"sku":"WIDGET-A"}]}}}"#.to_string();
    let mut app = spikard::App::new();
    app.route(spikard::post("/graphql"), move |_ctx: spikard::RequestContext| {
        let body = expected_body.clone();
        async move {
            Ok(axum::http::Response::builder()
                .status(200u16)
                .header("content-type", "application/json")
                .body(axum::body::Body::from(body))
                .unwrap())
        }
    })
    .unwrap();
    let router = app.into_router().unwrap();
    let server = axum_test::TestServer::new(router);
    let response = server
        .post("/graphql")
        .add_header(r#"Content-Type"#, r#"application/json"#)
        .bytes(bytes::Bytes::copy_from_slice(
            r#"{"query":"{ order(id: \"ORD-1\") { id customer { name address { city } } items { sku quantity } } }"}"#
                .as_bytes(),
        ))
        .await;
    assert_eq!(response.status_code().as_u16(), 200u16);
}

#[tokio::test]
async fn test_graphql_query_with_variables() {
    // Tests GraphQL query that uses variables passed in the request body
    let expected_body = r#"{"data":{"user":{"id":"user-42","name":"Alice"}}}"#.to_string();
    let mut app = spikard::App::new();
    app.route(spikard::post("/graphql"), move |_ctx: spikard::RequestContext| {
        let body = expected_body.clone();
        async move {
            Ok(axum::http::Response::builder()
                .status(200u16)
                .header("content-type", "application/json")
                .body(axum::body::Body::from(body))
                .unwrap())
        }
    })
    .unwrap();
    let router = app.into_router().unwrap();
    let server = axum_test::TestServer::new(router);
    let response = server
        .post("/graphql")
        .add_header(r#"Content-Type"#, r#"application/json"#)
        .bytes(bytes::Bytes::copy_from_slice(
            r#"{"query":"query GetUser($id: ID!) { user(id: $id) { id name } }","variables":{"id":"user-42"}}"#
                .as_bytes(),
        ))
        .await;
    assert_eq!(response.status_code().as_u16(), 200u16);
}

#[tokio::test]
async fn test_graphql_simple_query() {
    // Tests simple GraphQL query execution returning data from the root query type
    let expected_body = r#"{"data":{"hello":"world"}}"#.to_string();
    let mut app = spikard::App::new();
    app.route(spikard::post("/graphql"), move |_ctx: spikard::RequestContext| {
        let body = expected_body.clone();
        async move {
            Ok(axum::http::Response::builder()
                .status(200u16)
                .header("content-type", "application/json")
                .body(axum::body::Body::from(body))
                .unwrap())
        }
    })
    .unwrap();
    let router = app.into_router().unwrap();
    let server = axum_test::TestServer::new(router);
    let response = server
        .post("/graphql")
        .add_header(r#"Content-Type"#, r#"application/json"#)
        .bytes(bytes::Bytes::copy_from_slice(r#"{"query":"{ hello }"}"#.as_bytes()))
        .await;
    assert_eq!(response.status_code().as_u16(), 200u16);
}

#[tokio::test]
async fn test_graphql_subscription_declaration() {
    // Tests that a subscription operation type is declared and the initial response shape matches
    let expected_body =
        r#"{"data":{"messageAdded":{"authorId":"user-1","id":"msg-1","text":"Hello room"}}}"#.to_string();
    let mut app = spikard::App::new();
    app.route(spikard::post("/graphql"), move |_ctx: spikard::RequestContext| {
        let body = expected_body.clone();
        async move {
            Ok(axum::http::Response::builder()
                .status(200u16)
                .header("content-type", "application/json")
                .body(axum::body::Body::from(body))
                .unwrap())
        }
    })
    .unwrap();
    let router = app.into_router().unwrap();
    let server = axum_test::TestServer::new(router);
    let response = server.post("/graphql")
        .add_header(r#"Content-Type"#, r#"application/json"#)
        .bytes(bytes::Bytes::copy_from_slice(r#"{"query":"subscription OnMessageAdded($roomId: ID!) { messageAdded(roomId: $roomId) { id text authorId } }","variables":{"roomId":"room-1"}}"#.as_bytes()))
        .await;
    assert_eq!(response.status_code().as_u16(), 200u16);
}

#[tokio::test]
async fn test_graphql_undefined_field_error() {
    // Tests that querying a field that does not exist in the schema returns a validation error
    let expected_body =
        r#"{"errors":[{"message":"Cannot query field \"nonExistentField\" on type \"Query\"."}]}"#.to_string();
    let mut app = spikard::App::new();
    app.route(spikard::post("/graphql"), move |_ctx: spikard::RequestContext| {
        let body = expected_body.clone();
        async move {
            Ok(axum::http::Response::builder()
                .status(200u16)
                .header("content-type", "application/json")
                .body(axum::body::Body::from(body))
                .unwrap())
        }
    })
    .unwrap();
    let router = app.into_router().unwrap();
    let server = axum_test::TestServer::new(router);
    let response = server
        .post("/graphql")
        .add_header(r#"Content-Type"#, r#"application/json"#)
        .bytes(bytes::Bytes::copy_from_slice(
            r#"{"query":"{ hello nonExistentField }"}"#.as_bytes(),
        ))
        .await;
    assert_eq!(response.status_code().as_u16(), 200u16);
}
