<?php
// This file is auto-generated by alef. DO NOT EDIT.

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Spikard\Php\SpikardPhp;
use GuzzleHttp\Client;

/** E2e tests for category: streaming. */
final class StreamingTest extends TestCase
{
    private Client $httpClient;

    protected function setUp(): void
    {
        parent::setUp();
        $baseUrl = getenv('TEST_SERVER_URL') ?: 'http://localhost:8080';
        $this->httpClient = new Client(['base_uri' => $baseUrl, 'http_errors' => false]);
    }

    /** Streams binary log segments with control bytes */
    public function test_binary_log_download(): void
    {
        $response = $this->httpClient->request('GET', "/stream/logfile");
        $body = json_decode((string) $response->getBody(), true, 512, JSON_THROW_ON_ERROR);
        $this->assertEquals(200, $response->getStatusCode());
        $this->assertEquals("LOG:\\u0000\\u0001\\u0002\\u0003|TAIL|\\u0007\\n", $body);
        $this->assertEquals("application/octet-stream", $response->getHeaderLine("content-type"));
    }

    /** Streams CSV header and rows as discrete chunks */
    public function test_chunked_csv_export(): void
    {
        $response = $this->httpClient->request('GET', "/stream/csv-report");
        $body = json_decode((string) $response->getBody(), true, 512, JSON_THROW_ON_ERROR);
        $this->assertEquals(200, $response->getStatusCode());
        $this->assertEquals("id,name,value\\n1,Alice,42\\n2,Bob,7\\n", $body);
        $this->assertEquals("text/csv", $response->getHeaderLine("content-type"));
    }

    /** Streams newline-delimited JSON payload in small chunks */
    public function test_stream_json_lines(): void
    {
        $response = $this->httpClient->request('GET', "/stream/json-lines");
        $body = json_decode((string) $response->getBody(), true, 512, JSON_THROW_ON_ERROR);
        $this->assertEquals(200, $response->getStatusCode());
        $this->assertEquals("{\"index\":0,\"payload\":\"alpha\"}\\n{\"index\":1,\"payload\":\"beta\"}\\n{\"index\":2,\"payload\":\"gamma\"}\\n", $body);
        $this->assertEquals("application/x-ndjson", $response->getHeaderLine("content-type"));
    }
}
