// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5ffea9fecd7cfa2374643bb3f9ec7758a6c680c9c456eb008dd25a73fd788f21
// To regenerate: alef e2e generate
// To verify freshness: alef verify

import { describe, expect, it } from "vitest";

async function _alefE2eDecompressAndParseJson(response: Response): Promise<unknown> {
  const contentEncoding = response.headers.get("content-encoding");
  let bytes = new Uint8Array(await response.arrayBuffer());

  // The runtime's own fetch (undici on Node, and the browser equivalent) decodes
  // `content-encoding` transparently and leaves the header in place, so by the time the
  // body reaches here it is usually already plain text. Decoding unconditionally on the
  // header alone therefore fails ("incorrect header check") against a server that really
  // did compress. Decode only when the payload still carries the encoding: gzip announces
  // itself with the 0x1f8b magic pair; brotli has no magic, so it is attempted and the
  // already-decoded case falls back to the bytes as received.
  if (contentEncoding === "gzip" && bytes.length >= 2 && bytes[0] === 0x1f && bytes[1] === 0x8b) {
    const { gunzipSync } = await import("zlib");
    bytes = new Uint8Array(gunzipSync(bytes));
  } else if (contentEncoding === "br") {
    const { brotliDecompressSync } = await import("zlib");
    try {
      bytes = new Uint8Array(brotliDecompressSync(bytes));
    } catch {
      // Already decoded by the runtime.
    }
  }

  const text = new TextDecoder().decode(bytes);
  return JSON.parse(text);
}

function _alefE2eText(value: unknown): string {
  return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
  if (item == null || typeof item !== "object") {
    return [_alefE2eText(item)];
  }
  const record = item as Record<string, unknown>;
  const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
  return [
    _alefE2eText(item),
    _alefE2eText(record.kind),
    _alefE2eText(record.name),
    _alefE2eText(record.source),
    _alefE2eText(record.alias),
    _alefE2eText(record.text),
    _alefE2eText(record.signature),
    itemsText,
  ];
}

function _alefE2eFormatMetadataDisplay(fm: unknown): string {
  if (fm == null) return "";
  if (typeof fm !== "object") return String(fm);
  const record = fm as Record<string, unknown>;
  const formatType = record.format_type;

  // FormatMetadata is internally tagged, so serde merges the variant payload's own fields as
  // siblings of the tag rather than nesting them: { format_type: 'image', format: 'PNG', ... }.
  // Read `format` off the record directly. Deliberately NO nested (`record.image`) fallback --
  // a binding that regresses to the pre-flatten shape must fail this assertion loudly instead
  // of silently degrading to the variant name below.
  if (formatType === "image" && typeof record.format === "string") {
    return record.format;
  }

  // Fallback: return format_type variant name
  if (typeof record.format_type === "string") return record.format_type;
  return "";
}

describe("body_limits", () => {
  it("body_over_limit_returns_413: Requests that exceed the configured max body size should be rejected with Payload Too Large.", async () => {
    const sutUrl = process.env.SUT_URL || "http://127.0.0.1:8001";
    const url = `${sutUrl}/fixtures/body_over_limit_returns_413/body-limit/over`;
    const response = await fetch(url, {
      method: "POST",
      redirect: "manual",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        note: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      }),
    });
    expect(response.status).toBe(413);
  });

  it("body_under_limit_succeeds: Ensures requests smaller than the configured body limit are accepted.", async () => {
    const sutUrl = process.env.SUT_URL || "http://127.0.0.1:8001";
    const url = `${sutUrl}/fixtures/body_under_limit_succeeds/body-limit/under`;
    const response = await fetch(url, {
      method: "POST",
      redirect: "manual",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ note: "small" }),
    });
    expect(response.status).toBe(200);
    const data = await _alefE2eDecompressAndParseJson(response);
    expect(data).toEqual({
      accepted: true,
      note: "small",
    });
  });
});
