// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f5e9f5cfd86677c929357a5eb467102b47d5798527a24c03b9b36eb018283c95
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
    testTimeout: 30000,
    hookTimeout: 120000,
    teardownTimeout: 30000,
  },
});
