// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7f82b4aa5872fb93ca2202882dd9b4bb653b852da7a7dbf5ea7954b684d7ea89
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.spikard.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module

/** E2e tests for category: background. */
class BackgroundTest {

    companion object {
        private val MAPPER = ObjectMapper().registerModule(Jdk8Module()).setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
    }
    @Test
    fun testBackgroundEventLogging() {
        // Enqueues a background job that appends the posted event to shared state
        val baseUrl = System.getenv("SUT_URL") ?: "http://127.0.0.1:8007"
        val uri = java.net.URI.create("$baseUrl/fixtures/background_event_logging/background/events")
        val builder = java.net.http.HttpRequest.newBuilder(uri)
            .method("POST", java.net.http.HttpRequest.BodyPublishers.ofString("{\"event\":\"alpha\"}"))
            .header("Content-Type", "application/json")
        val response = java.net.http.HttpClient.newHttpClient()
            .send(builder.build(), java.net.http.HttpResponse.BodyHandlers.ofString())
        assertEquals(202, response.statusCode(), "status code mismatch")
        assertTrue(response.headers().firstValue("content-type").orElse("").contains("application/json"), "header content-type mismatch")
    }

    @Test
    fun testBackgroundEventLoggingSecondPayload() {
        // Ensures background jobs handle different payloads
        val baseUrl = System.getenv("SUT_URL") ?: "http://127.0.0.1:8007"
        val uri = java.net.URI.create("$baseUrl/fixtures/background_event_logging_second_payload/background/events")
        val builder = java.net.http.HttpRequest.newBuilder(uri)
            .method("POST", java.net.http.HttpRequest.BodyPublishers.ofString("{\"event\":\"beta\"}"))
            .header("Content-Type", "application/json")
        val response = java.net.http.HttpClient.newHttpClient()
            .send(builder.build(), java.net.http.HttpResponse.BodyHandlers.ofString())
        assertEquals(202, response.statusCode(), "status code mismatch")
        assertTrue(response.headers().firstValue("content-type").orElse("").contains("application/json"), "header content-type mismatch")
    }

}
