// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c0b782539044cb3f74e0647773236b0d328109519f9d857913856874135e80b5
// Re-generate with: alef generate
#![allow(dead_code, unused_imports, unused_variables)]
#![allow(
    clippy::too_many_arguments,
    clippy::let_unit_value,
    clippy::needless_borrow,
    clippy::map_identity,
    clippy::just_underscores_and_digits,
    clippy::unused_unit,
    clippy::unnecessary_cast,
    clippy::unwrap_or_default,
    clippy::derivable_impls,
    clippy::needless_borrows_for_generic_args,
    clippy::unnecessary_fallible_conversions,
    clippy::useless_conversion,
    clippy::arc_with_non_send_sync,
    clippy::collapsible_if,
    clippy::clone_on_copy,
    clippy::should_implement_trait
)]

use wasm_bindgen::prelude::*;

pub mod dispatch;

pub use dispatch::*;

/// CORS configuration for a route
#[derive(Clone, Default)]
#[wasm_bindgen]
pub struct WasmCorsConfig {
    allowed_origins: Vec<String>,
    allowed_methods: Vec<String>,
    allowed_headers: Vec<String>,
    expose_headers: Option<Vec<String>>,
    max_age: Option<u32>,
    allow_credentials: Option<bool>,
}

#[wasm_bindgen]
impl WasmCorsConfig {
    #[allow(non_snake_case)]
    #[wasm_bindgen(constructor)]
    pub fn new(
        allowedOrigins: Option<Vec<String>>,
        allowedMethods: Option<Vec<String>>,
        allowedHeaders: Option<Vec<String>>,
        exposeHeaders: Option<Vec<String>>,
        maxAge: Option<u32>,
        allowCredentials: Option<bool>,
    ) -> WasmCorsConfig {
        WasmCorsConfig {
            allowed_origins: allowedOrigins.unwrap_or_default(),
            allowed_methods: allowedMethods.unwrap_or_default(),
            allowed_headers: allowedHeaders.unwrap_or_default(),
            expose_headers: exposeHeaders,
            max_age: maxAge,
            allow_credentials: allowCredentials,
        }
    }

    #[wasm_bindgen(getter, js_name = "allowedOrigins")]
    pub fn allowed_origins(&self) -> Vec<String> {
        self.allowed_origins.clone()
    }

    #[wasm_bindgen(setter, js_name = "allowedOrigins")]
    pub fn set_allowed_origins(&mut self, value: Vec<String>) {
        self.allowed_origins = value;
    }

    #[wasm_bindgen(getter, js_name = "allowedMethods")]
    pub fn allowed_methods(&self) -> Vec<String> {
        self.allowed_methods.clone()
    }

    #[wasm_bindgen(setter, js_name = "allowedMethods")]
    pub fn set_allowed_methods(&mut self, value: Vec<String>) {
        self.allowed_methods = value;
    }

    #[wasm_bindgen(getter, js_name = "allowedHeaders")]
    pub fn allowed_headers(&self) -> Vec<String> {
        self.allowed_headers.clone()
    }

    #[wasm_bindgen(setter, js_name = "allowedHeaders")]
    pub fn set_allowed_headers(&mut self, value: Vec<String>) {
        self.allowed_headers = value;
    }

    #[wasm_bindgen(getter, js_name = "exposeHeaders")]
    pub fn expose_headers(&self) -> Option<Vec<String>> {
        self.expose_headers.clone()
    }

    #[wasm_bindgen(setter, js_name = "exposeHeaders")]
    pub fn set_expose_headers(&mut self, value: Option<Vec<String>>) {
        self.expose_headers = value;
    }

    #[wasm_bindgen(getter, js_name = "maxAge")]
    pub fn max_age(&self) -> Option<u32> {
        self.max_age
    }

    #[wasm_bindgen(setter, js_name = "maxAge")]
    pub fn set_max_age(&mut self, value: Option<u32>) {
        self.max_age = value;
    }

    #[wasm_bindgen(getter, js_name = "allowCredentials")]
    pub fn allow_credentials(&self) -> Option<bool> {
        self.allow_credentials
    }

    #[wasm_bindgen(setter, js_name = "allowCredentials")]
    pub fn set_allow_credentials(&mut self, value: Option<bool>) {
        self.allow_credentials = value;
    }

    /// Get the cached joined methods string for preflight responses
    #[wasm_bindgen(js_name = "allowedMethodsJoined")]
    pub fn allowed_methods_joined(&self) -> String {
        spikard_http::CorsConfig::from(self.clone())
            .allowed_methods_joined()
            .into()
    }

    /// Get the cached joined headers string for preflight responses
    #[wasm_bindgen(js_name = "allowedHeadersJoined")]
    pub fn allowed_headers_joined(&self) -> String {
        spikard_http::CorsConfig::from(self.clone())
            .allowed_headers_joined()
            .into()
    }

    /// Check if an origin is allowed (O(1) with wildcard, O(n) for exact match)
    #[wasm_bindgen(js_name = "isOriginAllowed")]
    pub fn is_origin_allowed(&self, origin: String) -> bool {
        spikard_http::CorsConfig::from(self.clone()).is_origin_allowed(&origin)
    }

    /// Check if a method is allowed (O(1) with wildcard, O(n) for exact match)
    #[wasm_bindgen(js_name = "isMethodAllowed")]
    pub fn is_method_allowed(&self, method: String) -> bool {
        spikard_http::CorsConfig::from(self.clone()).is_method_allowed(&method)
    }

    /// Check if all requested headers are allowed (O(n) where n = num requested headers)
    #[wasm_bindgen(js_name = "areHeadersAllowed")]
    pub fn are_headers_allowed(&self, _requested: Vec<String>) -> bool {
        false
    }

    #[allow(clippy::should_implement_trait)]
    #[wasm_bindgen]
    pub fn default() -> WasmCorsConfig {
        spikard_http::CorsConfig::default().into()
    }
}

/// Compression configuration shared across runtimes
#[derive(Clone, Default)]
#[wasm_bindgen]
pub struct WasmCompressionConfig {
    gzip: bool,
    brotli: bool,
    min_size: usize,
    quality: u32,
}

#[wasm_bindgen]
impl WasmCompressionConfig {
    #[allow(non_snake_case)]
    #[wasm_bindgen(constructor)]
    pub fn new(
        gzip: Option<bool>,
        brotli: Option<bool>,
        minSize: Option<usize>,
        quality: Option<u32>,
    ) -> WasmCompressionConfig {
        WasmCompressionConfig {
            gzip: gzip.unwrap_or(true),
            brotli: brotli.unwrap_or(true),
            min_size: minSize.unwrap_or_default(),
            quality: quality.unwrap_or_default(),
        }
    }

    #[wasm_bindgen(getter)]
    pub fn gzip(&self) -> bool {
        self.gzip
    }

    #[wasm_bindgen(setter)]
    pub fn set_gzip(&mut self, value: bool) {
        self.gzip = value;
    }

    #[wasm_bindgen(getter)]
    pub fn brotli(&self) -> bool {
        self.brotli
    }

    #[wasm_bindgen(setter)]
    pub fn set_brotli(&mut self, value: bool) {
        self.brotli = value;
    }

    #[wasm_bindgen(getter, js_name = "minSize")]
    pub fn min_size(&self) -> usize {
        self.min_size
    }

    #[wasm_bindgen(setter, js_name = "minSize")]
    pub fn set_min_size(&mut self, value: usize) {
        self.min_size = value;
    }

    #[wasm_bindgen(getter)]
    pub fn quality(&self) -> u32 {
        self.quality
    }

    #[wasm_bindgen(setter)]
    pub fn set_quality(&mut self, value: u32) {
        self.quality = value;
    }

    #[allow(clippy::should_implement_trait)]
    #[wasm_bindgen]
    pub fn default() -> WasmCompressionConfig {
        spikard_http::CompressionConfig::default().into()
    }
}

/// Rate limiting configuration shared across runtimes
#[derive(Clone, Default)]
#[wasm_bindgen]
pub struct WasmRateLimitConfig {
    per_second: u64,
    burst: u32,
    ip_based: bool,
}

#[wasm_bindgen]
impl WasmRateLimitConfig {
    #[allow(non_snake_case)]
    #[wasm_bindgen(constructor)]
    pub fn new(perSecond: Option<u64>, burst: Option<u32>, ipBased: Option<bool>) -> WasmRateLimitConfig {
        WasmRateLimitConfig {
            per_second: perSecond.unwrap_or(100),
            burst: burst.unwrap_or(200),
            ip_based: ipBased.unwrap_or(true),
        }
    }

    #[wasm_bindgen(getter, js_name = "perSecond")]
    pub fn per_second(&self) -> u64 {
        self.per_second
    }

    #[wasm_bindgen(setter, js_name = "perSecond")]
    pub fn set_per_second(&mut self, value: u64) {
        self.per_second = value;
    }

    #[wasm_bindgen(getter)]
    pub fn burst(&self) -> u32 {
        self.burst
    }

    #[wasm_bindgen(setter)]
    pub fn set_burst(&mut self, value: u32) {
        self.burst = value;
    }

    #[wasm_bindgen(getter, js_name = "ipBased")]
    pub fn ip_based(&self) -> bool {
        self.ip_based
    }

    #[wasm_bindgen(setter, js_name = "ipBased")]
    pub fn set_ip_based(&mut self, value: bool) {
        self.ip_based = value;
    }

    #[allow(clippy::should_implement_trait)]
    #[wasm_bindgen]
    pub fn default() -> WasmRateLimitConfig {
        spikard_http::RateLimitConfig::default().into()
    }
}

/// JSON-RPC method metadata for routes that support JSON-RPC
///
/// This struct captures the metadata needed to expose HTTP routes as JSON-RPC methods,
/// enabling discovery and documentation of RPC-compatible endpoints.
///
/// # Examples
#[derive(Clone, Default)]
#[wasm_bindgen]
pub struct WasmJsonRpcMethodInfo {
    method_name: String,
    description: Option<String>,
    params_schema: Option<JsValue>,
    result_schema: Option<JsValue>,
    deprecated: bool,
    tags: Vec<String>,
}

#[wasm_bindgen]
impl WasmJsonRpcMethodInfo {
    #[allow(non_snake_case)]
    #[wasm_bindgen(constructor)]
    pub fn new(
        methodName: String,
        deprecated: bool,
        tags: Vec<String>,
        description: Option<String>,
        paramsSchema: Option<JsValue>,
        resultSchema: Option<JsValue>,
    ) -> WasmJsonRpcMethodInfo {
        WasmJsonRpcMethodInfo {
            method_name: methodName,
            description,
            params_schema: paramsSchema,
            result_schema: resultSchema,
            deprecated,
            tags,
        }
    }

    #[wasm_bindgen]
    #[allow(clippy::should_implement_trait)]
    pub fn default() -> WasmJsonRpcMethodInfo {
        <WasmJsonRpcMethodInfo as ::core::default::Default>::default()
    }

    #[wasm_bindgen(getter, js_name = "methodName")]
    pub fn method_name(&self) -> String {
        self.method_name.clone()
    }

    #[wasm_bindgen(setter, js_name = "methodName")]
    pub fn set_method_name(&mut self, value: String) {
        self.method_name = value;
    }

    #[wasm_bindgen(getter)]
    pub fn description(&self) -> Option<String> {
        self.description.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_description(&mut self, value: Option<String>) {
        self.description = value;
    }

    #[wasm_bindgen(getter, js_name = "paramsSchema")]
    pub fn params_schema(&self) -> Option<JsValue> {
        self.params_schema.clone()
    }

    #[wasm_bindgen(setter, js_name = "paramsSchema")]
    pub fn set_params_schema(&mut self, value: Option<JsValue>) {
        self.params_schema = value;
    }

    #[wasm_bindgen(getter, js_name = "resultSchema")]
    pub fn result_schema(&self) -> Option<JsValue> {
        self.result_schema.clone()
    }

    #[wasm_bindgen(setter, js_name = "resultSchema")]
    pub fn set_result_schema(&mut self, value: Option<JsValue>) {
        self.result_schema = value;
    }

    #[wasm_bindgen(getter)]
    pub fn deprecated(&self) -> bool {
        self.deprecated
    }

    #[wasm_bindgen(setter)]
    pub fn set_deprecated(&mut self, value: bool) {
        self.deprecated = value;
    }

    #[wasm_bindgen(getter)]
    pub fn tags(&self) -> Vec<String> {
        self.tags.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_tags(&mut self, value: Vec<String>) {
        self.tags = value;
    }
}

/// RFC 9457 Problem Details for HTTP APIs
///
/// A machine-readable format for specifying errors in HTTP API responses.
/// Per RFC 9457, all fields are optional. The `type` field defaults to "about:blank"
/// if not specified.
///
/// # Content-Type
/// Responses using this struct should set:
/// ```text
/// Content-Type: application/problem+json
/// ```
///
/// ```json
/// {
///   "type": "https://spikard.dev/errors/validation-error",
///   "title": "Request Validation Failed",
///   "status": 422,
///   "detail": "2 validation errors in request body",
///   "errors": [...]
/// }
/// ```
#[derive(Clone, Default)]
#[wasm_bindgen]
pub struct WasmProblemDetails {
    type_uri: String,
    title: String,
    status: u16,
    detail: Option<String>,
    instance: Option<String>,
    extensions: JsValue,
}

#[wasm_bindgen]
impl WasmProblemDetails {
    #[allow(non_snake_case)]
    #[wasm_bindgen(constructor)]
    pub fn new(
        typeUri: String,
        title: String,
        status: u16,
        extensions: JsValue,
        detail: Option<String>,
        instance: Option<String>,
    ) -> WasmProblemDetails {
        WasmProblemDetails {
            type_uri: typeUri,
            title,
            status,
            detail,
            instance,
            extensions,
        }
    }

    #[wasm_bindgen]
    #[allow(clippy::should_implement_trait)]
    pub fn default() -> WasmProblemDetails {
        <WasmProblemDetails as ::core::default::Default>::default()
    }

    #[wasm_bindgen(getter, js_name = "typeUri")]
    pub fn type_uri(&self) -> String {
        self.type_uri.clone()
    }

    #[wasm_bindgen(setter, js_name = "typeUri")]
    pub fn set_type_uri(&mut self, value: String) {
        self.type_uri = value;
    }

    #[wasm_bindgen(getter)]
    pub fn title(&self) -> String {
        self.title.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_title(&mut self, value: String) {
        self.title = value;
    }

    #[wasm_bindgen(getter)]
    pub fn status(&self) -> u16 {
        self.status
    }

    #[wasm_bindgen(setter)]
    pub fn set_status(&mut self, value: u16) {
        self.status = value;
    }

    #[wasm_bindgen(getter)]
    pub fn detail(&self) -> Option<String> {
        self.detail.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_detail(&mut self, value: Option<String>) {
        self.detail = value;
    }

    #[wasm_bindgen(getter)]
    pub fn instance(&self) -> Option<String> {
        self.instance.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_instance(&mut self, value: Option<String>) {
        self.instance = value;
    }

    #[wasm_bindgen(getter)]
    pub fn extensions(&self) -> JsValue {
        self.extensions.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_extensions(&mut self, value: JsValue) {
        self.extensions = value;
    }

    /// Set the detail field
    #[wasm_bindgen(js_name = "withDetail")]
    pub fn with_detail(&self, detail: String) -> WasmProblemDetails {
        spikard_http::ProblemDetails::from(self.clone())
            .with_detail(detail)
            .into()
    }

    /// Set the instance field
    #[wasm_bindgen(js_name = "withInstance")]
    pub fn with_instance(&self, instance: String) -> WasmProblemDetails {
        spikard_http::ProblemDetails::from(self.clone())
            .with_instance(instance)
            .into()
    }

    /// Create a not found error
    #[wasm_bindgen(js_name = "notFound")]
    pub fn not_found(detail: String) -> WasmProblemDetails {
        spikard_http::ProblemDetails::not_found(detail).into()
    }

    /// Create a method not allowed error
    #[wasm_bindgen(js_name = "methodNotAllowed")]
    pub fn method_not_allowed(detail: String) -> WasmProblemDetails {
        spikard_http::ProblemDetails::method_not_allowed(detail).into()
    }

    /// Create an internal server error
    #[wasm_bindgen(js_name = "internalServerError")]
    pub fn internal_server_error(detail: String) -> WasmProblemDetails {
        spikard_http::ProblemDetails::internal_server_error(detail).into()
    }

    /// Create a bad request error
    #[wasm_bindgen(js_name = "badRequest")]
    pub fn bad_request(detail: String) -> WasmProblemDetails {
        spikard_http::ProblemDetails::bad_request(detail).into()
    }

    /// Serialize to JSON string
    ///
    /// # Errors
    /// Returns an error if the serialization fails.
    #[allow(clippy::missing_errors_doc)]
    #[wasm_bindgen(js_name = "toJson")]
    pub fn to_json(&self) -> Result<String, JsValue> {
        let result = spikard_http::ProblemDetails::from(self.clone())
            .to_json()
            .map_err(|e| JsValue::from_str(&e.to_string()))?;
        Ok(result)
    }

    /// Serialize to pretty JSON string
    ///
    /// # Errors
    /// Returns an error if the serialization fails.
    #[allow(clippy::missing_errors_doc)]
    #[wasm_bindgen(js_name = "toJsonPretty")]
    pub fn to_json_pretty(&self) -> Result<String, JsValue> {
        let result = spikard_http::ProblemDetails::from(self.clone())
            .to_json_pretty()
            .map_err(|e| JsValue::from_str(&e.to_string()))?;
        Ok(result)
    }
}

/// AsyncAPI HTTP endpoint configuration
#[derive(Clone, Default)]
#[wasm_bindgen]
pub struct WasmAsyncApiConfig {
    enabled: bool,
    spec: Option<JsValue>,
}

#[wasm_bindgen]
impl WasmAsyncApiConfig {
    #[allow(non_snake_case)]
    #[wasm_bindgen(constructor)]
    pub fn new(enabled: Option<bool>, spec: Option<JsValue>) -> WasmAsyncApiConfig {
        WasmAsyncApiConfig {
            enabled: enabled.unwrap_or_default(),
            spec,
        }
    }

    #[wasm_bindgen]
    #[allow(clippy::should_implement_trait)]
    pub fn default() -> WasmAsyncApiConfig {
        <WasmAsyncApiConfig as ::core::default::Default>::default()
    }

    #[wasm_bindgen(getter)]
    pub fn enabled(&self) -> bool {
        self.enabled
    }

    #[wasm_bindgen(setter)]
    pub fn set_enabled(&mut self, value: bool) {
        self.enabled = value;
    }

    #[wasm_bindgen(getter)]
    pub fn spec(&self) -> Option<JsValue> {
        self.spec.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_spec(&mut self, value: Option<JsValue>) {
        self.spec = value;
    }
}

/// A single channel extracted from an AsyncAPI spec
#[derive(Clone, Default)]
#[wasm_bindgen]
pub struct WasmParsedChannel {
    name: String,
    address: String,
    messages: Vec<String>,
    bindings: Option<JsValue>,
}

#[wasm_bindgen]
impl WasmParsedChannel {
    #[allow(non_snake_case)]
    #[wasm_bindgen(constructor)]
    pub fn new(name: String, address: String, messages: Vec<String>, bindings: Option<JsValue>) -> WasmParsedChannel {
        WasmParsedChannel {
            name,
            address,
            messages,
            bindings,
        }
    }

    #[wasm_bindgen]
    #[allow(clippy::should_implement_trait)]
    pub fn default() -> WasmParsedChannel {
        <WasmParsedChannel as ::core::default::Default>::default()
    }

    #[wasm_bindgen(getter)]
    pub fn name(&self) -> String {
        self.name.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_name(&mut self, value: String) {
        self.name = value;
    }

    #[wasm_bindgen(getter)]
    pub fn address(&self) -> String {
        self.address.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_address(&mut self, value: String) {
        self.address = value;
    }

    #[wasm_bindgen(getter)]
    pub fn messages(&self) -> Vec<String> {
        self.messages.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_messages(&mut self, value: Vec<String>) {
        self.messages = value;
    }

    #[wasm_bindgen(getter)]
    pub fn bindings(&self) -> Option<JsValue> {
        self.bindings.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_bindings(&mut self, value: Option<JsValue>) {
        self.bindings = value;
    }
}

/// A single operation extracted from an AsyncAPI spec
#[derive(Clone, Default)]
#[wasm_bindgen]
pub struct WasmParsedOperation {
    name: String,
    action: String,
    channel: String,
}

#[wasm_bindgen]
impl WasmParsedOperation {
    #[allow(non_snake_case)]
    #[wasm_bindgen(constructor)]
    pub fn new(name: String, action: String, channel: String) -> WasmParsedOperation {
        WasmParsedOperation { name, action, channel }
    }

    #[wasm_bindgen]
    #[allow(clippy::should_implement_trait)]
    pub fn default() -> WasmParsedOperation {
        <WasmParsedOperation as ::core::default::Default>::default()
    }

    #[wasm_bindgen(getter)]
    pub fn name(&self) -> String {
        self.name.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_name(&mut self, value: String) {
        self.name = value;
    }

    #[wasm_bindgen(getter)]
    pub fn action(&self) -> String {
        self.action.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_action(&mut self, value: String) {
        self.action = value;
    }

    #[wasm_bindgen(getter)]
    pub fn channel(&self) -> String {
        self.channel.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_channel(&mut self, value: String) {
        self.channel = value;
    }
}

/// A resolved message (name + JSON Schema)
#[derive(Clone, Default)]
#[wasm_bindgen]
pub struct WasmParsedMessage {
    name: String,
    schema: Option<JsValue>,
}

#[wasm_bindgen]
impl WasmParsedMessage {
    #[allow(non_snake_case)]
    #[wasm_bindgen(constructor)]
    pub fn new(name: String, schema: Option<JsValue>) -> WasmParsedMessage {
        WasmParsedMessage { name, schema }
    }

    #[wasm_bindgen]
    #[allow(clippy::should_implement_trait)]
    pub fn default() -> WasmParsedMessage {
        <WasmParsedMessage as ::core::default::Default>::default()
    }

    #[wasm_bindgen(getter)]
    pub fn name(&self) -> String {
        self.name.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_name(&mut self, value: String) {
        self.name = value;
    }

    #[wasm_bindgen(getter)]
    pub fn schema(&self) -> Option<JsValue> {
        self.schema.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_schema(&mut self, value: Option<JsValue>) {
        self.schema = value;
    }
}

/// Full parse result returned by `POST /asyncapi/parse`
#[derive(Clone, Default)]
#[wasm_bindgen]
pub struct WasmParseResult {
    spec_version: String,
    title: String,
    api_version: String,
    channels: Vec<WasmParsedChannel>,
    operations: Vec<WasmParsedOperation>,
    messages: Vec<WasmParsedMessage>,
}

#[wasm_bindgen]
impl WasmParseResult {
    #[allow(non_snake_case)]
    #[wasm_bindgen(constructor)]
    pub fn new(
        specVersion: String,
        title: String,
        apiVersion: String,
        channels: Vec<WasmParsedChannel>,
        operations: Vec<WasmParsedOperation>,
        messages: Vec<WasmParsedMessage>,
    ) -> WasmParseResult {
        WasmParseResult {
            spec_version: specVersion,
            title,
            api_version: apiVersion,
            channels,
            operations,
            messages,
        }
    }

    #[wasm_bindgen]
    #[allow(clippy::should_implement_trait)]
    pub fn default() -> WasmParseResult {
        <WasmParseResult as ::core::default::Default>::default()
    }

    #[wasm_bindgen(getter, js_name = "specVersion")]
    pub fn spec_version(&self) -> String {
        self.spec_version.clone()
    }

    #[wasm_bindgen(setter, js_name = "specVersion")]
    pub fn set_spec_version(&mut self, value: String) {
        self.spec_version = value;
    }

    #[wasm_bindgen(getter)]
    pub fn title(&self) -> String {
        self.title.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_title(&mut self, value: String) {
        self.title = value;
    }

    #[wasm_bindgen(getter, js_name = "apiVersion")]
    pub fn api_version(&self) -> String {
        self.api_version.clone()
    }

    #[wasm_bindgen(setter, js_name = "apiVersion")]
    pub fn set_api_version(&mut self, value: String) {
        self.api_version = value;
    }

    #[wasm_bindgen(getter)]
    pub fn channels(&self) -> Vec<WasmParsedChannel> {
        self.channels.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_channels(&mut self, value: Vec<WasmParsedChannel>) {
        self.channels = value;
    }

    #[wasm_bindgen(getter)]
    pub fn operations(&self) -> Vec<WasmParsedOperation> {
        self.operations.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_operations(&mut self, value: Vec<WasmParsedOperation>) {
        self.operations = value;
    }

    #[wasm_bindgen(getter)]
    pub fn messages(&self) -> Vec<WasmParsedMessage> {
        self.messages.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_messages(&mut self, value: Vec<WasmParsedMessage>) {
        self.messages = value;
    }
}

/// Request body for `POST /asyncapi/parse`
#[derive(Clone, Default)]
#[wasm_bindgen]
pub struct WasmParseRequest {
    spec: JsValue,
}

#[wasm_bindgen]
impl WasmParseRequest {
    #[allow(non_snake_case)]
    #[wasm_bindgen(constructor)]
    pub fn new(spec: JsValue) -> WasmParseRequest {
        WasmParseRequest { spec }
    }

    #[wasm_bindgen]
    #[allow(clippy::should_implement_trait)]
    pub fn default() -> WasmParseRequest {
        <WasmParseRequest as ::core::default::Default>::default()
    }

    #[wasm_bindgen(getter)]
    pub fn spec(&self) -> JsValue {
        self.spec.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_spec(&mut self, value: JsValue) {
        self.spec = value;
    }
}

/// Response body for `POST /asyncapi/validate`
#[derive(Clone, Default)]
#[wasm_bindgen]
pub struct WasmValidationResponse {
    valid: bool,
    errors: Vec<String>,
}

#[wasm_bindgen]
impl WasmValidationResponse {
    #[allow(non_snake_case)]
    #[wasm_bindgen(constructor)]
    pub fn new(valid: bool, errors: Vec<String>) -> WasmValidationResponse {
        WasmValidationResponse { valid, errors }
    }

    #[wasm_bindgen]
    #[allow(clippy::should_implement_trait)]
    pub fn default() -> WasmValidationResponse {
        <WasmValidationResponse as ::core::default::Default>::default()
    }

    #[wasm_bindgen(getter)]
    pub fn valid(&self) -> bool {
        self.valid
    }

    #[wasm_bindgen(setter)]
    pub fn set_valid(&mut self, value: bool) {
        self.valid = value;
    }

    #[wasm_bindgen(getter)]
    pub fn errors(&self) -> Vec<String> {
        self.errors.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_errors(&mut self, value: Vec<String>) {
        self.errors = value;
    }
}

/// Request body for `POST /asyncapi/validate`
#[derive(Clone, Default)]
#[wasm_bindgen]
pub struct WasmValidateRequest {
    spec: JsValue,
    channel: String,
    message: String,
    payload: JsValue,
}

#[wasm_bindgen]
impl WasmValidateRequest {
    #[allow(non_snake_case)]
    #[wasm_bindgen(constructor)]
    pub fn new(spec: JsValue, channel: String, message: String, payload: JsValue) -> WasmValidateRequest {
        WasmValidateRequest {
            spec,
            channel,
            message,
            payload,
        }
    }

    #[wasm_bindgen]
    #[allow(clippy::should_implement_trait)]
    pub fn default() -> WasmValidateRequest {
        <WasmValidateRequest as ::core::default::Default>::default()
    }

    #[wasm_bindgen(getter)]
    pub fn spec(&self) -> JsValue {
        self.spec.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_spec(&mut self, value: JsValue) {
        self.spec = value;
    }

    #[wasm_bindgen(getter)]
    pub fn channel(&self) -> String {
        self.channel.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_channel(&mut self, value: String) {
        self.channel = value;
    }

    #[wasm_bindgen(getter)]
    pub fn message(&self) -> String {
        self.message.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_message(&mut self, value: String) {
        self.message = value;
    }

    #[wasm_bindgen(getter)]
    pub fn payload(&self) -> JsValue {
        self.payload.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_payload(&mut self, value: JsValue) {
        self.payload = value;
    }
}

/// JSON-RPC server configuration
#[derive(Clone, Default)]
#[wasm_bindgen]
pub struct WasmJsonRpcConfig {
    enabled: bool,
    endpoint_path: String,
    enable_batch: bool,
    max_batch_size: usize,
}

#[wasm_bindgen]
impl WasmJsonRpcConfig {
    #[allow(non_snake_case)]
    #[wasm_bindgen(constructor)]
    pub fn new(
        enabled: Option<bool>,
        endpointPath: Option<String>,
        enableBatch: Option<bool>,
        maxBatchSize: Option<usize>,
    ) -> WasmJsonRpcConfig {
        WasmJsonRpcConfig {
            enabled: enabled.unwrap_or(true),
            endpoint_path: endpointPath.unwrap_or_default(),
            enable_batch: enableBatch.unwrap_or_default(),
            max_batch_size: maxBatchSize.unwrap_or_default(),
        }
    }

    #[wasm_bindgen(getter)]
    pub fn enabled(&self) -> bool {
        self.enabled
    }

    #[wasm_bindgen(setter)]
    pub fn set_enabled(&mut self, value: bool) {
        self.enabled = value;
    }

    #[wasm_bindgen(getter, js_name = "endpointPath")]
    pub fn endpoint_path(&self) -> String {
        self.endpoint_path.clone()
    }

    #[wasm_bindgen(setter, js_name = "endpointPath")]
    pub fn set_endpoint_path(&mut self, value: String) {
        self.endpoint_path = value;
    }

    #[wasm_bindgen(getter, js_name = "enableBatch")]
    pub fn enable_batch(&self) -> bool {
        self.enable_batch
    }

    #[wasm_bindgen(setter, js_name = "enableBatch")]
    pub fn set_enable_batch(&mut self, value: bool) {
        self.enable_batch = value;
    }

    #[wasm_bindgen(getter, js_name = "maxBatchSize")]
    pub fn max_batch_size(&self) -> usize {
        self.max_batch_size
    }

    #[wasm_bindgen(setter, js_name = "maxBatchSize")]
    pub fn set_max_batch_size(&mut self, value: usize) {
        self.max_batch_size = value;
    }

    #[allow(clippy::should_implement_trait)]
    #[wasm_bindgen]
    pub fn default() -> WasmJsonRpcConfig {
        spikard_http::JsonRpcConfig::default().into()
    }
}

/// OpenAPI configuration
#[derive(Clone, Default)]
#[wasm_bindgen]
pub struct WasmOpenApiConfig {
    enabled: bool,
    title: String,
    version: String,
    description: Option<String>,
    swagger_ui_path: String,
    redoc_path: String,
    openapi_json_path: String,
    contact: Option<WasmContactInfo>,
    license: Option<WasmLicenseInfo>,
    servers: Vec<WasmServerInfo>,
    security_schemes: JsValue,
}

#[wasm_bindgen]
impl WasmOpenApiConfig {
    #[allow(clippy::too_many_arguments)]
    #[allow(non_snake_case)]
    #[wasm_bindgen(constructor)]
    pub fn new(
        enabled: Option<bool>,
        title: Option<String>,
        version: Option<String>,
        swaggerUiPath: Option<String>,
        redocPath: Option<String>,
        openapiJsonPath: Option<String>,
        servers: Option<Vec<WasmServerInfo>>,
        securitySchemes: Option<JsValue>,
        description: Option<String>,
        contact: Option<WasmContactInfo>,
        license: Option<WasmLicenseInfo>,
    ) -> WasmOpenApiConfig {
        WasmOpenApiConfig {
            enabled: enabled.unwrap_or(false),
            title: title.unwrap_or_else(|| "API".to_string()),
            version: version.unwrap_or_else(|| "1.0.0".to_string()),
            description,
            swagger_ui_path: swaggerUiPath.unwrap_or_default(),
            redoc_path: redocPath.unwrap_or_default(),
            openapi_json_path: openapiJsonPath.unwrap_or_default(),
            contact,
            license,
            servers: servers.unwrap_or_default(),
            security_schemes: securitySchemes.unwrap_or_default(),
        }
    }

    #[wasm_bindgen(getter)]
    pub fn enabled(&self) -> bool {
        self.enabled
    }

    #[wasm_bindgen(setter)]
    pub fn set_enabled(&mut self, value: bool) {
        self.enabled = value;
    }

    #[wasm_bindgen(getter)]
    pub fn title(&self) -> String {
        self.title.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_title(&mut self, value: String) {
        self.title = value;
    }

    #[wasm_bindgen(getter)]
    pub fn version(&self) -> String {
        self.version.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_version(&mut self, value: String) {
        self.version = value;
    }

    #[wasm_bindgen(getter)]
    pub fn description(&self) -> Option<String> {
        self.description.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_description(&mut self, value: Option<String>) {
        self.description = value;
    }

    #[wasm_bindgen(getter, js_name = "swaggerUiPath")]
    pub fn swagger_ui_path(&self) -> String {
        self.swagger_ui_path.clone()
    }

    #[wasm_bindgen(setter, js_name = "swaggerUiPath")]
    pub fn set_swagger_ui_path(&mut self, value: String) {
        self.swagger_ui_path = value;
    }

    #[wasm_bindgen(getter, js_name = "redocPath")]
    pub fn redoc_path(&self) -> String {
        self.redoc_path.clone()
    }

    #[wasm_bindgen(setter, js_name = "redocPath")]
    pub fn set_redoc_path(&mut self, value: String) {
        self.redoc_path = value;
    }

    #[wasm_bindgen(getter, js_name = "openapiJsonPath")]
    pub fn openapi_json_path(&self) -> String {
        self.openapi_json_path.clone()
    }

    #[wasm_bindgen(setter, js_name = "openapiJsonPath")]
    pub fn set_openapi_json_path(&mut self, value: String) {
        self.openapi_json_path = value;
    }

    #[wasm_bindgen(getter)]
    pub fn contact(&self) -> Option<WasmContactInfo> {
        self.contact.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_contact(&mut self, value: Option<WasmContactInfo>) {
        self.contact = value;
    }

    #[wasm_bindgen(getter)]
    pub fn license(&self) -> Option<WasmLicenseInfo> {
        self.license.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_license(&mut self, value: Option<WasmLicenseInfo>) {
        self.license = value;
    }

    #[wasm_bindgen(getter)]
    pub fn servers(&self) -> Vec<WasmServerInfo> {
        self.servers.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_servers(&mut self, value: Vec<WasmServerInfo>) {
        self.servers = value;
    }

    #[wasm_bindgen(getter, js_name = "securitySchemes")]
    pub fn security_schemes(&self) -> JsValue {
        self.security_schemes.clone()
    }

    #[wasm_bindgen(setter, js_name = "securitySchemes")]
    pub fn set_security_schemes(&mut self, value: JsValue) {
        self.security_schemes = value;
    }

    #[allow(clippy::should_implement_trait)]
    #[wasm_bindgen]
    pub fn default() -> WasmOpenApiConfig {
        spikard_http::OpenApiConfig::default().into()
    }
}

/// Contact information
#[derive(Clone, Default)]
#[wasm_bindgen]
pub struct WasmContactInfo {
    name: Option<String>,
    email: Option<String>,
    url: Option<String>,
}

#[wasm_bindgen]
impl WasmContactInfo {
    #[allow(non_snake_case)]
    #[wasm_bindgen(constructor)]
    pub fn new(name: Option<String>, email: Option<String>, url: Option<String>) -> WasmContactInfo {
        WasmContactInfo { name, email, url }
    }

    #[wasm_bindgen]
    #[allow(clippy::should_implement_trait)]
    pub fn default() -> WasmContactInfo {
        <WasmContactInfo as ::core::default::Default>::default()
    }

    #[wasm_bindgen(getter)]
    pub fn name(&self) -> Option<String> {
        self.name.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_name(&mut self, value: Option<String>) {
        self.name = value;
    }

    #[wasm_bindgen(getter)]
    pub fn email(&self) -> Option<String> {
        self.email.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_email(&mut self, value: Option<String>) {
        self.email = value;
    }

    #[wasm_bindgen(getter)]
    pub fn url(&self) -> Option<String> {
        self.url.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_url(&mut self, value: Option<String>) {
        self.url = value;
    }
}

/// License information
#[derive(Clone, Default)]
#[wasm_bindgen]
pub struct WasmLicenseInfo {
    name: String,
    url: Option<String>,
}

#[wasm_bindgen]
impl WasmLicenseInfo {
    #[allow(non_snake_case)]
    #[wasm_bindgen(constructor)]
    pub fn new(name: String, url: Option<String>) -> WasmLicenseInfo {
        WasmLicenseInfo { name, url }
    }

    #[wasm_bindgen]
    #[allow(clippy::should_implement_trait)]
    pub fn default() -> WasmLicenseInfo {
        <WasmLicenseInfo as ::core::default::Default>::default()
    }

    #[wasm_bindgen(getter)]
    pub fn name(&self) -> String {
        self.name.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_name(&mut self, value: String) {
        self.name = value;
    }

    #[wasm_bindgen(getter)]
    pub fn url(&self) -> Option<String> {
        self.url.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_url(&mut self, value: Option<String>) {
        self.url = value;
    }
}

/// Server information
#[derive(Clone, Default)]
#[wasm_bindgen]
pub struct WasmServerInfo {
    url: String,
    description: Option<String>,
}

#[wasm_bindgen]
impl WasmServerInfo {
    #[allow(non_snake_case)]
    #[wasm_bindgen(constructor)]
    pub fn new(url: String, description: Option<String>) -> WasmServerInfo {
        WasmServerInfo { url, description }
    }

    #[wasm_bindgen]
    #[allow(clippy::should_implement_trait)]
    pub fn default() -> WasmServerInfo {
        <WasmServerInfo as ::core::default::Default>::default()
    }

    #[wasm_bindgen(getter)]
    pub fn url(&self) -> String {
        self.url.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_url(&mut self, value: String) {
        self.url = value;
    }

    #[wasm_bindgen(getter)]
    pub fn description(&self) -> Option<String> {
        self.description.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_description(&mut self, value: Option<String>) {
        self.description = value;
    }
}

/// HTTP Response with custom status code, headers, and content
#[derive(Clone, Default)]
#[wasm_bindgen]
pub struct WasmResponse {
    content: Option<JsValue>,
    status_code: u16,
    headers: JsValue,
}

#[wasm_bindgen]
impl WasmResponse {
    #[allow(non_snake_case)]
    #[wasm_bindgen(constructor)]
    pub fn new(statusCode: Option<u16>, headers: Option<JsValue>, content: Option<JsValue>) -> WasmResponse {
        WasmResponse {
            content,
            status_code: statusCode.unwrap_or_default(),
            headers: headers.unwrap_or_default(),
        }
    }

    #[wasm_bindgen(getter)]
    pub fn content(&self) -> Option<JsValue> {
        self.content.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_content(&mut self, value: Option<JsValue>) {
        self.content = value;
    }

    #[wasm_bindgen(getter, js_name = "statusCode")]
    pub fn status_code(&self) -> u16 {
        self.status_code
    }

    #[wasm_bindgen(setter, js_name = "statusCode")]
    pub fn set_status_code(&mut self, value: u16) {
        self.status_code = value;
    }

    #[wasm_bindgen(getter)]
    pub fn headers(&self) -> JsValue {
        self.headers.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_headers(&mut self, value: JsValue) {
        self.headers = value;
    }

    /// Set a header
    #[wasm_bindgen(js_name = "setHeader")]
    pub fn set_header(&self, key: String, value: String) -> () {
        spikard_http::Response::from(self.clone()).set_header(key, value)
    }

    /// Set a cookie in the response
    #[allow(clippy::too_many_arguments)]
    #[wasm_bindgen(js_name = "setCookie")]
    pub fn set_cookie(
        &self,
        key: String,
        value: String,
        secure: bool,
        http_only: bool,
        max_age: Option<i64>,
        domain: Option<String>,
        path: Option<String>,
        same_site: Option<String>,
    ) -> () {
        spikard_http::Response::from(self.clone())
            .set_cookie(key, value, secure, http_only, max_age, domain, path, same_site)
    }

    #[allow(clippy::should_implement_trait)]
    #[wasm_bindgen]
    pub fn default() -> WasmResponse {
        spikard_http::Response::default().into()
    }
}

/// JWT authentication configuration
#[derive(Clone, Default)]
#[wasm_bindgen]
pub struct WasmJwtConfig {
    secret: String,
    algorithm: String,
    audience: Option<Vec<String>>,
    issuer: Option<String>,
    leeway: u64,
}

#[wasm_bindgen]
impl WasmJwtConfig {
    #[allow(non_snake_case)]
    #[wasm_bindgen(constructor)]
    pub fn new(
        secret: String,
        algorithm: String,
        leeway: u64,
        audience: Option<Vec<String>>,
        issuer: Option<String>,
    ) -> WasmJwtConfig {
        WasmJwtConfig {
            secret,
            algorithm,
            audience,
            issuer,
            leeway,
        }
    }

    #[wasm_bindgen]
    #[allow(clippy::should_implement_trait)]
    pub fn default() -> WasmJwtConfig {
        <WasmJwtConfig as ::core::default::Default>::default()
    }

    #[wasm_bindgen(getter)]
    pub fn secret(&self) -> String {
        self.secret.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_secret(&mut self, value: String) {
        self.secret = value;
    }

    #[wasm_bindgen(getter)]
    pub fn algorithm(&self) -> String {
        self.algorithm.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_algorithm(&mut self, value: String) {
        self.algorithm = value;
    }

    #[wasm_bindgen(getter)]
    pub fn audience(&self) -> Option<Vec<String>> {
        self.audience.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_audience(&mut self, value: Option<Vec<String>>) {
        self.audience = value;
    }

    #[wasm_bindgen(getter)]
    pub fn issuer(&self) -> Option<String> {
        self.issuer.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_issuer(&mut self, value: Option<String>) {
        self.issuer = value;
    }

    #[wasm_bindgen(getter)]
    pub fn leeway(&self) -> u64 {
        self.leeway
    }

    #[wasm_bindgen(setter)]
    pub fn set_leeway(&mut self, value: u64) {
        self.leeway = value;
    }
}

/// API Key authentication configuration
#[derive(Clone, Default)]
#[wasm_bindgen]
pub struct WasmApiKeyConfig {
    keys: Vec<String>,
    header_name: String,
}

#[wasm_bindgen]
impl WasmApiKeyConfig {
    #[allow(non_snake_case)]
    #[wasm_bindgen(constructor)]
    pub fn new(keys: Vec<String>, headerName: String) -> WasmApiKeyConfig {
        WasmApiKeyConfig {
            keys,
            header_name: headerName,
        }
    }

    #[wasm_bindgen]
    #[allow(clippy::should_implement_trait)]
    pub fn default() -> WasmApiKeyConfig {
        <WasmApiKeyConfig as ::core::default::Default>::default()
    }

    #[wasm_bindgen(getter)]
    pub fn keys(&self) -> Vec<String> {
        self.keys.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_keys(&mut self, value: Vec<String>) {
        self.keys = value;
    }

    #[wasm_bindgen(getter, js_name = "headerName")]
    pub fn header_name(&self) -> String {
        self.header_name.clone()
    }

    #[wasm_bindgen(setter, js_name = "headerName")]
    pub fn set_header_name(&mut self, value: String) {
        self.header_name = value;
    }
}

/// Server configuration
#[derive(Clone, Default)]
#[wasm_bindgen]
pub struct WasmServerConfig {
    host: String,
    port: u16,
    workers: usize,
    enable_request_id: bool,
    max_body_size: Option<usize>,
    request_timeout: Option<u64>,
    compression: Option<WasmCompressionConfig>,
    rate_limit: Option<WasmRateLimitConfig>,
    jwt_auth: Option<WasmJwtConfig>,
    api_key_auth: Option<WasmApiKeyConfig>,
    graceful_shutdown: bool,
    shutdown_timeout: u64,
    asyncapi: Option<WasmAsyncApiConfig>,
    openapi: Option<WasmOpenApiConfig>,
    jsonrpc: Option<WasmJsonRpcConfig>,
}

#[wasm_bindgen]
impl WasmServerConfig {
    #[allow(clippy::too_many_arguments)]
    #[allow(non_snake_case)]
    #[wasm_bindgen(constructor)]
    pub fn new(
        host: Option<String>,
        port: Option<u16>,
        workers: Option<usize>,
        enableRequestId: Option<bool>,
        gracefulShutdown: Option<bool>,
        shutdownTimeout: Option<u64>,
        maxBodySize: Option<usize>,
        requestTimeout: Option<u64>,
        compression: Option<WasmCompressionConfig>,
        rateLimit: Option<WasmRateLimitConfig>,
        jwtAuth: Option<WasmJwtConfig>,
        apiKeyAuth: Option<WasmApiKeyConfig>,
        asyncapi: Option<WasmAsyncApiConfig>,
        openapi: Option<WasmOpenApiConfig>,
        jsonrpc: Option<WasmJsonRpcConfig>,
    ) -> WasmServerConfig {
        WasmServerConfig {
            host: host.unwrap_or_else(|| "127.0.0.1".to_string()),
            port: port.unwrap_or(8000),
            workers: workers.unwrap_or(1),
            enable_request_id: enableRequestId.unwrap_or(false),
            max_body_size: maxBodySize,
            request_timeout: requestTimeout,
            compression,
            rate_limit: rateLimit,
            jwt_auth: jwtAuth,
            api_key_auth: apiKeyAuth,
            graceful_shutdown: gracefulShutdown.unwrap_or(true),
            shutdown_timeout: shutdownTimeout.unwrap_or(30),
            asyncapi,
            openapi,
            jsonrpc,
        }
    }

    #[wasm_bindgen(getter)]
    pub fn host(&self) -> String {
        self.host.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_host(&mut self, value: String) {
        self.host = value;
    }

    #[wasm_bindgen(getter)]
    pub fn port(&self) -> u16 {
        self.port
    }

    #[wasm_bindgen(setter)]
    pub fn set_port(&mut self, value: u16) {
        self.port = value;
    }

    #[wasm_bindgen(getter)]
    pub fn workers(&self) -> usize {
        self.workers
    }

    #[wasm_bindgen(setter)]
    pub fn set_workers(&mut self, value: usize) {
        self.workers = value;
    }

    #[wasm_bindgen(getter, js_name = "enableRequestId")]
    pub fn enable_request_id(&self) -> bool {
        self.enable_request_id
    }

    #[wasm_bindgen(setter, js_name = "enableRequestId")]
    pub fn set_enable_request_id(&mut self, value: bool) {
        self.enable_request_id = value;
    }

    #[wasm_bindgen(getter, js_name = "maxBodySize")]
    pub fn max_body_size(&self) -> Option<usize> {
        self.max_body_size
    }

    #[wasm_bindgen(setter, js_name = "maxBodySize")]
    pub fn set_max_body_size(&mut self, value: Option<usize>) {
        self.max_body_size = value;
    }

    #[wasm_bindgen(getter, js_name = "requestTimeout")]
    pub fn request_timeout(&self) -> Option<u64> {
        self.request_timeout
    }

    #[wasm_bindgen(setter, js_name = "requestTimeout")]
    pub fn set_request_timeout(&mut self, value: Option<u64>) {
        self.request_timeout = value;
    }

    #[wasm_bindgen(getter)]
    pub fn compression(&self) -> Option<WasmCompressionConfig> {
        self.compression.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_compression(&mut self, value: Option<WasmCompressionConfig>) {
        self.compression = value;
    }

    #[wasm_bindgen(getter, js_name = "rateLimit")]
    pub fn rate_limit(&self) -> Option<WasmRateLimitConfig> {
        self.rate_limit.clone()
    }

    #[wasm_bindgen(setter, js_name = "rateLimit")]
    pub fn set_rate_limit(&mut self, value: Option<WasmRateLimitConfig>) {
        self.rate_limit = value;
    }

    #[wasm_bindgen(getter, js_name = "jwtAuth")]
    pub fn jwt_auth(&self) -> Option<WasmJwtConfig> {
        self.jwt_auth.clone()
    }

    #[wasm_bindgen(setter, js_name = "jwtAuth")]
    pub fn set_jwt_auth(&mut self, value: Option<WasmJwtConfig>) {
        self.jwt_auth = value;
    }

    #[wasm_bindgen(getter, js_name = "apiKeyAuth")]
    pub fn api_key_auth(&self) -> Option<WasmApiKeyConfig> {
        self.api_key_auth.clone()
    }

    #[wasm_bindgen(setter, js_name = "apiKeyAuth")]
    pub fn set_api_key_auth(&mut self, value: Option<WasmApiKeyConfig>) {
        self.api_key_auth = value;
    }

    #[wasm_bindgen(getter, js_name = "gracefulShutdown")]
    pub fn graceful_shutdown(&self) -> bool {
        self.graceful_shutdown
    }

    #[wasm_bindgen(setter, js_name = "gracefulShutdown")]
    pub fn set_graceful_shutdown(&mut self, value: bool) {
        self.graceful_shutdown = value;
    }

    #[wasm_bindgen(getter, js_name = "shutdownTimeout")]
    pub fn shutdown_timeout(&self) -> u64 {
        self.shutdown_timeout
    }

    #[wasm_bindgen(setter, js_name = "shutdownTimeout")]
    pub fn set_shutdown_timeout(&mut self, value: u64) {
        self.shutdown_timeout = value;
    }

    #[wasm_bindgen(getter)]
    pub fn asyncapi(&self) -> Option<WasmAsyncApiConfig> {
        self.asyncapi.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_asyncapi(&mut self, value: Option<WasmAsyncApiConfig>) {
        self.asyncapi = value;
    }

    #[wasm_bindgen(getter)]
    pub fn openapi(&self) -> Option<WasmOpenApiConfig> {
        self.openapi.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_openapi(&mut self, value: Option<WasmOpenApiConfig>) {
        self.openapi = value;
    }

    #[wasm_bindgen(getter)]
    pub fn jsonrpc(&self) -> Option<WasmJsonRpcConfig> {
        self.jsonrpc.clone()
    }

    #[wasm_bindgen(setter)]
    pub fn set_jsonrpc(&mut self, value: Option<WasmJsonRpcConfig>) {
        self.jsonrpc = value;
    }

    #[allow(clippy::should_implement_trait)]
    #[wasm_bindgen]
    pub fn default() -> WasmServerConfig {
        spikard_http::ServerConfig::default().into()
    }
}

/// HTTP method

#[wasm_bindgen]
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum WasmMethod {
    Get = 0,
    Post = 1,
    Put = 2,
    Patch = 3,
    Delete = 4,
    Head = 5,
    Options = 6,
    Trace = 7,
}

#[allow(clippy::derivable_impls)]
impl Default for WasmMethod {
    fn default() -> Self {
        Self::Get
    }
}

impl WasmMethod {
    /// Returns the serde wire string for this variant (e.g. `"stop"`, `"tool_calls"`).
    pub fn to_api_str(self) -> &'static str {
        match self {
            Self::Get => "Get",
            Self::Post => "Post",
            Self::Put => "Put",
            Self::Patch => "Patch",
            Self::Delete => "Delete",
            Self::Head => "Head",
            Self::Options => "Options",
            Self::Trace => "Trace",
        }
    }

    /// Parses a serde wire string and returns the corresponding variant, or None if unrecognized.
    pub fn from_api_str(s: &str) -> Option<Self> {
        match s {
            "Get" => Some(Self::Get),
            "Post" => Some(Self::Post),
            "Put" => Some(Self::Put),
            "Patch" => Some(Self::Patch),
            "Delete" => Some(Self::Delete),
            "Head" => Some(Self::Head),
            "Options" => Some(Self::Options),
            "Trace" => Some(Self::Trace),
            _ => None,
        }
    }
}

/// Security scheme types

#[wasm_bindgen]
#[derive(Clone, Default)]
pub struct WasmSecuritySchemeInfo {
    pub(crate) r#type: String,
    pub(crate) scheme: Option<String>,
    pub(crate) bearer_format: Option<String>,
    pub(crate) location: Option<String>,
    pub(crate) name: Option<String>,
}

#[wasm_bindgen]
impl WasmSecuritySchemeInfo {
    #[wasm_bindgen(constructor)]
    pub fn new() -> WasmSecuritySchemeInfo {
        Self::default()
    }

    #[wasm_bindgen]
    #[allow(clippy::should_implement_trait)]
    pub fn default() -> WasmSecuritySchemeInfo {
        <Self as ::core::default::Default>::default()
    }

    #[wasm_bindgen(getter, js_name = "type")]
    pub fn r#type(&self) -> String {
        self.r#type.clone()
    }
    #[wasm_bindgen(setter, js_name = "type")]
    pub fn set_type(&mut self, value: String) {
        self.r#type = value;
    }

    #[wasm_bindgen(getter, js_name = "scheme")]
    pub fn scheme(&self) -> Option<String> {
        self.scheme.clone()
    }
    #[wasm_bindgen(setter, js_name = "scheme")]
    pub fn set_scheme(&mut self, value: Option<String>) {
        self.scheme = value;
    }

    #[wasm_bindgen(getter, js_name = "bearerFormat")]
    pub fn bearer_format(&self) -> Option<String> {
        self.bearer_format.clone()
    }
    #[wasm_bindgen(setter, js_name = "bearerFormat")]
    pub fn set_bearer_format(&mut self, value: Option<String>) {
        self.bearer_format = value;
    }

    #[wasm_bindgen(getter, js_name = "location")]
    pub fn location(&self) -> Option<String> {
        self.location.clone()
    }
    #[wasm_bindgen(setter, js_name = "location")]
    pub fn set_location(&mut self, value: Option<String>) {
        self.location = value;
    }

    #[wasm_bindgen(getter, js_name = "name")]
    pub fn name(&self) -> Option<String> {
        self.name.clone()
    }
    #[wasm_bindgen(setter, js_name = "name")]
    pub fn set_name(&mut self, value: Option<String>) {
        self.name = value;
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<WasmCorsConfig> for spikard_http::CorsConfig {
    fn from(val: WasmCorsConfig) -> Self {
        Self {
            allowed_origins: val.allowed_origins.into_iter().collect(),
            allowed_methods: val.allowed_methods.into_iter().collect(),
            allowed_headers: val.allowed_headers.into_iter().collect(),
            expose_headers: val.expose_headers.map(|v| v.into_iter().collect()),
            max_age: val.max_age,
            allow_credentials: val.allow_credentials,
            methods_joined_cache: Default::default(),
            headers_joined_cache: Default::default(),
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<spikard_http::CorsConfig> for WasmCorsConfig {
    fn from(val: spikard_http::CorsConfig) -> Self {
        Self {
            allowed_origins: val.allowed_origins.into_iter().collect(),
            allowed_methods: val.allowed_methods.into_iter().collect(),
            allowed_headers: val.allowed_headers.into_iter().collect(),
            expose_headers: val.expose_headers.map(|v| v.into_iter().collect()),
            max_age: val.max_age,
            allow_credentials: val.allow_credentials,
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<WasmCompressionConfig> for spikard_http::CompressionConfig {
    fn from(val: WasmCompressionConfig) -> Self {
        Self {
            gzip: val.gzip,
            brotli: val.brotli,
            min_size: val.min_size,
            quality: val.quality,
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<spikard_http::CompressionConfig> for WasmCompressionConfig {
    fn from(val: spikard_http::CompressionConfig) -> Self {
        Self {
            gzip: val.gzip,
            brotli: val.brotli,
            min_size: val.min_size,
            quality: val.quality,
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<WasmRateLimitConfig> for spikard_http::RateLimitConfig {
    fn from(val: WasmRateLimitConfig) -> Self {
        Self {
            per_second: val.per_second,
            burst: val.burst,
            ip_based: val.ip_based,
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<spikard_http::RateLimitConfig> for WasmRateLimitConfig {
    fn from(val: spikard_http::RateLimitConfig) -> Self {
        Self {
            per_second: val.per_second,
            burst: val.burst,
            ip_based: val.ip_based,
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<spikard_http::JsonRpcMethodInfo> for WasmJsonRpcMethodInfo {
    fn from(val: spikard_http::JsonRpcMethodInfo) -> Self {
        Self {
            method_name: val.method_name,
            description: val.description,
            params_schema: val
                .params_schema
                .as_ref()
                .and_then(|v| serde_wasm_bindgen::to_value(v).ok()),
            result_schema: val
                .result_schema
                .as_ref()
                .and_then(|v| serde_wasm_bindgen::to_value(v).ok()),
            deprecated: val.deprecated,
            tags: val.tags.into_iter().collect(),
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<WasmProblemDetails> for spikard_http::ProblemDetails {
    fn from(val: WasmProblemDetails) -> Self {
        Self {
            type_uri: val.type_uri,
            title: val.title,
            status: val.status,
            detail: val.detail,
            instance: val.instance,
            extensions: serde_wasm_bindgen::from_value(val.extensions.clone()).unwrap_or_default(),
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<spikard_http::ProblemDetails> for WasmProblemDetails {
    fn from(val: spikard_http::ProblemDetails) -> Self {
        Self {
            type_uri: val.type_uri,
            title: val.title,
            status: val.status,
            detail: val.detail,
            instance: val.instance,
            extensions: js_sys::JSON::parse(&serde_json::to_string(&val.extensions).unwrap_or_default())
                .unwrap_or(JsValue::NULL),
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<WasmAsyncApiConfig> for spikard_http::AsyncApiConfig {
    fn from(val: WasmAsyncApiConfig) -> Self {
        Self {
            enabled: val.enabled,
            spec: val
                .spec
                .as_ref()
                .and_then(|v| serde_wasm_bindgen::from_value(v.clone()).ok()),
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<spikard_http::AsyncApiConfig> for WasmAsyncApiConfig {
    fn from(val: spikard_http::AsyncApiConfig) -> Self {
        Self {
            enabled: val.enabled,
            spec: val.spec.as_ref().and_then(|v| serde_wasm_bindgen::to_value(v).ok()),
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<spikard_http::ParsedChannel> for WasmParsedChannel {
    fn from(val: spikard_http::ParsedChannel) -> Self {
        Self {
            name: val.name,
            address: val.address,
            messages: val.messages.into_iter().collect(),
            bindings: val.bindings.as_ref().and_then(|v| serde_wasm_bindgen::to_value(v).ok()),
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<spikard_http::ParsedOperation> for WasmParsedOperation {
    fn from(val: spikard_http::ParsedOperation) -> Self {
        Self {
            name: val.name,
            action: val.action,
            channel: val.channel,
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<spikard_http::ParsedMessage> for WasmParsedMessage {
    fn from(val: spikard_http::ParsedMessage) -> Self {
        Self {
            name: val.name,
            schema: val.schema.as_ref().and_then(|v| serde_wasm_bindgen::to_value(v).ok()),
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<spikard_http::ParseResult> for WasmParseResult {
    fn from(val: spikard_http::ParseResult) -> Self {
        Self {
            spec_version: val.spec_version,
            title: val.title,
            api_version: val.api_version,
            channels: val.channels.into_iter().map(Into::into).collect(),
            operations: val.operations.into_iter().map(Into::into).collect(),
            messages: val.messages.into_iter().map(Into::into).collect(),
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<spikard_http::asyncapi::ParseRequest> for WasmParseRequest {
    fn from(val: spikard_http::asyncapi::ParseRequest) -> Self {
        Self {
            spec: serde_wasm_bindgen::to_value(&val.spec).unwrap_or(JsValue::NULL),
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<spikard_http::ValidationResponse> for WasmValidationResponse {
    fn from(val: spikard_http::ValidationResponse) -> Self {
        Self {
            valid: val.valid,
            errors: val.errors.into_iter().collect(),
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<spikard_http::ValidateRequest> for WasmValidateRequest {
    fn from(val: spikard_http::ValidateRequest) -> Self {
        Self {
            spec: serde_wasm_bindgen::to_value(&val.spec).unwrap_or(JsValue::NULL),
            channel: val.channel,
            message: val.message,
            payload: serde_wasm_bindgen::to_value(&val.payload).unwrap_or(JsValue::NULL),
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<WasmJsonRpcConfig> for spikard_http::JsonRpcConfig {
    fn from(val: WasmJsonRpcConfig) -> Self {
        Self {
            enabled: val.enabled,
            endpoint_path: val.endpoint_path,
            enable_batch: val.enable_batch,
            max_batch_size: val.max_batch_size,
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<spikard_http::JsonRpcConfig> for WasmJsonRpcConfig {
    fn from(val: spikard_http::JsonRpcConfig) -> Self {
        Self {
            enabled: val.enabled,
            endpoint_path: val.endpoint_path,
            enable_batch: val.enable_batch,
            max_batch_size: val.max_batch_size,
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<WasmOpenApiConfig> for spikard_http::OpenApiConfig {
    fn from(val: WasmOpenApiConfig) -> Self {
        Self {
            enabled: val.enabled,
            title: val.title,
            version: val.version,
            description: val.description,
            swagger_ui_path: val.swagger_ui_path,
            redoc_path: val.redoc_path,
            openapi_json_path: val.openapi_json_path,
            contact: val.contact.map(Into::into),
            license: val.license.map(Into::into),
            servers: val.servers.into_iter().map(Into::into).collect(),
            security_schemes: serde_wasm_bindgen::from_value(val.security_schemes.clone()).unwrap_or_default(),
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<spikard_http::OpenApiConfig> for WasmOpenApiConfig {
    fn from(val: spikard_http::OpenApiConfig) -> Self {
        Self {
            enabled: val.enabled,
            title: val.title,
            version: val.version,
            description: val.description,
            swagger_ui_path: val.swagger_ui_path,
            redoc_path: val.redoc_path,
            openapi_json_path: val.openapi_json_path,
            contact: val.contact.map(Into::into),
            license: val.license.map(Into::into),
            servers: val.servers.into_iter().map(Into::into).collect(),
            security_schemes: js_sys::JSON::parse(&serde_json::to_string(&val.security_schemes).unwrap_or_default())
                .unwrap_or(JsValue::NULL),
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<WasmContactInfo> for spikard_http::ContactInfo {
    fn from(val: WasmContactInfo) -> Self {
        Self {
            name: val.name,
            email: val.email,
            url: val.url,
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<spikard_http::ContactInfo> for WasmContactInfo {
    fn from(val: spikard_http::ContactInfo) -> Self {
        Self {
            name: val.name,
            email: val.email,
            url: val.url,
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<WasmLicenseInfo> for spikard_http::LicenseInfo {
    fn from(val: WasmLicenseInfo) -> Self {
        Self {
            name: val.name,
            url: val.url,
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<spikard_http::LicenseInfo> for WasmLicenseInfo {
    fn from(val: spikard_http::LicenseInfo) -> Self {
        Self {
            name: val.name,
            url: val.url,
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<WasmServerInfo> for spikard_http::ServerInfo {
    fn from(val: WasmServerInfo) -> Self {
        Self {
            url: val.url,
            description: val.description,
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<spikard_http::ServerInfo> for WasmServerInfo {
    fn from(val: spikard_http::ServerInfo) -> Self {
        Self {
            url: val.url,
            description: val.description,
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<WasmResponse> for spikard_http::Response {
    fn from(val: WasmResponse) -> Self {
        Self {
            content: val
                .content
                .as_ref()
                .and_then(|v| serde_wasm_bindgen::from_value(v.clone()).ok()),
            status_code: val.status_code,
            headers: serde_wasm_bindgen::from_value(val.headers.clone()).unwrap_or_default(),
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<spikard_http::Response> for WasmResponse {
    fn from(val: spikard_http::Response) -> Self {
        Self {
            content: val.content.as_ref().and_then(|v| serde_wasm_bindgen::to_value(v).ok()),
            status_code: val.status_code,
            headers: js_sys::JSON::parse(&serde_json::to_string(&val.headers).unwrap_or_default())
                .unwrap_or(JsValue::NULL),
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<WasmJwtConfig> for spikard_http::JwtConfig {
    fn from(val: WasmJwtConfig) -> Self {
        Self {
            secret: val.secret,
            algorithm: val.algorithm,
            audience: val.audience.map(|v| v.into_iter().collect()),
            issuer: val.issuer,
            leeway: val.leeway,
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<spikard_http::JwtConfig> for WasmJwtConfig {
    fn from(val: spikard_http::JwtConfig) -> Self {
        Self {
            secret: val.secret,
            algorithm: val.algorithm,
            audience: val.audience.map(|v| v.into_iter().collect()),
            issuer: val.issuer,
            leeway: val.leeway,
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<WasmApiKeyConfig> for spikard_http::ApiKeyConfig {
    fn from(val: WasmApiKeyConfig) -> Self {
        Self {
            keys: val.keys.into_iter().collect(),
            header_name: val.header_name,
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<spikard_http::ApiKeyConfig> for WasmApiKeyConfig {
    fn from(val: spikard_http::ApiKeyConfig) -> Self {
        Self {
            keys: val.keys.into_iter().collect(),
            header_name: val.header_name,
        }
    }
}

#[allow(clippy::needless_update)]
#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<WasmServerConfig> for spikard_http::ServerConfig {
    fn from(val: WasmServerConfig) -> Self {
        Self {
            host: val.host,
            port: val.port,
            workers: val.workers,
            enable_request_id: val.enable_request_id,
            max_body_size: val.max_body_size,
            request_timeout: val.request_timeout,
            compression: val.compression.map(Into::into),
            rate_limit: val.rate_limit.map(Into::into),
            jwt_auth: val.jwt_auth.map(Into::into),
            api_key_auth: val.api_key_auth.map(Into::into),
            graceful_shutdown: val.graceful_shutdown,
            shutdown_timeout: val.shutdown_timeout,
            asyncapi: val.asyncapi.map(Into::into),
            openapi: val.openapi.map(Into::into),
            jsonrpc: val.jsonrpc.map(Into::into),
            lifecycle_hooks: Default::default(),
            ..Default::default()
        }
    }
}

#[allow(clippy::redundant_closure, clippy::useless_conversion)]
impl From<spikard_http::ServerConfig> for WasmServerConfig {
    fn from(val: spikard_http::ServerConfig) -> Self {
        Self {
            host: val.host,
            port: val.port,
            workers: val.workers,
            enable_request_id: val.enable_request_id,
            max_body_size: val.max_body_size,
            request_timeout: val.request_timeout,
            compression: val.compression.map(Into::into),
            rate_limit: val.rate_limit.map(Into::into),
            jwt_auth: val.jwt_auth.map(Into::into),
            api_key_auth: val.api_key_auth.map(Into::into),
            graceful_shutdown: val.graceful_shutdown,
            shutdown_timeout: val.shutdown_timeout,
            asyncapi: val.asyncapi.map(Into::into),
            openapi: val.openapi.map(Into::into),
            jsonrpc: val.jsonrpc.map(Into::into),
        }
    }
}

impl From<WasmMethod> for spikard_http::Method {
    fn from(val: WasmMethod) -> Self {
        match val {
            WasmMethod::Get => Self::Get,
            WasmMethod::Post => Self::Post,
            WasmMethod::Put => Self::Put,
            WasmMethod::Patch => Self::Patch,
            WasmMethod::Delete => Self::Delete,
            WasmMethod::Head => Self::Head,
            WasmMethod::Options => Self::Options,
            WasmMethod::Trace => Self::Trace,
        }
    }
}

impl From<spikard_http::Method> for WasmMethod {
    fn from(val: spikard_http::Method) -> Self {
        match val {
            spikard_http::Method::Get => Self::Get,
            spikard_http::Method::Post => Self::Post,
            spikard_http::Method::Put => Self::Put,
            spikard_http::Method::Patch => Self::Patch,
            spikard_http::Method::Delete => Self::Delete,
            spikard_http::Method::Head => Self::Head,
            spikard_http::Method::Options => Self::Options,
            spikard_http::Method::Trace => Self::Trace,
        }
    }
}

impl From<WasmSecuritySchemeInfo> for spikard_http::SecuritySchemeInfo {
    fn from(val: WasmSecuritySchemeInfo) -> Self {
        match val.r#type.as_str() {
            "http" => Self::Http {
                scheme: val.scheme.clone().unwrap_or_default(),
                bearer_format: val.bearer_format.clone(),
            },
            "apiKey" => Self::ApiKey {
                location: val.location.clone().unwrap_or_default(),
                name: val.name.clone().unwrap_or_default(),
            },
            _ => Self::Http {
                scheme: Default::default(),
                bearer_format: Default::default(),
            },
        }
    }
}

impl From<spikard_http::SecuritySchemeInfo> for WasmSecuritySchemeInfo {
    fn from(val: spikard_http::SecuritySchemeInfo) -> Self {
        match val {
            spikard_http::SecuritySchemeInfo::Http { scheme, bearer_format } => Self {
                r#type: "http".to_string(),
                bearer_format,
                location: None,
                name: None,
                scheme: Some(scheme),
            },
            spikard_http::SecuritySchemeInfo::ApiKey { location, name } => Self {
                r#type: "apiKey".to_string(),
                bearer_format: None,
                location: Some(location),
                name: Some(name),
                scheme: None,
            },
        }
    }
}
