// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fdad3957aca9c770729ae3f8a2bf85ea9b75453417e5d37b935eb57d7efa235d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package dev.spikard.e2e

import org.junit.jupiter.api.BeforeAll

/**
 * JUnit 5 setup that ensures SUT_URL is set before tests run.
 * Defaults to http://127.0.0.1:8007 if not already set.
 */
class SutServerSetup {
    companion object {
        @BeforeAll
        @JvmStatic
        fun setupSutServer() {
            val existing = System.getenv("SUT_URL") ?: System.getProperty("SUT_URL")
            val url = if (!existing.isNullOrEmpty()) {
                existing
            } else {
                "http://127.0.0.1:8007"
            }
            System.setProperty("SUT_URL", url)
            println("Tests will use SUT at: $url")
        }
    }
}
