# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7a0aa20e22e9cfe1e6106550f28dc9facd94cc2e9fe13be44c3311b70a64f1f3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

module Spikard
  ## The version string for this package.
  VERSION = "0.17.0.pre.rc.5"
end
