# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8d2b914736a655587a50a80bda0621aa8fea8a0bfa8e8449cfe21cfa208d8691
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

module Spikard
  ## The version string for this package.
  VERSION = "0.17.0.pre.rc.1"
end
