// Generated by alef. Do not edit by hand.
// alef:hash:61fbbfc1b88aa2f636ecf0c1c6e5f557b04292dbba6689b3b0c73043e4198c2f

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.7.0"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "spikard-android"
