# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0b192ef8e5ca341b49d82adccc7098b86714fc7213e06132bf210e17223a6f55
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Spikard.ApiKeyConfig do
  @moduledoc "API Key authentication configuration"

  @typedoc "API Key authentication configuration"
  @type t :: %__MODULE__{
          keys: [String.t()],
          header_name: String.t() | nil
        }

  defstruct keys: [],
            header_name: nil
end
