# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:61fbbfc1b88aa2f636ecf0c1c6e5f557b04292dbba6689b3b0c73043e4198c2f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Spikard.ApiKeyConfig do
  @moduledoc "API Key authentication configuration"

  @typedoc "API Key authentication configuration"
  @type t :: %__MODULE__{
          keys: [String.t()],
          header_name: String.t() | nil
        }

  defstruct keys: [],
            header_name: nil
end
