# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a0d25d45224025f60feb1c7d73a0a4e01cc139c4ae9b91556c0780940980b3db
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Spikard.ApiKeyConfig do
  @moduledoc "API Key authentication configuration"

  @typedoc "API Key authentication configuration"
  @type t :: %__MODULE__{
          keys: [String.t()],
          header_name: String.t() | nil
        }

  defstruct keys: [],
            header_name: nil
end
