# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:311daba6328f0b9c14dde594f82aef8bd216642a26bb32c123069d3cb499f1f3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Spikard.AsyncApiConfig do
  @moduledoc "AsyncAPI HTTP endpoint configuration"

  @typedoc "AsyncAPI HTTP endpoint configuration"
  @type t :: %__MODULE__{
          enabled: boolean(),
          spec: String.t() | nil
        }

  defstruct enabled: false,
            spec: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
