# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1bbc071094cc416666a529239845224afde22a75a1b797b70a5e7d08e6c0e805
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Spikard.AsyncApiConfig do
  @moduledoc "AsyncAPI HTTP endpoint configuration"

  @typedoc "AsyncAPI HTTP endpoint configuration"
  @type t :: %__MODULE__{
          enabled: boolean(),
          spec: String.t() | nil
        }

  defstruct enabled: false,
            spec: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
