# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0fdebc102fb44f9e2c6b2c86d89a5f7b4b0813772118b76816bed4084da3cd76
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Spikard.BackgroundJobMetadata do
  @moduledoc false

  @type t :: %__MODULE__{
          name: String.t() | nil,
          request_id: String.t() | nil
        }

  defstruct name: nil,
            request_id: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
