# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:44d5f4d8f6b7b25c1a91bd06857b4c0682d1dce56d2440ff1e80e902d08cdc81
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Spikard.FieldErrorSpec do
  @moduledoc """
  A field-level error to inject at a specific response path.

  `path` is the dot-separated sequence of field names from the operation root to the field
  that should fail, e.g. `"user"` for a top-level field or `"order.customer"` for a nested one.
  """

  @typedoc "A field-level error to inject at a specific response path."
  @type t :: %__MODULE__{
  path: String.t() | nil,
  message: String.t() | nil
  }

  defstruct path: nil,
  message: nil
end
