# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:61fbbfc1b88aa2f636ecf0c1c6e5f557b04292dbba6689b3b0c73043e4198c2f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Spikard.FullSchemaConfig do
  @moduledoc "Configuration for fully-featured schemas with Query, Mutation, and Subscription types"

  @typedoc "Configuration for fully-featured schemas with Query, Mutation, and Subscription types"
  @type t :: %__MODULE__{
          introspection_enabled: boolean(),
          complexity_limit: non_neg_integer() | nil,
          depth_limit: non_neg_integer() | nil
        }

  defstruct introspection_enabled: true,
            complexity_limit: nil,
            depth_limit: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
