# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a0d25d45224025f60feb1c7d73a0a4e01cc139c4ae9b91556c0780940980b3db
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Spikard.JsonRpcConfig do
  @moduledoc "JSON-RPC server configuration"

  @typedoc "JSON-RPC server configuration"
  @type t :: %__MODULE__{
          enabled: boolean(),
          endpoint_path: String.t() | nil,
          enable_batch: boolean(),
          max_batch_size: non_neg_integer()
        }

  defstruct enabled: true,
            endpoint_path: nil,
            enable_batch: false,
            max_batch_size: 0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
