# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:26c03d84d8aa8b01af1294cb901a1b3ca292d02fa388aad85d491acad6ff6f27
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Spikard.JwtConfig do
  @moduledoc "JWT authentication configuration"

  @typedoc "JWT authentication configuration"
  @type t :: %__MODULE__{
  secret: String.t() | nil,
  algorithm: String.t() | nil,
  audience: [String.t()] | nil,
  issuer: String.t() | nil,
  leeway: non_neg_integer()
  }

  defstruct secret: nil,
  algorithm: nil,
  audience: nil,
  issuer: nil,
  leeway: 0
end
