# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:56dc4b179c375dda7ab50c6262ee6db7f3223b46a58eef1b90472f38ffbf5f80
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Spikard.JwtConfig do
  @moduledoc "JWT authentication configuration"

  @typedoc "JWT authentication configuration"
  @type t :: %__MODULE__{
          secret: String.t() | nil,
          algorithm: String.t() | nil,
          audience: [String.t()] | nil,
          issuer: String.t() | nil,
          leeway: non_neg_integer()
        }

  defstruct secret: nil,
            algorithm: nil,
            audience: nil,
            issuer: nil,
            leeway: 0
end
