# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9bde8e8158f8579f0802673f8558e588e6654bbc87df86e8c015ff3decce3080
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Spikard.JwtConfig do
  @moduledoc "JWT authentication configuration"

  @typedoc "JWT authentication configuration"
  @type t :: %__MODULE__{
          secret: String.t() | nil,
          algorithm: String.t() | nil,
          audience: [String.t()] | nil,
          issuer: String.t() | nil,
          leeway: non_neg_integer()
        }

  defstruct secret: nil,
            algorithm: nil,
            audience: nil,
            issuer: nil,
            leeway: 0
end
