# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0deed3730fe0b3937dd6f4a66b4ed57060000f1fc80c0951bee7a9e219c0b6fe
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Spikard.Method do
  @moduledoc "HTTP method"

  @typedoc "HTTP method"
  @type t :: :get | :post | :put | :patch | :delete | :head | :options | :connect | :trace

  @get :get
  @post :post
  @put :put
  @patch :patch
  @delete :delete
  @head :head
  @options :options
  @connect :connect
  @trace :trace

  @spec get() :: t()
  def get, do: @get
  @spec post() :: t()
  def post, do: @post
  @spec put() :: t()
  def put, do: @put
  @spec patch() :: t()
  def patch, do: @patch
  @spec delete() :: t()
  def delete, do: @delete
  @spec head() :: t()
  def head, do: @head
  @spec options() :: t()
  def options, do: @options
  @spec connect() :: t()
  def connect, do: @connect
  @spec trace() :: t()
  def trace, do: @trace
end
