# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:21b3a5c2c0e3e2dafa5eac0ba17686d1a539091ca41a7ce18d3a007896d75bf0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Spikard.ParsedChannel do
  @moduledoc "A single channel extracted from an AsyncAPI spec"

  @typedoc "A single channel extracted from an AsyncAPI spec"
  @type t :: %__MODULE__{
  name: String.t() | nil,
  address: String.t() | nil,
  messages: [String.t()],
  bindings: String.t() | nil
  }

  defstruct name: nil,
  address: nil,
  messages: [],
  bindings: nil
end
