# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0fdebc102fb44f9e2c6b2c86d89a5f7b4b0813772118b76816bed4084da3cd76
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Spikard.ParseRequest do
  @moduledoc "Request body for `POST /asyncapi/parse`"

  @typedoc "Request body for `POST /asyncapi/parse`"
  @type t :: %__MODULE__{
          spec: String.t() | nil
        }

  defstruct spec: nil
end
