# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2a5a90b766eca1206c1cbd4e3f5c8797895d4a5a3411c48af1270b3074c9ed23
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Spikard.ParsedOperation do
  @moduledoc "A single operation extracted from an AsyncAPI spec"

  @typedoc "A single operation extracted from an AsyncAPI spec"
  @type t :: %__MODULE__{
          name: String.t() | nil,
          action: String.t() | nil,
          channel: String.t() | nil
        }

  defstruct name: nil,
            action: nil,
            channel: nil
end
