# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d3901ccd0562d670c46890c6dfba29ddcc523dd04f549dd746fe451e2d4f19c5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Spikard.ParsedMessage do
  @moduledoc "A resolved message (name + JSON Schema)"

  @typedoc "A resolved message (name + JSON Schema)"
  @type t :: %__MODULE__{
          name: String.t() | nil,
          schema: String.t() | nil
        }

  defstruct name: nil,
            schema: nil
end
