# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:44d5f4d8f6b7b25c1a91bd06857b4c0682d1dce56d2440ff1e80e902d08cdc81
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Spikard.Response do
  @moduledoc "HTTP Response with custom status code, headers, and content"

  @typedoc "HTTP Response with custom status code, headers, and content"
  @type t :: %__MODULE__{
  content: String.t() | nil,
  status_code: non_neg_integer(),
  headers: map()
  }

  defstruct content: nil,
  status_code: 0,
  headers: %{}

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
