# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b5167d25336e3011d4daa9dcfbe6e9b01fdb7992536b9984a54b4650875c3ba2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Spikard.ResponseSnapshot do
  @moduledoc "Snapshot of an Axum response used by higher-level language bindings."

  @typedoc "Snapshot of an Axum response used by higher-level language bindings."
  @type t :: %__MODULE__{
  status: non_neg_integer(),
  headers: map(),
  body: binary()
  }

  defstruct status: 0,
  headers: %{},
  body: <<>>
end
