# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e0d1fa10e160246309f8a258b5ab03668d066e83bc4b81e9b7679fda0d6de229
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Spikard.ResponseSnapshot do
  @moduledoc "Snapshot of an Axum response used by higher-level language bindings."

  @typedoc "Snapshot of an Axum response used by higher-level language bindings."
  @type t :: %__MODULE__{
          status: non_neg_integer(),
          headers: map(),
          body: binary()
  }

  defstruct status: 0,
  headers: %{},
  body: <<>>
end
