# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2d52f3f3ace4969b27d64f1c96278f5159bdcb297a4c8aea8492b6907ccc4327
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Spikard.SchemaConfig do
  @moduledoc """
  Configuration for GraphQL schema building.

  Encapsulates all schema-level configuration options including
  introspection control, complexity limits, and depth limits.
  """

  @typedoc "Configuration for GraphQL schema building."
  @type t :: %__MODULE__{
          introspection_enabled: boolean(),
          complexity_limit: non_neg_integer() | nil,
          depth_limit: non_neg_integer() | nil
        }

  defstruct introspection_enabled: true,
            complexity_limit: nil,
            depth_limit: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
