# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ff661085f2552438300d3602c96320234ed4598748050b75209b591afdcf32ec
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Spikard.SecuritySchemeInfo do
  @moduledoc "Security scheme types"

  @typedoc "Security scheme types"
  @type t :: term()

  @type http :: %{type: :http, scheme: String.t(), bearer_format: String.t()}
  @type api_key :: %{type: :api_key, location: String.t(), name: String.t()}

  def http(scheme, bearer_format), do: {:http, %{scheme: scheme, bearer_format: bearer_format}}
  def api_key(location, name), do: {:api_key, %{location: location, name: name}}
end
