# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0deed3730fe0b3937dd6f4a66b4ed57060000f1fc80c0951bee7a9e219c0b6fe
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Spikard.SecuritySchemeInfo do
  @moduledoc "Security scheme types"

  @typedoc "Security scheme types"
  @type t :: term()

  @type http :: %{type: :http, scheme: String.t(), bearer_format: String.t()}
  @type api_key :: %{type: :api_key, location: String.t(), name: String.t()}
end
