# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:191d1a176db6a96adfe857a819eadc04f98bc69838450d88e84d6a76968c88d8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Spikard.SecuritySchemeInfo do
  @moduledoc "Security scheme types"

  @typedoc "Security scheme types"
  @type t :: term()

  @type http :: %{type: :http, scheme: String.t(), bearer_format: String.t()}
  @type api_key :: %{type: :api_key, location: String.t(), name: String.t()}
end
