# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2d52f3f3ace4969b27d64f1c96278f5159bdcb297a4c8aea8492b6907ccc4327
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Spikard.StaticFilesConfig do
  @moduledoc "Static file serving configuration"

  @typedoc "Static file serving configuration"
  @type t :: %__MODULE__{
          directory: String.t() | nil,
          route_prefix: String.t() | nil,
          index_file: boolean(),
          cache_control: String.t() | nil
        }

  defstruct directory: nil,
            route_prefix: nil,
            index_file: false,
            cache_control: nil
end
