# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ad945baf4e9b1e14ce5dfec13f5ff80ebba31239f3d170fb1c15674547b888a0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Spikard.TestingSseEvent do
  @moduledoc "A single Server-Sent Event."

  @typedoc "A single Server-Sent Event."
  @type t :: %__MODULE__{
  data: String.t() | nil
  }

  defstruct data: nil
end
