# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b5167d25336e3011d4daa9dcfbe6e9b01fdb7992536b9984a54b4650875c3ba2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Spikard.ValidateRequest do
  @moduledoc "Request body for `POST /asyncapi/validate`"

  @typedoc "Request body for `POST /asyncapi/validate`"
  @type t :: %__MODULE__{
  spec: String.t() | nil,
  channel: String.t() | nil,
  message: String.t() | nil,
  payload: String.t() | nil
  }

  defstruct spec: nil,
  channel: nil,
  message: nil,
  payload: nil
end
