name: 'Build Wheels'
description: 'Build Python wheels using cibuildwheel'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.13'

outputs:
  artifact-name:
    description: 'Name of the uploaded artifact'
    value: wheels-${{ runner.os }}

runs:
  using: 'composite'
  steps:
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Setup Python environment
      uses: ./.github/actions/setup-python-env
      with:
        python-version: ${{ inputs.python-version }}
        cache-prefix: python-build-wheels

    - name: Install cibuildwheel
      shell: bash
      run: python -m pip install cibuildwheel==3.2.0

    - name: Build wheels
      shell: bash
      run: python -m cibuildwheel crates/spikard-py --output-dir wheelhouse
      env:
        # Using abi3; a single cp310 build produces the universal wheel. Avoid duplicate names.
        CIBW_BUILD: "cp310-*"

        CIBW_ARCHS_LINUX: x86_64 aarch64
        CIBW_ARCHS_MACOS: x86_64 arm64
        CIBW_ARCHS_WINDOWS: AMD64

        CIBW_BUILD_FRONTEND: "build"
        CIBW_BUILD_VERBOSITY: 1

        CIBW_BEFORE_ALL_LINUX: >
          yum install -y openssl-devel pkgconfig &&
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y &&
          source ~/.cargo/env
        CIBW_BEFORE_ALL_MACOS: rustup target add x86_64-apple-darwin aarch64-apple-darwin
        CIBW_BEFORE_ALL_WINDOWS: ""

        CIBW_BEFORE_BUILD_LINUX: pip install --upgrade pip maturin build
        CIBW_BEFORE_BUILD_MACOS: pip install --upgrade pip maturin build
        CIBW_BEFORE_BUILD_WINDOWS: pip install --upgrade pip maturin build

        CIBW_ENVIRONMENT: MATURIN_BUILD_ARGS="--compatibility linux"
        CIBW_ENVIRONMENT_WINDOWS: MATURIN_BUILD_ARGS=""
        CIBW_ENVIRONMENT_MACOS: 'MATURIN_BUILD_ARGS="" MACOSX_DEPLOYMENT_TARGET=11.0'

        CIBW_SKIP: "*-musllinux* *-win32 *-manylinux_i686"

        CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
        CIBW_MANYLINUX_AARCH64_IMAGE: manylinux2014

        CIBW_REPAIR_WHEEL_COMMAND_LINUX: ""
        CIBW_REPAIR_WHEEL_COMMAND_MACOS: ""
        CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: ""

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ runner.os }}
        path: ./wheelhouse/*.whl
        retention-days: 7
