// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:63b3214a76f76c30fe73c659214474837b30c1cdd41aecea9b4301aed4de8c61
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
const std = @import("std");
const testing = std.testing;
const spikard = @import("spikard");

// E2e tests for category: query_params

test "42_negative_integer_query_param" {
    // Query parameter with negative integer value should be parsed correctly
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "43_scientific_notation_float" {
    // Query parameter with scientific notation float should parse correctly
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "44_string_minlength_validation_success" {
    // String query parameter meeting minLength constraint should succeed
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "45_string_minlength_validation_failure" {
    // String query parameter below minLength constraint should fail validation
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "46_string_maxlength_validation_failure" {
    // String query parameter exceeding maxLength constraint should fail validation
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "47_pattern_validation_email_success" {
    // String query parameter matching regex pattern should succeed
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "48_pattern_validation_email_failure" {
    // String query parameter not matching regex pattern should fail validation
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "49_integer_gt_constraint_success" {
    // Integer query parameter greater than exclusive minimum should succeed
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "50_integer_gt_constraint_failure" {
    // Integer query parameter equal to exclusive minimum should fail validation
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "51_integer_ge_constraint_boundary" {
    // Integer query parameter equal to minimum should succeed with ge constraint
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "52_integer_le_constraint_boundary" {
    // Integer query parameter equal to maximum should succeed with le constraint
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "53_integer_le_constraint_failure" {
    // Integer query parameter exceeding maximum should fail validation
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "54_array_minitems_constraint_success" {
    // Array query parameter meeting minItems constraint should succeed
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "55_array_minitems_constraint_failure" {
    // Array query parameter below minItems constraint should fail validation
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "56_array_maxitems_constraint_failure" {
    // Array query parameter exceeding maxItems constraint should fail validation
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "57_boolean_empty_string_coercion" {
    // Boolean query parameter with empty string should coerce to false
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "58_format_email_success" {
    // Query parameter with valid email format should be accepted
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "59_format_email_failure" {
    // Query parameter with invalid email format should fail validation
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "60_format_ipv4_success" {
    // Query parameter with valid IPv4 address should be accepted
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "61_format_ipv4_failure" {
    // Query parameter with invalid IPv4 address should fail validation
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "62_format_ipv6_success" {
    // Query parameter with valid IPv6 address should be accepted
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "63_format_uri_success" {
    // Query parameter with valid URI should be accepted
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "64_format_uri_failure" {
    // Query parameter with invalid URI should fail validation
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "65_format_hostname_success" {
    // Query parameter with valid hostname should be accepted
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "66_multipleof_constraint_success" {
    // Integer query parameter that is multiple of constraint should succeed
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "67_multipleof_constraint_failure" {
    // Integer query parameter that is not multiple of constraint should fail
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "68_array_uniqueitems_success" {
    // Array query parameter with unique items should succeed
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "69_array_uniqueitems_failure" {
    // Array query parameter with duplicate items should fail when uniqueItems is true
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "70_array_separator_pipe" {
    // Array query parameter with pipe separator should parse correctly
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "71_array_separator_semicolon" {
    // Array query parameter with semicolon separator should parse correctly
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "72_array_separator_space" {
    // Array query parameter with space separator should parse correctly
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "array_query_parameter_empty_array" {
    // Tests array query parameter when no values are provided
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "array_query_parameter_single_value" {
    // Tests array query parameter with single value
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "boolean_query_parameter_numeric_1" {
    // Tests boolean query parameter with '1' converts to true
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "boolean_query_parameter_true" {
    // Tests boolean query parameter with 'true' string value
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "date_query_parameter_success" {
    // Tests date query parameter with valid ISO date format
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "datetime_query_parameter_success" {
    // Tests datetime query parameter with valid ISO datetime format
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "enum_query_parameter_invalid_value" {
    // Tests enum query parameter with value not in enum
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "enum_query_parameter_success" {
    // Tests enum query parameter with valid enum value
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "float_query_param_with_ge_constraint_success" {
    // Tests float query parameter with ge validation at boundary
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "integer_query_param_with_ge_constraint_boundary" {
    // Tests integer query parameter with ge validation at boundary value
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "integer_query_param_with_gt_constraint_valid" {
    // Tests integer query parameter with gt validation, value above limit
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "integer_query_param_with_le_constraint_boundary" {
    // Tests integer query parameter with le validation at boundary value
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "integer_query_param_with_lt_constraint_valid" {
    // Tests integer query parameter with lt validation, value below limit
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "integer_with_default_value_not_provided" {
    // Tests integer parameter with default value when not provided
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "integer_with_default_value_override" {
    // Tests integer parameter with default value when overridden with custom value
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "list_of_integers_multiple_values" {
    // Tests list query parameter with multiple integer values using same key
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "list_of_strings_multiple_values" {
    // Tests list of string query parameters with multiple values
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "list_query_parameter_required_but_missing" {
    // Tests required list parameter without any values, should return 422
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "list_with_default_empty_array_no_values_provided" {
    // Tests list parameter with default=[] when no values provided, should return empty list
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "multiple_query_parameters_with_different_types" {
    // Tests multiple query parameters of different types in single request
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "optional_integer_query_parameter_missing" {
    // Tests optional integer parameter without value, should not error
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "optional_query_parameter_with_default_value" {
    // Tests optional query parameter that uses default when not provided
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "optional_string_query_parameter_missing" {
    // Tests optional string parameter without value, should return None/null
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "optional_string_query_parameter_provided" {
    // Tests optional string parameter with value provided
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "query_parameter_with_special_characters_url_encoding" {
    // Tests query parameters with special characters that need URL encoding
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "query_parameter_with_url_encoded_space" {
    // Tests query parameter with URL encoded space character
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "query_parameter_with_url_encoded_special_characters" {
    // Tests query parameter with URL encoded special characters
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "required_integer_query_parameter_float_value" {
    // Tests integer query parameter with float string value, should return 422
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "required_integer_query_parameter_invalid_type" {
    // Tests integer query parameter with non-numeric string, should return 422
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "required_integer_query_parameter_missing" {
    // Tests a required integer query parameter without providing value, should return 422
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "required_integer_query_parameter_success" {
    // Tests a required integer query parameter with valid value
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "required_string_query_parameter_missing" {
    // Tests a required string query parameter without providing value, should return 422
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "required_string_query_parameter_success" {
    // Tests a required string query parameter with valid value
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "string_query_param_with_max_length_constraint_fail" {
    // Tests string query parameter with max_length validation failure
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "string_query_param_with_min_length_constraint_fail" {
    // Tests string query parameter with min_length validation failure
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "string_query_param_with_regex_pattern_fail" {
    // Tests string query parameter with regex pattern validation failure
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "string_validation_with_regex_failure" {
    // Tests string parameter with regex pattern validation - non-matching pattern returns 422
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "string_validation_with_regex_success" {
    // Tests string parameter with regex pattern validation - matching pattern
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "uuid_query_parameter_invalid_format" {
    // Tests UUID query parameter with invalid UUID format
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}

test "uuid_query_parameter_success" {
    // Tests UUID query parameter with valid UUID format
    var gpa = std.heap.GeneralPurposeAllocator(.{}){}
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const response = spikard.handle_request();
}
