// This file is auto-generated by alef. DO NOT EDIT.
import { describe, it, expect } from 'vitest';

describe('cors', () => {
  it('_cors_preflight_method_not_allowed: CORS preflight request for non-allowed method should be rejected', async () => {
    const response = await app.request('/api/data', { method: 'OPTIONS', headers: {
      'Origin': 'https://example.com',
      'Access-Control-Request-Method': 'DELETE',
      'Access-Control-Request-Headers': 'Content-Type',
    } });
    expect(response.status).toBe(403);
  });

  it('_cors_preflight_header_not_allowed: CORS preflight request with non-allowed header should be rejected', async () => {
    const response = await app.request('/api/data', { method: 'OPTIONS', headers: {
      'Access-Control-Request-Headers': 'X-Custom-Header',
      'Origin': 'https://example.com',
      'Access-Control-Request-Method': 'POST',
    } });
    expect(response.status).toBe(403);
  });

  it('_cors_max_age: CORS preflight response should include Access-Control-Max-Age', async () => {
    const response = await app.request('/api/data', { method: 'OPTIONS', headers: {
      'Access-Control-Request-Headers': 'Content-Type',
      'Access-Control-Request-Method': 'POST',
      'Origin': 'https://example.com',
    } });
    expect(response.status).toBe(204);
    expect(response.headers.get('access-control-allow-origin')).toBe('https://example.com');
    expect(response.headers.get('access-control-allow-methods')).toBe('POST');
    expect(response.headers.get('access-control-max-age')).toBe('3600');
    expect(response.headers.get('access-control-allow-headers')).toBe('Content-Type');
  });

  it('_cors_expose_headers: CORS response should include Access-Control-Expose-Headers for custom headers', async () => {
    const response = await app.request('/api/data', { method: 'GET', headers: {
      'Origin': 'https://example.com',
    } });
    expect(response.status).toBe(200);
    expect(response.headers.get('x-total-count')).toBe('42');
    expect(response.headers.get('access-control-allow-origin')).toBe('https://example.com');
    expect(response.headers.get('access-control-expose-headers')).toBe('X-Total-Count, X-Request-Id');
    expect(response.headers.get('x-request-id')).toBe('abc123');
  });

  it('_cors_origin_null: CORS request with \'null\' origin should be handled according to policy', async () => {
    const response = await app.request('/api/data', { method: 'GET', headers: {
      'Origin': 'null',
    } });
    expect(response.status).toBe(403);
    const data = await response.json();
    expect(data).toEqual({ error: "Origin 'null' is not allowed" });
  });

  it('cors_request_blocked: Tests CORS request from disallowed origin', async () => {
    const response = await app.request('/items/', { method: 'GET', headers: {
      'Origin': 'https://malicious-site.com',
    } });
    expect(response.status).toBe(403);
    const data = await response.json();
    expect(data).toEqual({ detail: "CORS request from origin 'https://malicious-site.com' not allowed" });
  });

  it('cors_safelisted_headers_without_preflight: Tests that safelisted headers (Content-Type: text/plain, Accept, Accept-Language) don\'t require preflight', async () => {
    const response = await app.request('/api/form', { method: 'POST', headers: {
      'Content-Type': 'text/plain',
      'Accept': 'application/json',
      'Origin': 'https://app.example.com',
      'Accept-Language': 'en-US',
    } });
    expect(response.status).toBe(200);
    const data = await response.json();
    expect(data).toEqual({ message: "Success" });
    expect(response.headers.get('access-control-allow-origin')).toBe('https://app.example.com');
    expect(response.headers.get('vary')).toBe('Origin');
  });
});
