<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:191d1a176db6a96adfe857a819eadc04f98bc69838450d88e84d6a76968c88d8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace Spikard\Php;

final class SpikardPhp
{
    /**
     * Create a simple schema configuration with only Query type.
     *
     * This is a convenience function for schemas that only have queries.
     *
     * @return QueryOnlyConfig
     */
    public static function schemaQueryOnly(
    ): QueryOnlyConfig {
        return \Spikard\Php\SpikardPhpApi::schemaQueryOnly(); // delegate to native extension class
    }
    /**
     * Create a schema configuration with Query and Mutation types.
     *
     * This is a convenience function for schemas with queries and mutations but no subscriptions.
     *
     * @return QueryMutationConfig
     */
    public static function schemaQueryMutation(
    ): QueryMutationConfig {
        return \Spikard\Php\SpikardPhpApi::schemaQueryMutation(); // delegate to native extension class
    }
    /**
     * Create a schema configuration with all three root types.
     *
     * This is a convenience function for fully-featured schemas.
     *
     * @return FullSchemaConfig
     */
    public static function schemaFull(
    ): FullSchemaConfig {
        return \Spikard\Php\SpikardPhpApi::schemaFull(); // delegate to native extension class
    }
}
