# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:595966fb62c51cd3e52439d5a972514ca5ba7ab7670e8d2b9ed9b1f8789ccb8f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""E2e tests for category: sse."""

import pytest  # noqa: F401


def test_sse_event_retry_5000_milliseconds(mock_server: str) -> None:
    """Tests SSE event with 5000ms retry interval."""
    import os  # noqa: PLC0415
    import urllib.request  # noqa: PLC0415

    base = os.environ.get("MOCK_SERVER_URL", mock_server)
    url = f"{base}/fixtures/sse_event_retry_5000_milliseconds"
    _headers = {
        "Accept": "text/event-stream",
    }
    _req = urllib.request.Request(url, headers=_headers, method="GET")

    class _NoRedirect(urllib.request.HTTPRedirectHandler):  # noqa: N801
        def redirect_request(self, *args, **kwargs):
            return None  # noqa: E704

    _opener = urllib.request.build_opener(_NoRedirect())
    try:
        response = _opener.open(_req)  # noqa: S310
        status_code = response.status
        resp_headers = dict(response.headers)
    except urllib.error.HTTPError as _exc:
        status_code = _exc.code
        resp_headers = dict(_exc.headers)
    assert status_code == 200  # noqa: S101
    assert resp_headers["content-type"] == "text/event-stream"  # noqa: S101


def test_sse_event_with_all_fields(mock_server: str) -> None:
    """Tests SSE event with all optional fields (id, type, retry)."""
    import os  # noqa: PLC0415
    import urllib.request  # noqa: PLC0415

    base = os.environ.get("MOCK_SERVER_URL", mock_server)
    url = f"{base}/fixtures/sse_event_with_all_fields"
    _headers = {
        "Accept": "text/event-stream",
    }
    _req = urllib.request.Request(url, headers=_headers, method="GET")

    class _NoRedirect(urllib.request.HTTPRedirectHandler):  # noqa: N801
        def redirect_request(self, *args, **kwargs):
            return None  # noqa: E704

    _opener = urllib.request.build_opener(_NoRedirect())
    try:
        response = _opener.open(_req)  # noqa: S310
        status_code = response.status
        resp_headers = dict(response.headers)
    except urllib.error.HTTPError as _exc:
        status_code = _exc.code
        resp_headers = dict(_exc.headers)
    assert status_code == 200  # noqa: S101
    assert resp_headers["content-type"] == "text/event-stream"  # noqa: S101


def test_sse_event_with_data_and_metadata(mock_server: str) -> None:
    """Tests SSE event with JSON data and metadata fields."""
    import os  # noqa: PLC0415
    import urllib.request  # noqa: PLC0415

    base = os.environ.get("MOCK_SERVER_URL", mock_server)
    url = f"{base}/fixtures/sse_event_with_data_and_metadata"
    _headers = {
        "Accept": "text/event-stream",
    }
    _req = urllib.request.Request(url, headers=_headers, method="GET")

    class _NoRedirect(urllib.request.HTTPRedirectHandler):  # noqa: N801
        def redirect_request(self, *args, **kwargs):
            return None  # noqa: E704

    _opener = urllib.request.build_opener(_NoRedirect())
    try:
        response = _opener.open(_req)  # noqa: S310
        status_code = response.status
        resp_headers = dict(response.headers)
    except urllib.error.HTTPError as _exc:
        status_code = _exc.code
        resp_headers = dict(_exc.headers)
    assert status_code == 200  # noqa: S101
    assert resp_headers["content-type"] == "text/event-stream"  # noqa: S101


def test_sse_event_with_id_field(mock_server: str) -> None:
    """Tests SSE event includes unique ID field."""
    import os  # noqa: PLC0415
    import urllib.request  # noqa: PLC0415

    base = os.environ.get("MOCK_SERVER_URL", mock_server)
    url = f"{base}/fixtures/sse_event_with_id_field"
    _headers = {
        "Accept": "text/event-stream",
    }
    _req = urllib.request.Request(url, headers=_headers, method="GET")

    class _NoRedirect(urllib.request.HTTPRedirectHandler):  # noqa: N801
        def redirect_request(self, *args, **kwargs):
            return None  # noqa: E704

    _opener = urllib.request.build_opener(_NoRedirect())
    try:
        response = _opener.open(_req)  # noqa: S310
        status_code = response.status
        resp_headers = dict(response.headers)
    except urllib.error.HTTPError as _exc:
        status_code = _exc.code
        resp_headers = dict(_exc.headers)
    assert status_code == 200  # noqa: S101
    assert resp_headers["content-type"] == "text/event-stream"  # noqa: S101


def test_sse_event_with_retry_field(mock_server: str) -> None:
    """Tests SSE event includes retry interval field."""
    import os  # noqa: PLC0415
    import urllib.request  # noqa: PLC0415

    base = os.environ.get("MOCK_SERVER_URL", mock_server)
    url = f"{base}/fixtures/sse_event_with_retry_field"
    _headers = {
        "Accept": "text/event-stream",
    }
    _req = urllib.request.Request(url, headers=_headers, method="GET")

    class _NoRedirect(urllib.request.HTTPRedirectHandler):  # noqa: N801
        def redirect_request(self, *args, **kwargs):
            return None  # noqa: E704

    _opener = urllib.request.build_opener(_NoRedirect())
    try:
        response = _opener.open(_req)  # noqa: S310
        status_code = response.status
        resp_headers = dict(response.headers)
    except urllib.error.HTTPError as _exc:
        status_code = _exc.code
        resp_headers = dict(_exc.headers)
    assert status_code == 200  # noqa: S101
    assert resp_headers["content-type"] == "text/event-stream"  # noqa: S101


def test_sse_event_with_type_field(mock_server: str) -> None:
    """Tests SSE event includes event type field."""
    import os  # noqa: PLC0415
    import urllib.request  # noqa: PLC0415

    base = os.environ.get("MOCK_SERVER_URL", mock_server)
    url = f"{base}/fixtures/sse_event_with_type_field"
    _headers = {
        "Accept": "text/event-stream",
    }
    _req = urllib.request.Request(url, headers=_headers, method="GET")

    class _NoRedirect(urllib.request.HTTPRedirectHandler):  # noqa: N801
        def redirect_request(self, *args, **kwargs):
            return None  # noqa: E704

    _opener = urllib.request.build_opener(_NoRedirect())
    try:
        response = _opener.open(_req)  # noqa: S310
        status_code = response.status
        resp_headers = dict(response.headers)
    except urllib.error.HTTPError as _exc:
        status_code = _exc.code
        resp_headers = dict(_exc.headers)
    assert status_code == 200  # noqa: S101
    assert resp_headers["content-type"] == "text/event-stream"  # noqa: S101


def test_sse_multiple_events_stream(mock_server: str) -> None:
    """Tests SSE stream with multiple consecutive events."""
    import os  # noqa: PLC0415
    import urllib.request  # noqa: PLC0415

    base = os.environ.get("MOCK_SERVER_URL", mock_server)
    url = f"{base}/fixtures/sse_multiple_events_stream"
    _headers = {
        "Accept": "text/event-stream",
    }
    _req = urllib.request.Request(url, headers=_headers, method="GET")

    class _NoRedirect(urllib.request.HTTPRedirectHandler):  # noqa: N801
        def redirect_request(self, *args, **kwargs):
            return None  # noqa: E704

    _opener = urllib.request.build_opener(_NoRedirect())
    try:
        response = _opener.open(_req)  # noqa: S310
        status_code = response.status
        resp_headers = dict(response.headers)
    except urllib.error.HTTPError as _exc:
        status_code = _exc.code
        resp_headers = dict(_exc.headers)
    assert status_code == 200  # noqa: S101
    assert resp_headers["content-type"] == "text/event-stream"  # noqa: S101


def test_sse_simple_event_stream(mock_server: str) -> None:
    """Tests Server-Sent Events with simple text events."""
    import os  # noqa: PLC0415
    import urllib.request  # noqa: PLC0415

    base = os.environ.get("MOCK_SERVER_URL", mock_server)
    url = f"{base}/fixtures/sse_simple_event_stream"
    _headers = {
        "Accept": "text/event-stream",
    }
    _req = urllib.request.Request(url, headers=_headers, method="GET")

    class _NoRedirect(urllib.request.HTTPRedirectHandler):  # noqa: N801
        def redirect_request(self, *args, **kwargs):
            return None  # noqa: E704

    _opener = urllib.request.build_opener(_NoRedirect())
    try:
        response = _opener.open(_req)  # noqa: S310
        status_code = response.status
        resp_headers = dict(response.headers)
    except urllib.error.HTTPError as _exc:
        status_code = _exc.code
        resp_headers = dict(_exc.headers)
    assert status_code == 200  # noqa: S101
    assert resp_headers["content-type"] == "text/event-stream"  # noqa: S101
    assert resp_headers["cache-control"] == "no-cache"  # noqa: S101
