AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - "ext/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "**/Gemfile.ext"
    - "**/Gemfile.ext.lock"
    - "packages/ruby/ext/**/*"
    - "packages/ruby/tmp/**/*"
    - "packages/ruby/vendor/**/*"
    - "packages/ruby/**/Gemfile.ext"
    - "packages/ruby/**/Gemfile.ext.lock"

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - 'spec/**/*.rb'
    - 'vendor/**/spec/**/*.rb'
    - 'vendor/crates/spikard-rb/examples/**/*.rb'
    - '**/*.gemspec'

Lint/UnusedBlockArgument:
  Exclude:
    - 'spec/**/*.rb'

Lint/MissingSuper:
  Exclude:
    - 'spec/**/*.rb'

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/**/*.rb'

# TODO: Refactor to reduce complexity
Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 12

Metrics/MethodLength:
  Max: 15

Metrics/ParameterLists:
  Max: 15
  CountKeywordArgs: false
