AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - "ext/**"
    - "tmp/**/*"
    - "**/Gemfile.ext"
    - "**/Gemfile.ext.lock"

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'

# TODO: Refactor to reduce complexity
Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 12

Metrics/MethodLength:
  Max: 15

Metrics/ParameterLists:
  Max: 15
  CountKeywordArgs: false
