AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - "ext/**"
    - "tmp/**/*"

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'

# Allow higher complexity in App#run method for now
# TODO: Refactor to reduce complexity
Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 12

Metrics/MethodLength:
  Max: 20

# OpenAPI config classes have many parameters by design
Metrics/ParameterLists:
  Max: 15
  CountKeywordArgs: false
