// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7f82b4aa5872fb93ca2202882dd9b4bb653b852da7a7dbf5ea7954b684d7ea89
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.spikard.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import com.fasterxml.jackson.module.kotlin.registerKotlinModule

/** E2e tests for category: websocket. */
class WebsocketTest {

    companion object {
        init {
            try {
                System.loadLibrary("spikard_jni")
            } catch (e: UnsatisfiedLinkError) {
                System.err.println("Failed to load spikard_jni library: ${e.message}")
                val libPath = System.getProperty("java.library.path")
                System.err.println("java.library.path: $libPath")
                throw e
            }
        }
        private val MAPPER = ObjectMapper().registerModule(Jdk8Module()).registerKotlinModule().setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
    }
    @Test
    fun testWsUpgradeHandshake() {
        // Tests WebSocket upgrade returns 101 Switching Protocols with correct Sec-WebSocket-Accept header
        org.junit.jupiter.api.Assumptions.assumeTrue(false, "Skipped: Java HttpClient cannot handle 101 Switching Protocols responses")
    }

}
