// DO NOT EDIT - auto-generated by alef
// alef:hash:f95c69151cf0cf0efe5dc46b8ca8f1ea721232b4ef265941e6ec9b46894dd78a
package dev.spikard;

/**
 * Error type for application builder operations.
 */
public class AppErrorException extends Exception {
  private static final long serialVersionUID = 1L;
  /** Creates a new AppErrorException with the given message. */
  public AppErrorException(final String message) { super(message); }

  /** Creates a new AppErrorException with the given message and cause. */
  public AppErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
