// DO NOT EDIT - auto-generated by alef
// alef:hash:0b192ef8e5ca341b49d82adccc7098b86714fc7213e06132bf210e17223a6f55
package dev.spikard;

/**
 * Authentication error
 *
 * Occurs when request authentication fails.
 */
public class AuthenticationErrorException extends GraphQLErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new AuthenticationErrorException with the given message. */
  public AuthenticationErrorException(final String message) {
    super(message);
  }

  /** Creates a new AuthenticationErrorException with the given message and cause. */
  public AuthenticationErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
