// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:40bcf4de7c94d052e9d9dd0aea2ddb3c22e3cd1ae7cb3863e0ea0a11df0392f8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.spikard;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

public record BackgroundJobMetadata(String name, @JsonProperty("request_id") Optional<String> requestId) {
    public static BackgroundJobMetadataBuilder builder() {
        return new BackgroundJobMetadataBuilder();
    }
}
