// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:08e924afb74595b3fe5a0715a97ae6cf943cd655682012ec4fc56ef72cfee677
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.spikard;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record BackgroundJobMetadata(
    String name,
    @Nullable @JsonProperty("request_id") String requestId
) {
    public static BackgroundJobMetadata defaultInstance() {
        throw new UnsupportedOperationException("defaultInstance is not yet bridged via JNI; use the Builder instead.");
    }
}
