// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:46df69cb013d9acb39a02e34534bc7e0647e7e5ece031da101883910bad834a2
// To regenerate: alef generate
// To verify freshness: alef verify
package dev.spikard;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;
import java.util.List;

/** Verified downloadable native-component management. */
public final class Components {
  private static final ObjectMapper MAPPER = new ObjectMapper();

  private Components() {}

  /** Downloads, verifies, loads, and pins a configured component. */
  public static void componentLoad(final String component)
      throws SpikardRsException {
    try (Arena arena = Arena.ofConfined()) {
      int result = (int)NativeLib.SPIKARD_COMPONENT_LOAD.invoke(
          arena.allocateFrom(component));
      if (result != 0) {
        throw nativeError("component load");
      }
    } catch (SpikardRsException error) {
      throw error;
    } catch (Throwable error) {
      throw new SpikardRsException("component load failed", error);
    }
  }

  /** Downloads and verifies every configured component. */
  public static List<String> componentPrefetch() throws SpikardRsException {
    return componentPrefetchInternal(MemorySegment.NULL);
  }

  /** Downloads and verifies one configured component. */
  public static List<String> componentPrefetch(final String component)
      throws SpikardRsException {
    try (Arena arena = Arena.ofConfined()) {
      return componentPrefetchInternal(arena.allocateFrom(component));
    }
  }

  /**
   * Returns ready, cached, not_downloaded, bundled, or
   * unsupported:&lt;reason&gt;.
   */
  public static String componentStatus(final String component)
      throws SpikardRsException {
    return callString(NativeLib.SPIKARD_COMPONENT_STATUS, component,
                      "component status");
  }

  /** Returns the content-addressed cache path for a configured component. */
  public static String componentCachePath(final String component)
      throws SpikardRsException {
    return callString(NativeLib.SPIKARD_COMPONENT_CACHE_PATH, component,
                      "component cache path");
  }

  private static List<String>
  componentPrefetchInternal(final MemorySegment component)
      throws SpikardRsException {
    try {
      MemorySegment result =
          (MemorySegment)NativeLib.SPIKARD_COMPONENT_PREFETCH.invoke(component);
      String json = takeString(result, "component prefetch");
      return MAPPER.readValue(json, new TypeReference<List<String>>() {});
    } catch (SpikardRsException error) {
      throw error;
    } catch (Throwable error) {
      throw new SpikardRsException("component prefetch failed", error);
    }
  }

  private static String callString(final MethodHandle method,
                                   final String component,
                                   final String operation)
      throws SpikardRsException {
    try (Arena arena = Arena.ofConfined()) {
      MemorySegment result =
          (MemorySegment)method.invoke(arena.allocateFrom(component));
      return takeString(result, operation);
    } catch (SpikardRsException error) {
      throw error;
    } catch (Throwable error) {
      throw new SpikardRsException(operation + " failed", error);
    }
  }

  private static String takeString(final MemorySegment result,
                                   final String operation) throws Throwable {
    if (result.equals(MemorySegment.NULL)) {
      throw nativeError(operation);
    }
    try {
      return result.reinterpret(Long.MAX_VALUE).getString(0);
    } finally {
      NativeLib.SPIKARD_FREE_STRING.invoke(result);
    }
  }

  private static SpikardRsException nativeError(final String operation)
      throws Throwable {
    int code = (int)NativeLib.SPIKARD_LAST_ERROR_CODE.invoke();
    MemorySegment context =
        (MemorySegment)NativeLib.SPIKARD_LAST_ERROR_CONTEXT.invoke();
    String message = context.equals(MemorySegment.NULL)
                         ? operation + " failed"
                         : context.reinterpret(Long.MAX_VALUE).getString(0);
    return new SpikardRsException(code, message);
  }
}
