// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9d871803d888378d6bd6b4890d1e6940bd6dbc1b9356a2b17b755ee50eb71976
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.spikard;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Contact information
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ContactInfo.Builder.class)
@SuppressWarnings("PMD")
public record ContactInfo(
    @Nullable @JsonProperty("name") String name,
    @Nullable @JsonProperty("email") String email,
    @Nullable @JsonProperty("url") String url) {
  public static Builder builder() {
    return new Builder();
  }

  // CPD-OFF
  @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
  public static final class Builder {

    private String name = null;
    private String email = null;
    private String url = null;

    /** Sets the name field. */
    @JsonProperty("name")
    public Builder withName(final @Nullable String value) {
      this.name = value;
      return this;
    }

    /** Sets the email field. */
    @JsonProperty("email")
    public Builder withEmail(final @Nullable String value) {
      this.email = value;
      return this;
    }

    /** Sets the url field. */
    @JsonProperty("url")
    public Builder withUrl(final @Nullable String value) {
      this.url = value;
      return this;
    }

    /** Builds the ContactInfo instance. */
    public ContactInfo build() {
      return new ContactInfo(name, email, url);
    }
  }
  // CPD-ON
}
