// DO NOT EDIT - auto-generated by alef
// alef:hash:fdad3957aca9c770729ae3f8a2bf85ea9b75453417e5d37b935eb57d7efa235d
package dev.spikard;

/**
 * Failed to extract DTO from the request context.
 */
public class DecodeException extends AppErrorException {
    /** Creates a new DecodeException with the given message. */
    public DecodeException(final String message) {
        super(message);
    }

    /** Creates a new DecodeException with the given message and cause. */
    public DecodeException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
