// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3fce4248d328727cbf68984ddea7f1a8c735c4150095b71890353b6b34f86c4c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.spikard;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Configuration for fully-featured schemas with Query, Mutation, and Subscription types
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record FullSchemaConfig(
    /**
     * Enable introspection queries
     */
    @JsonProperty("introspection_enabled") boolean introspectionEnabled,
    /**
     * Maximum query complexity (None = unlimited)
     */
    @Nullable @JsonProperty("complexity_limit") Long complexityLimit,
    /**
     * Maximum query depth (None = unlimited)
     */
    @Nullable @JsonProperty("depth_limit") Long depthLimit
) {
    public static FullSchemaConfig defaultInstance() {
        throw new UnsupportedOperationException("defaultInstance is not yet bridged via JNI; use the Builder instead.");
    }
}
