// DO NOT EDIT - auto-generated by alef
// alef:hash:21b3a5c2c0e3e2dafa5eac0ba17686d1a539091ca41a7ce18d3a007896d75bf0
package dev.spikard;

/**
 * GraphQL route registration failed (e.g. an unrecognized `schema_type`).
 */
public class GraphQLException extends AppErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new GraphQLException with the given message. */
    public GraphQLException(final String message) {
        super(message);
    }

    /** Creates a new GraphQLException with the given message and cause. */
    public GraphQLException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
