// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b9e55555870df5736d303ec25a2ec00c41ddd0d81fb4b2b8cb1219cd936697cc
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.spikard;

import java.lang.foreign.MemorySegment;

@SuppressWarnings("PMD")
public class HandlerResult implements AutoCloseable {
  private final MemorySegment handle;

  HandlerResult(MemorySegment handle) {
    this.handle = handle;
  }

  MemorySegment handle() {
    return this.handle;
  }

  @Override
  @SuppressWarnings("PMD.AvoidCatchingGenericException")
  public void close() {
    if (handle != null && !handle.equals(MemorySegment.NULL)) {
      try {
        NativeLib.SPIKARD_HANDLER_RESULT_FREE.invoke(handle);
      } catch (Throwable e) {
        throw new RuntimeException("Failed to free HandlerResult: " + e.getMessage(), e);
      }
    }
  }
}
