// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8e86cd7c02ed55d3d3adb1d493e3a259d54a3e6692730a15e8399773c49bef33
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.spikard;

import java.lang.foreign.MemorySegment;

@SuppressWarnings("PMD")
public class HandlerResult implements AutoCloseable {
  private final MemorySegment handle;

  HandlerResult(MemorySegment handle) {
    this.handle = handle;
  }

  MemorySegment handle() {
    return this.handle;
  }

  @Override
  @SuppressWarnings("PMD.AvoidCatchingGenericException")
  public void close() {
    if (handle != null && !handle.equals(MemorySegment.NULL)) {
      try {
        NativeLib.SPIKARD_HANDLER_RESULT_FREE.invoke(handle);
      } catch (Throwable e) {
        throw new RuntimeException("Failed to free HandlerResult: " + e.getMessage(), e);
      }
    }
  }
}
