// DO NOT EDIT - auto-generated by alef
// alef:hash:7cc2d07aa9e1432a9f9eef7566eb1ea0c34e82d7e2a009b8936a13901ffa280e
package dev.spikard;

/**
 * Internal server error
 *
 * Occurs when an unexpected internal error happens.
 */
public class InternalErrorException extends GraphQLErrorException {
  /** Creates a new InternalErrorException with the given message. */
  public InternalErrorException(final String message) {
    super(message);
  }

  /** Creates a new InternalErrorException with the given message and cause. */
  public InternalErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
