// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b5167d25336e3011d4daa9dcfbe6e9b01fdb7992536b9984a54b4650875c3ba2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.spikard;

/** Exception thrown when input validation fails. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class InvalidInputException extends SpikardRsException {
  private static final long serialVersionUID = 1L;

  /** Creates a new InvalidInputException. */
  public InvalidInputException(final String message) { super(1, message); }

  /** Creates a new InvalidInputException with a cause. */
  public InvalidInputException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
