// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6379227f1f9f7fa5f8665035fe88b22acaaa0566b7220e375dc39ccc0f9ce6d0
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.spikard;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * JWT authentication configuration
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = JwtConfig.Builder.class)
public record JwtConfig(
    /**
     * Secret key for JWT verification
     */
    @JsonProperty("secret") String secret,
    /**
     * Required algorithm (HS256, HS384, HS512, RS256, etc.)
     */
    @Nullable @JsonProperty("algorithm") String algorithm,
    /**
     * Required audience claim
     */
    @Nullable @JsonProperty("audience") List<String> audience,
    /**
     * Required issuer claim
     */
    @Nullable @JsonProperty("issuer") String issuer,
    /**
     * Leeway for expiration checks (seconds)
     */
    @Nullable @JsonProperty("leeway") Long leeway
) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

private String secret = "";
private String algorithm = null;
private List<String> audience = null;
private String issuer = null;
private Long leeway = null;

        /** Sets the secret field. */
        @JsonProperty("secret")
        public Builder withSecret(final String value) {
            this.secret = value;
            return this;
        }

        /** Sets the algorithm field. */
        @JsonProperty("algorithm")
        public Builder withAlgorithm(final @Nullable String value) {
            this.algorithm = value;
            return this;
        }

        /** Sets the audience field. */
        @JsonProperty("audience")
        public Builder withAudience(final @Nullable List<String> value) {
            this.audience = value;
            return this;
        }

        /** Sets the issuer field. */
        @JsonProperty("issuer")
        public Builder withIssuer(final @Nullable String value) {
            this.issuer = value;
            return this;
        }

        /** Sets the leeway field. */
        @JsonProperty("leeway")
        public Builder withLeeway(final @Nullable Long value) {
            this.leeway = value;
            return this;
        }

        /** Builds the JwtConfig instance. */
        public JwtConfig build() {
            return new JwtConfig(
                secret,
                algorithm,
                audience,
                issuer,
                leeway
            );
        }
    }
    // CPD-ON
}
