// DO NOT EDIT - auto-generated by alef
// alef:hash:bb216a5bd333306783e3eb7d042577ff84a8ceb4aefe9cc4dfa3995ed66d104b
package dev.spikard;

/**
 * Not found error
 *
 * Occurs when a requested resource is not found.
 */
public class NotFoundException extends GraphQLErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new NotFoundException with the given message. */
    public NotFoundException(final String message) {
        super(message);
    }

    /** Creates a new NotFoundException with the given message and cause. */
    public NotFoundException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
