// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:522db12d796bdc8a9d0fa4c5e205a4f7487df4b3f987a58dd797200301c49d95
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.spikard;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import java.util.List;

/**
 * Full parse result returned by {@code POST /asyncapi/parse}
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ParseResult.Builder.class)
@SuppressWarnings("PMD")
public record ParseResult(
    @JsonProperty("spec_version") String specVersion,
    @JsonProperty("title") String title,
    @JsonProperty("api_version") String apiVersion,
    @JsonProperty("channels") List<ParsedChannel> channels,
    @JsonProperty("operations") List<ParsedOperation> operations,
    @JsonProperty("messages") List<ParsedMessage> messages) {
  public static Builder builder() {
    return new Builder();
  }

  // CPD-OFF
  @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
  public static final class Builder {

    @JsonProperty("spec_version")
    private String specVersion = "";

    private String title = "";

    @JsonProperty("api_version")
    private String apiVersion = "";

    private List<ParsedChannel> channels = List.of();
    private List<ParsedOperation> operations = List.of();
    private List<ParsedMessage> messages = List.of();

    /** Sets the specVersion field. */
    @JsonProperty("spec_version")
    public Builder withSpecVersion(final String value) {
      this.specVersion = value;
      return this;
    }

    /** Sets the title field. */
    @JsonProperty("title")
    public Builder withTitle(final String value) {
      this.title = value;
      return this;
    }

    /** Sets the apiVersion field. */
    @JsonProperty("api_version")
    public Builder withApiVersion(final String value) {
      this.apiVersion = value;
      return this;
    }

    /** Sets the channels field. */
    @JsonProperty("channels")
    public Builder withChannels(final List<ParsedChannel> value) {
      this.channels = value;
      return this;
    }

    /** Sets the operations field. */
    @JsonProperty("operations")
    public Builder withOperations(final List<ParsedOperation> value) {
      this.operations = value;
      return this;
    }

    /** Sets the messages field. */
    @JsonProperty("messages")
    public Builder withMessages(final List<ParsedMessage> value) {
      this.messages = value;
      return this;
    }

    /** Builds the ParseResult instance. */
    public ParseResult build() {
      return new ParseResult(specVersion, title, apiVersion, channels, operations, messages);
    }
  }
  // CPD-ON
}
