// DO NOT EDIT - auto-generated by alef
// alef:hash:1e8c5c22e591b7048e2896e148a508bd5436f7e9ff8f45a19a0a538e30f6c689
package dev.spikard;

/**
 * GraphQL parse error
 *
 * Occurs when the GraphQL query string cannot be parsed.
 */
public class ParseErrorException extends GraphQLErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ParseErrorException with the given message. */
  public ParseErrorException(final String message) { super(message); }

  /** Creates a new ParseErrorException with the given message and cause. */
  public ParseErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
