// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3b4d35cf86c72e2f6e573c4000574cecea8e00eb523bd1db3e4933748a1ae277
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.spikard;

import java.util.Optional;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Configuration for schemas with only Query type
 */
@JsonPOJOBuilder(withPrefix = "with")
public class QueryOnlyConfigBuilder {

    @JsonProperty("introspection_enabled")
    private boolean introspectionEnabled = true;
    @JsonProperty("complexity_limit")
    private Optional<Long> complexityLimit = Optional.empty();
    @JsonProperty("depth_limit")
    private Optional<Long> depthLimit = Optional.empty();

    /** Sets the introspectionEnabled field. */
    @JsonProperty("introspection_enabled")
    public QueryOnlyConfigBuilder withIntrospectionEnabled(final boolean value) {
        this.introspectionEnabled = value;
        return this;
    }

    /** Sets the complexityLimit field. */
    @JsonProperty("complexity_limit")
    public QueryOnlyConfigBuilder withComplexityLimit(final Optional<Long> value) {
        this.complexityLimit = value;
        return this;
    }

    /** Sets the depthLimit field. */
    @JsonProperty("depth_limit")
    public QueryOnlyConfigBuilder withDepthLimit(final Optional<Long> value) {
        this.depthLimit = value;
        return this;
    }

    /** Builds the QueryOnlyConfig instance. */
    public QueryOnlyConfig build() {
        return new QueryOnlyConfig(
            introspectionEnabled,
            complexityLimit.orElse(null),
            depthLimit.orElse(null)
        );
    }
}
