// DO NOT EDIT - auto-generated by alef
// alef:hash:e0d1fa10e160246309f8a258b5ab03668d066e83bc4b81e9b7679fda0d6de229
package dev.spikard;

/**
 * Rate limit error
 *
 * Occurs when rate limit is exceeded.
 */
public class RateLimitExceededException extends GraphQLErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new RateLimitExceededException with the given message. */
  public RateLimitExceededException(final String message) { super(message); }

  /**
   * Creates a new RateLimitExceededException with the given message and cause.
   */
  public RateLimitExceededException(final String message,
                                    final Throwable cause) {
    super(message, cause);
  }
}
