// DO NOT EDIT - auto-generated by alef
// alef:hash:d63f032adc2f1af41d3929dbd77c93a1c563240b88124e4d5919db130260b99d
package dev.spikard;

/**
 * Error during request handling
 *
 * Occurs when the HTTP request cannot be properly handled or parsed.
 */
public class RequestHandlingErrorException extends GraphQLErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new RequestHandlingErrorException with the given message. */
  public RequestHandlingErrorException(final String message) { super(message); }

  /**
   * Creates a new RequestHandlingErrorException with the given message and
   * cause.
   */
  public RequestHandlingErrorException(final String message,
                                       final Throwable cause) {
    super(message, cause);
  }

  /**
   * Creates a new RequestHandlingErrorException with the given message and the
   * native error's introspection values.
   */
  public RequestHandlingErrorException(final String message,
                                       final int statusCode,
                                       final boolean isTransientFlag,
                                       final String errorType) {
    super(message, statusCode, isTransientFlag, errorType);
  }
}
