// DO NOT EDIT - auto-generated by alef
// alef:hash:c3a14e536ee74c3980a67a9e0a903020c03caf1c8d48a05d4dac2ea7030fdf81
package dev.spikard;

/**
 * Error during request handling
 *
 * Occurs when the HTTP request cannot be properly handled or parsed.
 */
public class RequestHandlingErrorException extends GraphQLErrorException {
  /** Creates a new RequestHandlingErrorException with the given message. */
  public RequestHandlingErrorException(final String message) {
    super(message);
  }

  /** Creates a new RequestHandlingErrorException with the given message and cause. */
  public RequestHandlingErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
