// DO NOT EDIT - auto-generated by alef
// alef:hash:c3f0f5517746246d50874cb2a9cdd8b3ffda9c41a245096399f1f72552b53ac5
package dev.spikard;

/**
 * Error during request handling
 *
 * Occurs when the HTTP request cannot be properly handled or parsed.
 */
public class RequestHandlingErrorException extends GraphQLErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new RequestHandlingErrorException with the given message. */
  public RequestHandlingErrorException(final String message) { super(message); }

  /**
   * Creates a new RequestHandlingErrorException with the given message and
   * cause.
   */
  public RequestHandlingErrorException(final String message,
                                       final Throwable cause) {
    super(message, cause);
  }
}
