// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fdad3957aca9c770729ae3f8a2bf85ea9b75453417e5d37b935eb57d7efa235d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.spikard;

import java.lang.foreign.MemorySegment;

public class RequestData implements AutoCloseable {
    private final MemorySegment handle;

    RequestData(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }

    @Override
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.SPIKARD_REQUEST_DATA_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free RequestData: " + e.getMessage(), e);
            }
        }
    }
}
