// DO NOT EDIT - auto-generated by alef
// alef:hash:d3901ccd0562d670c46890c6dfba29ddcc523dd04f549dd746fe451e2d4f19c5
package dev.spikard;

/**
 * Route registration failed.
 */
public class RouteException extends AppErrorException {
  /** Creates a new RouteException with the given message. */
  public RouteException(final String message) {
    super(message);
  }

  /** Creates a new RouteException with the given message and cause. */
  public RouteException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
