// DO NOT EDIT - auto-generated by alef
// alef:hash:b8b369dfc79dfacd0d9771fbe3d352bdb78c32e5250af81afc44f0cbe8d283bc
package dev.spikard;

/**
 * Route registration failed.
 */
public class RouteException extends AppErrorException {
    /** Creates a new RouteException with the given message. */
    public RouteException(final String message) {
        super(message);
    }

    /** Creates a new RouteException with the given message and cause. */
    public RouteException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
