// DO NOT EDIT - auto-generated by alef
// alef:hash:2d7dbf81c707f179a8f3e779c4f3753ba5e68c5eb1f3903e5c5895387dd5956c
package dev.spikard;

/**
 * Error during schema building
 *
 * Occurs when schema construction fails due to invalid definitions or conflicts.
 */
public class SchemaBuildErrorException extends GraphQLErrorException {
    /** Creates a new SchemaBuildErrorException with the given message. */
    public SchemaBuildErrorException(final String message) {
        super(message);
    }

    /** Creates a new SchemaBuildErrorException with the given message and cause. */
    public SchemaBuildErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
