// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:eb9c7b97390fdc1ff93990b5eabc89326793eec840edf6e2f9e74fe0ec2e432d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.spikard;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Configuration for GraphQL schema building.
 *
 * Encapsulates all schema-level configuration options including introspection control, complexity limits, and depth
 * limits.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record SchemaConfig(
        /** Enable introspection queries */
        @JsonProperty("introspection_enabled") boolean introspectionEnabled,
        /** Maximum query complexity (None = unlimited) */
        @JsonProperty("complexity_limit") Optional<Long> complexityLimit, /** Maximum query depth (None = unlimited) */
        @JsonProperty("depth_limit") Optional<Long> depthLimit) {
    public static SchemaConfigBuilder builder() {
        return new SchemaConfigBuilder();
    }
}
