// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d96e25dc3b5d482dfba084d8abb65ab872dd519c804c3eb24c57c93e7bebcfab
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.spikard;

import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Configuration for GraphQL schema building.
 *
 * Encapsulates all schema-level configuration options including introspection control, complexity limits, and depth
 * limits.
 */
public record SchemaConfig(
        /** Enable introspection queries */
        @JsonProperty("introspection_enabled") boolean introspectionEnabled,
        /** Maximum query complexity (None = unlimited) */
        @JsonProperty("complexity_limit") Optional<Long> complexityLimit, /** Maximum query depth (None = unlimited) */
        @JsonProperty("depth_limit") Optional<Long> depthLimit) {
    public static SchemaConfigBuilder builder() {
        return new SchemaConfigBuilder();
    }
}
