// DO NOT EDIT - auto-generated by alef
// alef:hash:0fdebc102fb44f9e2c6b2c86d89a5f7b4b0813772118b76816bed4084da3cd76
package dev.spikard;

/**
 * Error during schema building
 *
 * Occurs when schema construction fails due to invalid definitions or conflicts.
 */
public class SchemaBuildErrorException extends GraphQLErrorException {
  /** Creates a new SchemaBuildErrorException with the given message. */
  public SchemaBuildErrorException(final String message) {
    super(message);
  }

  /** Creates a new SchemaBuildErrorException with the given message and cause. */
  public SchemaBuildErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
