// DO NOT EDIT - auto-generated by alef
// alef:hash:b0da2ef06c3ae573b1a115ebd7ad10695a9ecd17be4f71601298e29a6aca9320
package dev.spikard;

/**
 * Serialization error
 *
 * Occurs during JSON serialization/deserialization of GraphQL values.
 */
public class SerializationErrorException extends GraphQLErrorException {
    /** Creates a new SerializationErrorException with the given message. */
    public SerializationErrorException(final String message) {
        super(message);
    }

    /** Creates a new SerializationErrorException with the given message and cause. */
    public SerializationErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
