// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5cda43db8f64def53c461be782227b0c2751e8ca01fcd213209ceb6324872e09
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.spikard;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Server information
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ServerInfo.Builder.class)
@SuppressWarnings("PMD")
public record ServerInfo(
    @JsonProperty("url") String url,
    @Nullable @JsonProperty("description") String description) {
  public static Builder builder() {
    return new Builder();
  }

  // CPD-OFF
  @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
  @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
  public static final class Builder {

    private String url = "";
    private String description = null;

    /** Sets the url field. */
    @JsonProperty("url")
    public Builder withUrl(final String value) {
      this.url = value;
      return this;
    }

    /** Sets the description field. */
    @JsonProperty("description")
    public Builder withDescription(final @Nullable String value) {
      this.description = value;
      return this;
    }

    /** Builds the ServerInfo instance. */
    public ServerInfo build() {
      return new ServerInfo(url, description);
    }
  }
  // CPD-ON
}
