// DO NOT EDIT - auto-generated by alef
// alef:hash:1e8c5c22e591b7048e2896e148a508bd5436f7e9ff8f45a19a0a538e30f6c689
package dev.spikard;

/**
 * Server/router construction failed.
 */
public class ServerException extends AppErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ServerException with the given message. */
  public ServerException(final String message) { super(message); }

  /** Creates a new ServerException with the given message and cause. */
  public ServerException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
