// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ab2e05161504bdc7f2905a5192e98aa5196a0c96081a9c7ff09d88b33dfd9d45
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.spikard;

/** Exception thrown by SpikardRs. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class SpikardRsException extends Exception {
  /** The error code. */
  private final int code;

  /** Creates a new SpikardRsException. */
  public SpikardRsException(final int code, final String message) {
    super(message);
    this.code = code;
  }

  /** Creates a new SpikardRsException with a cause. */
  public SpikardRsException(final String message, final Throwable cause) {
    super(message, cause);
    this.code = -1;
  }

  /** Returns the error code. */
  public int getCode() {
    return code;
  }
}
