// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bacc7a45002bfd0392d1112dd9b076bb2219a2a5dfe05b31716acf3a21f9d347
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.spikard;

/** Exception thrown by SpikardRs. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class SpikardRsException extends Exception {
  /** The error code. */
  private final int code;

  /** Creates a new SpikardRsException. */
  public SpikardRsException(final int code, final String message) {
    super(message);
    this.code = code;
  }

  /** Creates a new SpikardRsException with a cause. */
  public SpikardRsException(final String message, final Throwable cause) {
    super(message, cause);
    this.code = -1;
  }

  /** Returns the error code. */
  public int getCode() {
    return code;
  }
}
