// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:56dc4b179c375dda7ab50c6262ee6db7f3223b46a58eef1b90472f38ffbf5f80
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.spikard;

/** Exception thrown by SpikardRs. */
@SuppressWarnings("checkstyle:LineLength")
public class SpikardRsException extends Exception {
    /** The error code. */
    private final int code;

    /** Creates a new SpikardRsException. */
    public SpikardRsException(final int code, final String message) {
        super(message);
        this.code = code;
    }

    /** Creates a new SpikardRsException with a cause. */
    public SpikardRsException(final String message, final Throwable cause) {
        super(message, cause);
        this.code = -1;
    }

    /** Returns the error code. */
    public int getCode() {
        return code;
    }
}
