// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:70d6afb04d5fecb0ab2f4ebe104a87ee02bf617fd393e24a5daaaa0b5ba34da1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.spikard;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Static file serving configuration
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = StaticFilesConfig.Builder.class)
@SuppressWarnings("PMD")
public record StaticFilesConfig(
    @JsonProperty("directory") String directory,
    @JsonProperty("route_prefix") String routePrefix,
    @Nullable @JsonProperty("index_file") Boolean indexFile,
    @Nullable @JsonProperty("cache_control") String cacheControl) {
  public static Builder builder() {
    return new Builder();
  }

  // CPD-OFF
  @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
  public static final class Builder {

    private String directory = "";

    @JsonProperty("route_prefix")
    private String routePrefix = "";

    @JsonProperty("index_file")
    private Boolean indexFile = null;

    @JsonProperty("cache_control")
    private String cacheControl = null;

    /** Sets the directory field. */
    @JsonProperty("directory")
    public Builder withDirectory(final String value) {
      this.directory = value;
      return this;
    }

    /** Sets the routePrefix field. */
    @JsonProperty("route_prefix")
    public Builder withRoutePrefix(final String value) {
      this.routePrefix = value;
      return this;
    }

    /** Sets the indexFile field. */
    @JsonProperty("index_file")
    public Builder withIndexFile(final @Nullable Boolean value) {
      this.indexFile = value;
      return this;
    }

    /** Sets the cacheControl field. */
    @JsonProperty("cache_control")
    public Builder withCacheControl(final @Nullable String value) {
      this.cacheControl = value;
      return this;
    }

    /** Builds the StaticFilesConfig instance. */
    public StaticFilesConfig build() {
      return new StaticFilesConfig(directory, routePrefix, indexFile, cacheControl);
    }
  }
  // CPD-ON
}
