// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a0d25d45224025f60feb1c7d73a0a4e01cc139c4ae9b91556c0780940980b3db
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.spikard;

/**
 * Request body for {@code POST /asyncapi/validate}
 */
public record ValidateRequest(Object spec, String channel, String message, Object payload) {
}
