// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:840bae09dcb46caf379a897f50754982dc7c229c7b4eadebdfaacb9f53776265
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.spikard;

import com.fasterxml.jackson.annotation.JsonInclude;
import java.util.List;

/**
 * Response body for {@code POST /asyncapi/validate}
 */
public record ValidationResponse(
    boolean valid,
    @JsonInclude(JsonInclude.Include.NON_NULL) List<String> errors) {}
