// DO NOT EDIT - auto-generated by alef
// alef:hash:ad15871feeee436c4d6834226cb6d4c1028dda187fafff80e82d5a3a35515de9
package dev.spikard;

/**
 * GraphQL validation error
 *
 * Occurs when a GraphQL query fails schema validation.
 */
public class ValidationErrorException extends GraphQLErrorException {
  /** Creates a new ValidationErrorException with the given message. */
  public ValidationErrorException(final String message) {
    super(message);
  }

  /** Creates a new ValidationErrorException with the given message and cause. */
  public ValidationErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
