#!/usr/bin/env bash
# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ff661085f2552438300d3602c96320234ed4598748050b75209b591afdcf32ec
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: websocket
set -euo pipefail

test_ws_upgrade_handshake() {
  # Tests WebSocket upgrade returns 101 Switching Protocols with correct Sec-WebSocket-Accept header
    >/dev/null

}

run_tests_websocket() {
  run_test test_ws_upgrade_handshake
}
