#!/usr/bin/env bash
# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b0da2ef06c3ae573b1a115ebd7ad10695a9ecd17be4f71601298e29a6aca9320
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: body_limits
set -euo pipefail

test_body_over_limit_returns_413() {
  # Requests that exceed the configured max body size should be rejected with Payload Too Large.
    >/dev/null

}

test_body_under_limit_succeeds() {
  # Ensures requests smaller than the configured body limit are accepted.
    >/dev/null

}

run_tests_body_limits() {
  run_test test_body_over_limit_returns_413
  run_test test_body_under_limit_succeeds
}
