//! Spikard-Ruby code generator
//!
//! Generates Ruby code using Spikard bindings

use crate::analyzer::{RouteAnalysis, RouteInfo};
use anyhow::Result;

pub fn generate(analysis: &RouteAnalysis) -> Result<String> {
    let mut output = String::new();

    // Generate header
    output.push_str(&generate_header());

    // Create app
    output.push_str("app = Spikard.new\n\n");

    // Generate handler functions
    for route in &analysis.routes {
        output.push_str(&generate_handler(route));
        output.push_str("\n\n");
    }

    // Generate main
    output.push_str(&generate_main());

    Ok(output)
}

fn generate_header() -> String {
    r#"#!/usr/bin/env ruby
# frozen_string_literal: true

# Auto-generated Spikard-Ruby benchmark server
#
# DO NOT EDIT - Generated by app-generator

require 'spikard'

"#
    .to_string()
}

fn generate_handler(route: &RouteInfo) -> String {
    let method = route.method.to_lowercase();
    let params = generate_parameters(route);
    let body = generate_handler_body(route);

    format!(
        r#"app.{} '{}' do{}
  response = {{}}
  {}
  response
end"#,
        method, route.route, params, body
    )
}

fn generate_parameters(route: &RouteInfo) -> String {
    let mut params = Vec::new();

    // Check what we need
    let has_path = !route.params.path.is_empty();
    let has_query = !route.params.query.is_empty();
    let has_body = route.params.body.is_some();

    if has_path {
        params.push("params");
    }
    if has_query {
        params.push("query");
    }
    if has_body {
        params.push("body");
    }

    if params.is_empty() {
        String::new()
    } else {
        format!(" |{}|", params.join(", "))
    }
}

fn generate_handler_body(route: &RouteInfo) -> String {
    let mut lines = Vec::new();

    // Add path params to response
    for (name, _) in &route.params.path {
        lines.push(format!("response[:{}] = params[:{}]", name, name));
    }

    // Add query params to response
    for (name, _) in &route.params.query {
        lines.push(format!("response[:{}] = query[:{}] if query[:{}]", name, name, name));
    }

    // Return body if present
    if route.params.body.is_some() {
        lines.push("response.merge!(body) if body".to_string());
    }

    lines.join("\n  ")
}

fn generate_main() -> String {
    r#"port = (ARGV[0] || 8000).to_i

$stderr.puts "Starting Spikard-Ruby server on port #{port}"
app.run!(host: '0.0.0.0', port: port)
"#
    .to_string()
}
