// Generated by alef. Do not edit by hand.
// alef:hash:39a1074d8b60814e692f63fa3a25d2000da3e19d7e6c1d39dd6bba8ad657fb6e
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package dev.spikard

/** Full parse result returned by `POST /asyncapi/parse` */
data class ParseResult(
    val specVersion: String,
    val title: String,
    val apiVersion: String,
    val channels: List<ParsedChannel> = emptyList(),
    val operations: List<ParsedOperation> = emptyList(),
    val messages: List<ParsedMessage> = emptyList(),
)
