# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:21b3a5c2c0e3e2dafa5eac0ba17686d1a539091ca41a7ce18d3a007896d75bf0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require_relative "spikard/version"
require_relative "spikard/native"

# Top-level namespace for the Spikard Ruby binding.
#
# All type and function symbols are re-exported from the native extension
# loaded via `require_relative "spikard/native"`. See
# {file:README.md} for usage examples and the upstream documentation
# for the full API reference.
module Spikard
  # Re-export all types and functions from native extension
  require_relative "spikard/service"
end

# Bring top-level Spikard classes into the global namespace so callers
# (and the generated e2e suite) can reference them unqualified. The native
# extension has already been required above, so every type constant is defined
# under Spikard by this point.
Spikard.constants.each do |const_name|
  value = Spikard.const_get(const_name)
  ::Object.const_set(const_name, value) if value.is_a?(Module) && !::Object.const_defined?(const_name)
end

require_relative "spikard/app"
require_relative "spikard/params"
require_relative "spikard/introspection"
