// Generated by alef. Do not edit by hand.
// alef:hash:5cda43db8f64def53c461be782227b0c2751e8ca01fcd213209ceb6324872e09

export 'spikard_bridge_generated/lib.dart';
export 'traits.dart';
import 'spikard_bridge_generated/lib.dart' as rust_bridge;
// ignore: duplicate_import
import 'spikard_bridge_generated/lib.dart';

class SpikardBridge {
  /// Create a simple schema configuration with only Query type.
  ///
  /// This is a convenience function for schemas that only have queries.
  ///
  /// # Returns
  ///
  /// A `QueryOnlyConfig` with default settings
  static Future<QueryOnlyConfig> schemaQueryOnly() async {
    return await rust_bridge.schemaQueryOnly();
  }

  /// Create a schema configuration with Query and Mutation types.
  ///
  /// This is a convenience function for schemas with queries and mutations but no subscriptions.
  ///
  /// # Returns
  ///
  /// A `QueryMutationConfig` with default settings
  static Future<QueryMutationConfig> schemaQueryMutation() async {
    return await rust_bridge.schemaQueryMutation();
  }

  /// Create a schema configuration with all three root types.
  ///
  /// This is a convenience function for fully-featured schemas.
  ///
  /// # Returns
  ///
  /// A `FullSchemaConfig` with default settings
  static Future<FullSchemaConfig> schemaFull() async {
    return await rust_bridge.schemaFull();
  }
}
