// Generated by alef. Do not edit by hand.
// alef:hash:2a5a90b766eca1206c1cbd4e3f5c8797895d4a5a3411c48af1270b3074c9ed23

// Traits module (empty in Dart as Dart does not have trait systems like Rust).
// This file is kept for API surface consistency across language bindings.
