# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:33fcf05e26469adb9b1de758549c59505248573f85c08bcb48ca47b3428688dd
# To regenerate: alef generate
# To verify freshness: alef verify

"""E2e tests for category: jsonrpc."""

import json
import os
import urllib.request

import pytest


def test_jsonrpc_batch_request() -> None:
    """Tests JSON-RPC batch request with multiple calls."""
    base = os.environ.get("SUT_URL", "http://127.0.0.1:8000")
    url = f"{base}/fixtures/jsonrpc_batch_request/rpc"
    _headers = {
        "Content-Type": "application/json",
    }
    _headers.setdefault("Content-Type", "application/json")
    _body = json.dumps(
        [
            {"id": 1, "jsonrpc": "2.0", "method": "add", "params": [1, 2]},
            {"id": 2, "jsonrpc": "2.0", "method": "subtract", "params": [5, 3]},
        ]
    ).encode()
    _req = urllib.request.Request(url, data=_body, headers=_headers, method="POST")  # noqa: S310

    class _NoRedirect(urllib.request.HTTPRedirectHandler):
        def redirect_request(self, *args, **kwargs):  # noqa: ANN002, ANN003, ANN202, ARG002
            return None

    _opener = urllib.request.build_opener(_NoRedirect())
    try:
        response = _opener.open(_req)
        status_code = response.status
        resp_body = response.read()
        resp_headers = dict(response.headers)
    except urllib.error.HTTPError as _exc:
        status_code = _exc.code
        resp_body = _exc.read()
        resp_headers = dict(_exc.headers)  # noqa: F841
    assert status_code == 200
    data = json.loads(resp_body)
    assert data == [{"id": 1, "jsonrpc": "2.0", "result": 3}, {"id": 2, "jsonrpc": "2.0", "result": 2}]


def test_jsonrpc_call_with_positional_params() -> None:
    """Tests JSON-RPC call with positional array parameters."""
    base = os.environ.get("SUT_URL", "http://127.0.0.1:8000")
    url = f"{base}/fixtures/jsonrpc_call_with_positional_params/rpc"
    _headers = {
        "Content-Type": "application/json",
    }
    _headers.setdefault("Content-Type", "application/json")
    _body = json.dumps({"id": 2, "jsonrpc": "2.0", "method": "multiply", "params": [4, 7]}).encode()
    _req = urllib.request.Request(url, data=_body, headers=_headers, method="POST")  # noqa: S310

    class _NoRedirect(urllib.request.HTTPRedirectHandler):
        def redirect_request(self, *args, **kwargs):  # noqa: ANN002, ANN003, ANN202, ARG002
            return None

    _opener = urllib.request.build_opener(_NoRedirect())
    try:
        response = _opener.open(_req)
        status_code = response.status
        resp_body = response.read()
        resp_headers = dict(response.headers)
    except urllib.error.HTTPError as _exc:
        status_code = _exc.code
        resp_body = _exc.read()
        resp_headers = dict(_exc.headers)  # noqa: F841
    assert status_code == 200
    data = json.loads(resp_body)
    assert data == {"id": 2, "jsonrpc": "2.0", "result": 28}


def test_jsonrpc_config_batch_disabled() -> None:
    """Tests JSON-RPC batch requests disabled returns error."""
    base = os.environ.get("SUT_URL", "http://127.0.0.1:8000")
    url = f"{base}/fixtures/jsonrpc_config_batch_disabled/rpc"
    _headers = {
        "Content-Type": "application/json",
    }
    _headers.setdefault("Content-Type", "application/json")
    _body = json.dumps(
        [
            {"id": 1, "jsonrpc": "2.0", "method": "add", "params": [1, 2]},
            {"id": 2, "jsonrpc": "2.0", "method": "subtract", "params": [5, 3]},
        ]
    ).encode()
    _req = urllib.request.Request(url, data=_body, headers=_headers, method="POST")  # noqa: S310

    class _NoRedirect(urllib.request.HTTPRedirectHandler):
        def redirect_request(self, *args, **kwargs):  # noqa: ANN002, ANN003, ANN202, ARG002
            return None

    _opener = urllib.request.build_opener(_NoRedirect())
    try:
        response = _opener.open(_req)
        status_code = response.status
        resp_body = response.read()
        resp_headers = dict(response.headers)
    except urllib.error.HTTPError as _exc:
        status_code = _exc.code
        resp_body = _exc.read()
        resp_headers = dict(_exc.headers)  # noqa: F841
    assert status_code == 400
    data = json.loads(resp_body)
    assert data == {"error": {"code": -32600, "message": "Batch requests not enabled"}, "jsonrpc": "2.0"}


def test_jsonrpc_config_custom_endpoint_path() -> None:
    """Tests JSON-RPC server at custom endpoint path."""
    base = os.environ.get("SUT_URL", "http://127.0.0.1:8000")
    url = f"{base}/fixtures/jsonrpc_config_custom_endpoint_path/api/rpc"
    _headers = {
        "Content-Type": "application/json",
    }
    _headers.setdefault("Content-Type", "application/json")
    _body = json.dumps({"id": 1, "jsonrpc": "2.0", "method": "test", "params": {}}).encode()
    _req = urllib.request.Request(url, data=_body, headers=_headers, method="POST")  # noqa: S310

    class _NoRedirect(urllib.request.HTTPRedirectHandler):
        def redirect_request(self, *args, **kwargs):  # noqa: ANN002, ANN003, ANN202, ARG002
            return None

    _opener = urllib.request.build_opener(_NoRedirect())
    try:
        response = _opener.open(_req)
        status_code = response.status
        resp_body = response.read()
        resp_headers = dict(response.headers)
    except urllib.error.HTTPError as _exc:
        status_code = _exc.code
        resp_body = _exc.read()
        resp_headers = dict(_exc.headers)  # noqa: F841
    assert status_code == 200
    data = json.loads(resp_body)
    assert data == {"id": 1, "jsonrpc": "2.0", "result": "ok"}


def test_jsonrpc_config_max_batch_size() -> None:
    """Tests JSON-RPC batch request respects maximum batch size."""
    base = os.environ.get("SUT_URL", "http://127.0.0.1:8000")
    url = f"{base}/fixtures/jsonrpc_config_max_batch_size/rpc"
    _headers = {
        "Content-Type": "application/json",
    }
    _headers.setdefault("Content-Type", "application/json")
    _body = json.dumps(
        [
            {"id": 1, "jsonrpc": "2.0", "method": "method1"},
            {"id": 2, "jsonrpc": "2.0", "method": "method2"},
            {"id": 3, "jsonrpc": "2.0", "method": "method3"},
        ]
    ).encode()
    _req = urllib.request.Request(url, data=_body, headers=_headers, method="POST")  # noqa: S310

    class _NoRedirect(urllib.request.HTTPRedirectHandler):
        def redirect_request(self, *args, **kwargs):  # noqa: ANN002, ANN003, ANN202, ARG002
            return None

    _opener = urllib.request.build_opener(_NoRedirect())
    try:
        response = _opener.open(_req)
        status_code = response.status
        resp_body = response.read()
        resp_headers = dict(response.headers)
    except urllib.error.HTTPError as _exc:
        status_code = _exc.code
        resp_body = _exc.read()
        resp_headers = dict(_exc.headers)  # noqa: F841
    assert status_code == 200
    data = json.loads(resp_body)
    assert data == [
        {"id": 1, "jsonrpc": "2.0", "result": "result1"},
        {"id": 2, "jsonrpc": "2.0", "result": "result2"},
        {"id": 3, "jsonrpc": "2.0", "result": "result3"},
    ]


def test_jsonrpc_deprecated_method_flag() -> None:
    """Tests JSON-RPC method marked as deprecated."""
    base = os.environ.get("SUT_URL", "http://127.0.0.1:8000")
    url = f"{base}/fixtures/jsonrpc_deprecated_method_flag/rpc"
    _headers = {
        "Content-Type": "application/json",
    }
    _headers.setdefault("Content-Type", "application/json")
    _body = json.dumps({"id": 1, "jsonrpc": "2.0", "method": "oldMethod", "params": {}}).encode()
    _req = urllib.request.Request(url, data=_body, headers=_headers, method="POST")  # noqa: S310

    class _NoRedirect(urllib.request.HTTPRedirectHandler):
        def redirect_request(self, *args, **kwargs):  # noqa: ANN002, ANN003, ANN202, ARG002
            return None

    _opener = urllib.request.build_opener(_NoRedirect())
    try:
        response = _opener.open(_req)
        status_code = response.status
        resp_body = response.read()
        resp_headers = dict(response.headers)
    except urllib.error.HTTPError as _exc:
        status_code = _exc.code
        resp_body = _exc.read()
        resp_headers = dict(_exc.headers)
    assert status_code == 200
    data = json.loads(resp_body)
    assert data == {"id": 1, "jsonrpc": "2.0", "result": "deprecated"}
    assert resp_headers["deprecation"] == "true"
    assert "sunset" in resp_headers


def test_jsonrpc_error_response() -> None:
    """Tests JSON-RPC error response with error object."""
    base = os.environ.get("SUT_URL", "http://127.0.0.1:8000")
    url = f"{base}/fixtures/jsonrpc_error_response/rpc"
    _headers = {
        "Content-Type": "application/json",
    }
    _headers.setdefault("Content-Type", "application/json")
    _body = json.dumps(
        {"id": 3, "jsonrpc": "2.0", "method": "divide", "params": {"denominator": 0, "numerator": 10}}
    ).encode()
    _req = urllib.request.Request(url, data=_body, headers=_headers, method="POST")  # noqa: S310

    class _NoRedirect(urllib.request.HTTPRedirectHandler):
        def redirect_request(self, *args, **kwargs):  # noqa: ANN002, ANN003, ANN202, ARG002
            return None

    _opener = urllib.request.build_opener(_NoRedirect())
    try:
        response = _opener.open(_req)
        status_code = response.status
        resp_body = response.read()
        resp_headers = dict(response.headers)
    except urllib.error.HTTPError as _exc:
        status_code = _exc.code
        resp_body = _exc.read()
        resp_headers = dict(_exc.headers)  # noqa: F841
    assert status_code == 200
    data = json.loads(resp_body)
    assert data == {
        "error": {"code": -32600, "data": "Division by zero", "message": "Invalid Request"},
        "id": 3,
        "jsonrpc": "2.0",
    }


def test_jsonrpc_invalid_params() -> None:
    """Tests JSON-RPC error for invalid parameters."""
    base = os.environ.get("SUT_URL", "http://127.0.0.1:8000")
    url = f"{base}/fixtures/jsonrpc_invalid_params/rpc"
    _headers = {
        "Content-Type": "application/json",
    }
    _headers.setdefault("Content-Type", "application/json")
    _body = json.dumps({"id": 5, "jsonrpc": "2.0", "method": "subtract", "params": {"wrong_field": 42}}).encode()
    _req = urllib.request.Request(url, data=_body, headers=_headers, method="POST")  # noqa: S310

    class _NoRedirect(urllib.request.HTTPRedirectHandler):
        def redirect_request(self, *args, **kwargs):  # noqa: ANN002, ANN003, ANN202, ARG002
            return None

    _opener = urllib.request.build_opener(_NoRedirect())
    try:
        response = _opener.open(_req)
        status_code = response.status
        resp_body = response.read()
        resp_headers = dict(response.headers)
    except urllib.error.HTTPError as _exc:
        status_code = _exc.code
        resp_body = _exc.read()
        resp_headers = dict(_exc.headers)  # noqa: F841
    assert status_code == 200
    data = json.loads(resp_body)
    assert data == {"error": {"code": -32602, "message": "Invalid params"}, "id": 5, "jsonrpc": "2.0"}


def test_jsonrpc_method_not_found() -> None:
    """Tests JSON-RPC error when method does not exist."""
    base = os.environ.get("SUT_URL", "http://127.0.0.1:8000")
    url = f"{base}/fixtures/jsonrpc_method_not_found/rpc"
    _headers = {
        "Content-Type": "application/json",
    }
    _headers.setdefault("Content-Type", "application/json")
    _body = json.dumps({"id": 4, "jsonrpc": "2.0", "method": "nonexistent_method"}).encode()
    _req = urllib.request.Request(url, data=_body, headers=_headers, method="POST")  # noqa: S310

    class _NoRedirect(urllib.request.HTTPRedirectHandler):
        def redirect_request(self, *args, **kwargs):  # noqa: ANN002, ANN003, ANN202, ARG002
            return None

    _opener = urllib.request.build_opener(_NoRedirect())
    try:
        response = _opener.open(_req)
        status_code = response.status
        resp_body = response.read()
        resp_headers = dict(response.headers)
    except urllib.error.HTTPError as _exc:
        status_code = _exc.code
        resp_body = _exc.read()
        resp_headers = dict(_exc.headers)  # noqa: F841
    assert status_code == 200
    data = json.loads(resp_body)
    assert data == {"error": {"code": -32601, "message": "Method not found"}, "id": 4, "jsonrpc": "2.0"}


def test_jsonrpc_method_parameter_validation() -> None:
    """Tests JSON-RPC validates parameter types and values."""
    base = os.environ.get("SUT_URL", "http://127.0.0.1:8000")
    url = f"{base}/fixtures/jsonrpc_method_parameter_validation/rpc"
    _headers = {
        "Content-Type": "application/json",
    }
    _headers.setdefault("Content-Type", "application/json")
    _body = json.dumps(
        {
            "id": 6,
            "jsonrpc": "2.0",
            "method": "update_user",
            "params": {"email": "john@example.com", "id": 123, "name": "John Doe"},
        }
    ).encode()
    _req = urllib.request.Request(url, data=_body, headers=_headers, method="POST")  # noqa: S310

    class _NoRedirect(urllib.request.HTTPRedirectHandler):
        def redirect_request(self, *args, **kwargs):  # noqa: ANN002, ANN003, ANN202, ARG002
            return None

    _opener = urllib.request.build_opener(_NoRedirect())
    try:
        response = _opener.open(_req)
        status_code = response.status
        resp_body = response.read()
        resp_headers = dict(response.headers)
    except urllib.error.HTTPError as _exc:
        status_code = _exc.code
        resp_body = _exc.read()
        resp_headers = dict(_exc.headers)  # noqa: F841
    assert status_code == 200
    data = json.loads(resp_body)
    assert data == {
        "id": 6,
        "jsonrpc": "2.0",
        "result": {"email": "john@example.com", "id": 123, "name": "John Doe", "updated": True},
    }


def test_jsonrpc_method_with_params_schema() -> None:
    """Tests JSON-RPC method params validated against schema."""
    base = os.environ.get("SUT_URL", "http://127.0.0.1:8000")
    url = f"{base}/fixtures/jsonrpc_method_with_params_schema/rpc"
    _headers = {
        "Content-Type": "application/json",
    }
    _headers.setdefault("Content-Type", "application/json")
    _body = json.dumps(
        {"id": 1, "jsonrpc": "2.0", "method": "createUser", "params": {"age": 30, "name": "Alice"}}
    ).encode()
    _req = urllib.request.Request(url, data=_body, headers=_headers, method="POST")  # noqa: S310

    class _NoRedirect(urllib.request.HTTPRedirectHandler):
        def redirect_request(self, *args, **kwargs):  # noqa: ANN002, ANN003, ANN202, ARG002
            return None

    _opener = urllib.request.build_opener(_NoRedirect())
    try:
        response = _opener.open(_req)
        status_code = response.status
        resp_body = response.read()
        resp_headers = dict(response.headers)
    except urllib.error.HTTPError as _exc:
        status_code = _exc.code
        resp_body = _exc.read()
        resp_headers = dict(_exc.headers)  # noqa: F841
    assert status_code == 200
    data = json.loads(resp_body)
    assert data == {"id": 1, "jsonrpc": "2.0", "result": {"age": 30, "id": 1, "name": "Alice"}}


def test_jsonrpc_method_with_result_schema() -> None:
    """Tests JSON-RPC method result schema validation."""
    base = os.environ.get("SUT_URL", "http://127.0.0.1:8000")
    url = f"{base}/fixtures/jsonrpc_method_with_result_schema/rpc"
    _headers = {
        "Content-Type": "application/json",
    }
    _headers.setdefault("Content-Type", "application/json")
    _body = json.dumps({"id": 1, "jsonrpc": "2.0", "method": "getUser", "params": {"id": 1}}).encode()
    _req = urllib.request.Request(url, data=_body, headers=_headers, method="POST")  # noqa: S310

    class _NoRedirect(urllib.request.HTTPRedirectHandler):
        def redirect_request(self, *args, **kwargs):  # noqa: ANN002, ANN003, ANN202, ARG002
            return None

    _opener = urllib.request.build_opener(_NoRedirect())
    try:
        response = _opener.open(_req)
        status_code = response.status
        resp_body = response.read()
        resp_headers = dict(response.headers)
    except urllib.error.HTTPError as _exc:
        status_code = _exc.code
        resp_body = _exc.read()
        resp_headers = dict(_exc.headers)  # noqa: F841
    assert status_code == 200
    data = json.loads(resp_body)
    assert data == {"id": 1, "jsonrpc": "2.0", "result": {"email": "john@example.com", "id": 1, "name": "John"}}


def test_jsonrpc_notification_no_id() -> None:
    """Tests JSON-RPC notification (no response expected)."""
    base = os.environ.get("SUT_URL", "http://127.0.0.1:8000")
    url = f"{base}/fixtures/jsonrpc_notification_no_id/rpc"
    _headers = {
        "Content-Type": "application/json",
    }
    _headers.setdefault("Content-Type", "application/json")
    _body = json.dumps({"jsonrpc": "2.0", "method": "notify_event", "params": {"event": "user_login"}}).encode()
    _req = urllib.request.Request(url, data=_body, headers=_headers, method="POST")  # noqa: S310

    class _NoRedirect(urllib.request.HTTPRedirectHandler):
        def redirect_request(self, *args, **kwargs):  # noqa: ANN002, ANN003, ANN202, ARG002
            return None

    _opener = urllib.request.build_opener(_NoRedirect())
    try:
        response = _opener.open(_req)
        status_code = response.status
        resp_body = response.read()
        resp_headers = dict(response.headers)
    except urllib.error.HTTPError as _exc:
        status_code = _exc.code
        resp_body = _exc.read()  # noqa: F841
        resp_headers = dict(_exc.headers)  # noqa: F841
    assert status_code == 204


def test_jsonrpc_notification_no_response() -> None:
    """Tests JSON-RPC notification (no id) doesn't return response."""
    base = os.environ.get("SUT_URL", "http://127.0.0.1:8000")
    url = f"{base}/fixtures/jsonrpc_notification_no_response/rpc"
    _headers = {
        "Content-Type": "application/json",
    }
    _headers.setdefault("Content-Type", "application/json")
    _body = json.dumps({"jsonrpc": "2.0", "method": "notify", "params": {"message": "hello"}}).encode()
    _req = urllib.request.Request(url, data=_body, headers=_headers, method="POST")  # noqa: S310

    class _NoRedirect(urllib.request.HTTPRedirectHandler):
        def redirect_request(self, *args, **kwargs):  # noqa: ANN002, ANN003, ANN202, ARG002
            return None

    _opener = urllib.request.build_opener(_NoRedirect())
    try:
        response = _opener.open(_req)
        status_code = response.status
        resp_body = response.read()
        resp_headers = dict(response.headers)
    except urllib.error.HTTPError as _exc:
        status_code = _exc.code
        resp_body = _exc.read()
        resp_headers = dict(_exc.headers)  # noqa: F841
    assert status_code == 204
    assert resp_body.decode() == ""


def test_jsonrpc_single_call_success() -> None:
    """Tests single JSON-RPC 2.0 call with successful response."""
    base = os.environ.get("SUT_URL", "http://127.0.0.1:8000")
    url = f"{base}/fixtures/jsonrpc_single_call_success/rpc"
    _headers = {
        "Content-Type": "application/json",
    }
    _headers.setdefault("Content-Type", "application/json")
    _body = json.dumps({"id": 1, "jsonrpc": "2.0", "method": "add", "params": {"a": 5, "b": 3}}).encode()
    _req = urllib.request.Request(url, data=_body, headers=_headers, method="POST")  # noqa: S310

    class _NoRedirect(urllib.request.HTTPRedirectHandler):
        def redirect_request(self, *args, **kwargs):  # noqa: ANN002, ANN003, ANN202, ARG002
            return None

    _opener = urllib.request.build_opener(_NoRedirect())
    try:
        response = _opener.open(_req)
        status_code = response.status
        resp_body = response.read()
        resp_headers = dict(response.headers)
    except urllib.error.HTTPError as _exc:
        status_code = _exc.code
        resp_body = _exc.read()
        resp_headers = dict(_exc.headers)  # noqa: F841
    assert status_code == 200
    data = json.loads(resp_body)
    assert data == {"id": 1, "jsonrpc": "2.0", "result": 8}
