# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cf857583778b9d5bbe16fefe79335d73e515a83164b74450a664caec59e9f7e6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
"""Smoke test: import the published package."""

import importlib


def test_imports_published_package():
    module = importlib.import_module("spikard")
    assert module is not None
