// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b0d09fee2511d02bac5c85f0a995b0ab3cbf57f62697dc7616d171960a5eaf54
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package dev.spikard.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.spikard.Spikard;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
import org.junit.jupiter.api.BeforeAll;import org.junit.jupiter.api.AfterAll;
import java.io.IOException;
import java.net.Socket;
import java.net.URI;
import java.time.Instant;
/** E2e tests for category: lifecycle_hooks. */
public class LifecycleHooksTest {
    private static final ObjectMapper MAPPER = new ObjectMapper().registerModule(new Jdk8Module()).setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE);
    private static Process harnessProcess;
    private static String sutUrl;

    @BeforeAll
    static void startHarness() throws Exception {
        String preset = System.getenv("SUT_URL");
        if (preset != null && !preset.isEmpty()) {
            sutUrl = preset;
            return;
        }

        String javaHome = System.getProperty("java.home");
        ProcessBuilder pb = new ProcessBuilder(
            javaHome + "/bin/java",
            "-cp", System.getProperty("java.class.path"),
            "dev.spikard.e2e.HarnessMain"
        );
        // Inherit parent process environment so native library paths are available
        pb.environment().putAll(System.getenv());
        pb.redirectErrorStream(false);
        harnessProcess = pb.start();

        // Drain harness output in background (optional port discovery, but primarily
        // to prevent pipe blocking). The harness may emit HARNESS_PORT but stdout buffering
        // when piped often prevents timely delivery, so we don't rely on it — instead we
        // use a default port and TCP polling below.
        java.io.BufferedReader reader = new java.io.BufferedReader(
            new java.io.InputStreamReader(harnessProcess.getInputStream(), "UTF-8")
        );
        java.io.BufferedReader errReader = new java.io.BufferedReader(
            new java.io.InputStreamReader(harnessProcess.getErrorStream(), "UTF-8")
        );
        Thread stderrDrainer = new Thread(() -> {
            try {
                String errLine;
                while ((errLine = errReader.readLine()) != null) {
                    System.err.println("[Harness stderr] " + errLine);
                }
            } catch (java.io.IOException ignored) {}
        });
        stderrDrainer.setDaemon(true);
        stderrDrainer.start();
        Thread stdoutDrainer = new Thread(() -> {
            try {
                String outLine;
                while ((outLine = reader.readLine()) != null) {
                    // Optionally parse HARNESS_PORT if present, but don't rely on it
                    if (outLine.startsWith("HARNESS_PORT=")) {
                        System.out.println("[Harness port marker] " + outLine);
                    }
                }
            } catch (java.io.IOException ignored) {}
        });
        stdoutDrainer.setDaemon(true);
        stdoutDrainer.start();

        // Use the default harness port and TCP polling to verify reachability
        int harnessPort = 8000;
        String host = "127.0.0.1";
        int port = harnessPort;
        sutUrl = "http://" + host + ":" + port;

        // TCP-readiness probe: poll until the harness accepts connections on the configured port
        long deadline = System.currentTimeMillis() + 15_000;
        boolean ready = false;
        while (System.currentTimeMillis() < deadline) {
            if (harnessProcess.isAlive() == false) {
                break;
            }
            try (Socket socket = new Socket(host, port)) {
                ready = true;
                break;
            } catch (IOException e) {
                Thread.sleep(100);
            }
        }

        if (!ready) {
            if (harnessProcess != null) {
                harnessProcess.destroyForcibly();
            }
            throw new RuntimeException("Harness did not become reachable at " + sutUrl + " within 15s");
        }

        System.setProperty("SUT_URL", sutUrl);
    }

    @AfterAll
    static void stopHarness() throws Exception {
        if (harnessProcess != null && harnessProcess.isAlive()) {
            harnessProcess.destroy();
            if (!harnessProcess.waitFor(5, java.util.concurrent.TimeUnit.SECONDS)) {
                harnessProcess.destroyForcibly();
            }
        }
    }
    @Test    void testHookExecutionOrder() throws Exception {
        // Test that multiple hooks of the same type execute in registration order
        String baseUrl = System.getenv("SUT_URL");
        if (baseUrl == null) baseUrl = "http://localhost:8000";        java.net.URI uri = java.net.URI.create(baseUrl + "/fixtures/hook_execution_order/api/test-hook-order");
        var builder = java.net.http.HttpRequest.newBuilder(uri)
        .method("GET", java.net.http.HttpRequest.BodyPublishers.noBody());        var response = java.net.http.HttpClient.newHttpClient()
        .send(builder.build(), java.net.http.HttpResponse.BodyHandlers.ofString());
        assertEquals(200, response.statusCode(), "status code mismatch");        var bodyJson = MAPPER.readTree(response.body());
        var expectedJson = MAPPER.readTree("{\"execution_order\":[\"first_hook\",\"second_hook\",\"third_hook\"],\"message\":\"Hooks executed in order\"}");
        assertEquals(expectedJson, bodyJson, "body mismatch");    }

    @Test    void testMultipleHooksAllPhases() throws Exception {
        // Test multiple lifecycle hooks across all five phases for a complete request lifecycle
        String baseUrl = System.getenv("SUT_URL");
        if (baseUrl == null) baseUrl = "http://localhost:8000";        java.net.URI uri = java.net.URI.create(baseUrl + "/fixtures/multiple_hooks_all_phases/api/full-lifecycle");
        var builder = java.net.http.HttpRequest.newBuilder(uri)
        .method("POST", java.net.http.HttpRequest.BodyPublishers.ofString("{\"action\":\"update_profile\",\"user_id\":\"user-123\"}"));        builder = builder.header("Authorization", "Bearer valid-token-12345");        builder = builder.header("Content-Type", "application/json");        var response = java.net.http.HttpClient.newHttpClient()
        .send(builder.build(), java.net.http.HttpResponse.BodyHandlers.ofString());
        assertEquals(200, response.statusCode(), "status code mismatch");        assertTrue(response.headers().firstValue("X-Content-Type-Options").orElse("").contains("nosniff"), "header X-Content-Type-Options mismatch");        assertTrue(response.headers().firstValue("X-Frame-Options").orElse("").contains("DENY"), "header X-Frame-Options mismatch");        assertTrue(response.headers().firstValue("X-Request-ID").orElse("").contains(".*"), "header X-Request-ID mismatch");        assertTrue(response.headers().firstValue("X-Response-Time").orElse("").contains(".*ms"), "header X-Response-Time mismatch");        var bodyJson = MAPPER.readTree(response.body());
        var expectedJson = MAPPER.readTree("{\"action\":\"update_profile\",\"message\":\"Action completed successfully\",\"request_id\":\".*\",\"user_id\":\"user-123\"}");
        assertEquals(expectedJson, bodyJson, "body mismatch");    }

    @Test    void testOnerrorErrorLogging() throws Exception {
        // Test onError hook that logs server errors and formats error responses
        String baseUrl = System.getenv("SUT_URL");
        if (baseUrl == null) baseUrl = "http://localhost:8000";        java.net.URI uri = java.net.URI.create(baseUrl + "/fixtures/onerror_error_logging/api/test-error");
        var builder = java.net.http.HttpRequest.newBuilder(uri)
        .method("GET", java.net.http.HttpRequest.BodyPublishers.noBody());        var response = java.net.http.HttpClient.newHttpClient()
        .send(builder.build(), java.net.http.HttpResponse.BodyHandlers.ofString());
        assertEquals(500, response.statusCode(), "status code mismatch");        assertTrue(response.headers().firstValue("Content-Type").orElse("").contains("application/json"), "header Content-Type mismatch");        var bodyJson = MAPPER.readTree(response.body());
        var expectedJson = MAPPER.readTree("{\"error\":\"Internal Server Error\",\"error_id\":\".*\",\"message\":\"An unexpected error occurred\"}");
        assertEquals(expectedJson, bodyJson, "body mismatch");    }

    @Test    void testOnrequestRequestLogging() throws Exception {
        // Test onRequest hook that logs incoming requests and adds a request ID
        String baseUrl = System.getenv("SUT_URL");
        if (baseUrl == null) baseUrl = "http://localhost:8000";        java.net.URI uri = java.net.URI.create(baseUrl + "/fixtures/onrequest_request_logging/api/test-on-request");
        var builder = java.net.http.HttpRequest.newBuilder(uri)
        .method("GET", java.net.http.HttpRequest.BodyPublishers.noBody());        var response = java.net.http.HttpClient.newHttpClient()
        .send(builder.build(), java.net.http.HttpResponse.BodyHandlers.ofString());
        assertEquals(200, response.statusCode(), "status code mismatch");        assertTrue(response.headers().firstValue("X-Request-ID").orElse("").contains(".*"), "header X-Request-ID mismatch");        var bodyJson = MAPPER.readTree(response.body());
        var expectedJson = MAPPER.readTree("{\"has_request_id\":true,\"message\":\"onRequest hooks executed\",\"request_logged\":true}");
        assertEquals(expectedJson, bodyJson, "body mismatch");    }

    @Test    void testOnresponseResponseTiming() throws Exception {
        // Test onResponse hook that adds timing information to response headers
        String baseUrl = System.getenv("SUT_URL");
        if (baseUrl == null) baseUrl = "http://localhost:8000";        java.net.URI uri = java.net.URI.create(baseUrl + "/fixtures/onresponse_response_timing/api/test-timing");
        var builder = java.net.http.HttpRequest.newBuilder(uri)
        .method("GET", java.net.http.HttpRequest.BodyPublishers.noBody());        var response = java.net.http.HttpClient.newHttpClient()
        .send(builder.build(), java.net.http.HttpResponse.BodyHandlers.ofString());
        assertEquals(200, response.statusCode(), "status code mismatch");        assertTrue(response.headers().firstValue("X-Response-Time").orElse("").contains(".*ms"), "header X-Response-Time mismatch");        var bodyJson = MAPPER.readTree(response.body());
        var expectedJson = MAPPER.readTree("{\"message\":\"Response with timing info\"}");
        assertEquals(expectedJson, bodyJson, "body mismatch");    }

    @Test    void testOnresponseSecurityHeaders() throws Exception {
        // Test onResponse hook that adds security headers to all responses
        String baseUrl = System.getenv("SUT_URL");
        if (baseUrl == null) baseUrl = "http://localhost:8000";        java.net.URI uri = java.net.URI.create(baseUrl + "/fixtures/onresponse_security_headers/api/test-security-headers");
        var builder = java.net.http.HttpRequest.newBuilder(uri)
        .method("GET", java.net.http.HttpRequest.BodyPublishers.noBody());        var response = java.net.http.HttpClient.newHttpClient()
        .send(builder.build(), java.net.http.HttpResponse.BodyHandlers.ofString());
        assertEquals(200, response.statusCode(), "status code mismatch");        assertTrue(response.headers().firstValue("Strict-Transport-Security").orElse("").contains("max-age=31536000; includeSubDomains"), "header Strict-Transport-Security mismatch");        assertTrue(response.headers().firstValue("X-Content-Type-Options").orElse("").contains("nosniff"), "header X-Content-Type-Options mismatch");        assertTrue(response.headers().firstValue("X-Frame-Options").orElse("").contains("DENY"), "header X-Frame-Options mismatch");        assertTrue(response.headers().firstValue("X-XSS-Protection").orElse("").contains("1; mode=block"), "header X-XSS-Protection mismatch");        var bodyJson = MAPPER.readTree(response.body());
        var expectedJson = MAPPER.readTree("{\"message\":\"Response with security headers\"}");
        assertEquals(expectedJson, bodyJson, "body mismatch");    }

    @Test    void testPrehandlerAuthenticationFailedShortCircuit() throws Exception {
        // Test preHandler hook that short-circuits on invalid authentication
        String baseUrl = System.getenv("SUT_URL");
        if (baseUrl == null) baseUrl = "http://localhost:8000";        java.net.URI uri = java.net.URI.create(baseUrl + "/fixtures/prehandler_authentication_failed_short_circuit/api/protected-resource-fail");
        var builder = java.net.http.HttpRequest.newBuilder(uri)
        .method("GET", java.net.http.HttpRequest.BodyPublishers.noBody());        builder = builder.header("Authorization", "Bearer invalid-token");        var response = java.net.http.HttpClient.newHttpClient()
        .send(builder.build(), java.net.http.HttpResponse.BodyHandlers.ofString());
        assertEquals(401, response.statusCode(), "status code mismatch");        var bodyJson = MAPPER.readTree(response.body());
        var expectedJson = MAPPER.readTree("{\"error\":\"Unauthorized\",\"message\":\"Invalid or expired authentication token\"}");
        assertEquals(expectedJson, bodyJson, "body mismatch");    }

    @Test    void testPrehandlerAuthenticationSuccess() throws Exception {
        // Test preHandler hook that validates authentication tokens
        String baseUrl = System.getenv("SUT_URL");
        if (baseUrl == null) baseUrl = "http://localhost:8000";        java.net.URI uri = java.net.URI.create(baseUrl + "/fixtures/prehandler_authentication_success/api/protected-resource");
        var builder = java.net.http.HttpRequest.newBuilder(uri)
        .method("GET", java.net.http.HttpRequest.BodyPublishers.noBody());        builder = builder.header("Authorization", "Bearer valid-token-12345");        var response = java.net.http.HttpClient.newHttpClient()
        .send(builder.build(), java.net.http.HttpResponse.BodyHandlers.ofString());
        assertEquals(200, response.statusCode(), "status code mismatch");        var bodyJson = MAPPER.readTree(response.body());
        var expectedJson = MAPPER.readTree("{\"authenticated\":true,\"message\":\"Access granted\",\"user_id\":\"user-123\"}");
        assertEquals(expectedJson, bodyJson, "body mismatch");    }

    @Test    void testPrehandlerAuthorizationCheck() throws Exception {
        // Test preHandler hook for role-based authorization after authentication
        String baseUrl = System.getenv("SUT_URL");
        if (baseUrl == null) baseUrl = "http://localhost:8000";        java.net.URI uri = java.net.URI.create(baseUrl + "/fixtures/prehandler_authorization_check/api/admin-only");
        var builder = java.net.http.HttpRequest.newBuilder(uri)
        .method("GET", java.net.http.HttpRequest.BodyPublishers.noBody());        builder = builder.header("Authorization", "Bearer admin-token-67890");        var response = java.net.http.HttpClient.newHttpClient()
        .send(builder.build(), java.net.http.HttpResponse.BodyHandlers.ofString());
        assertEquals(200, response.statusCode(), "status code mismatch");        var bodyJson = MAPPER.readTree(response.body());
        var expectedJson = MAPPER.readTree("{\"message\":\"Admin access granted\",\"role\":\"admin\",\"user_id\":\"admin-456\"}");
        assertEquals(expectedJson, bodyJson, "body mismatch");    }

    @Test    void testPrehandlerAuthorizationForbiddenShortCircuit() throws Exception {
        // Test preHandler hook that denies access for insufficient permissions
        String baseUrl = System.getenv("SUT_URL");
        if (baseUrl == null) baseUrl = "http://localhost:8000";        java.net.URI uri = java.net.URI.create(baseUrl + "/fixtures/prehandler_authorization_forbidden_short_circuit/api/admin-only-forbidden");
        var builder = java.net.http.HttpRequest.newBuilder(uri)
        .method("GET", java.net.http.HttpRequest.BodyPublishers.noBody());        builder = builder.header("Authorization", "Bearer user-token-11111");        var response = java.net.http.HttpClient.newHttpClient()
        .send(builder.build(), java.net.http.HttpResponse.BodyHandlers.ofString());
        assertEquals(403, response.statusCode(), "status code mismatch");        var bodyJson = MAPPER.readTree(response.body());
        var expectedJson = MAPPER.readTree("{\"error\":\"Forbidden\",\"message\":\"Admin role required for this endpoint\"}");
        assertEquals(expectedJson, bodyJson, "body mismatch");    }

    @Test    void testPrevalidationRateLimitExceededShortCircuit() throws Exception {
        // Test preValidation hook that short-circuits when rate limit is exceeded
        String baseUrl = System.getenv("SUT_URL");
        if (baseUrl == null) baseUrl = "http://localhost:8000";        java.net.URI uri = java.net.URI.create(baseUrl + "/fixtures/prevalidation_rate_limit_exceeded_short_circuit/api/test-rate-limit-exceeded");
        var builder = java.net.http.HttpRequest.newBuilder(uri)
        .method("POST", java.net.http.HttpRequest.BodyPublishers.ofString("{\"data\":\"test\"}"));        builder = builder.header("Content-Type", "application/json");        var response = java.net.http.HttpClient.newHttpClient()
        .send(builder.build(), java.net.http.HttpResponse.BodyHandlers.ofString());
        assertEquals(429, response.statusCode(), "status code mismatch");        assertTrue(response.headers().firstValue("Retry-After").orElse("").contains("60"), "header Retry-After mismatch");        var bodyJson = MAPPER.readTree(response.body());
        var expectedJson = MAPPER.readTree("{\"error\":\"Rate limit exceeded\",\"message\":\"Too many requests, please try again later\"}");
        assertEquals(expectedJson, bodyJson, "body mismatch");    }

    @Test    void testPrevalidationRateLimiting() throws Exception {
        // Test preValidation hook that implements rate limiting before validation
        String baseUrl = System.getenv("SUT_URL");
        if (baseUrl == null) baseUrl = "http://localhost:8000";        java.net.URI uri = java.net.URI.create(baseUrl + "/fixtures/prevalidation_rate_limiting/api/test-rate-limit");
        var builder = java.net.http.HttpRequest.newBuilder(uri)
        .method("POST", java.net.http.HttpRequest.BodyPublishers.ofString("{\"data\":\"test\"}"));        builder = builder.header("Content-Type", "application/json");        var response = java.net.http.HttpClient.newHttpClient()
        .send(builder.build(), java.net.http.HttpResponse.BodyHandlers.ofString());
        assertEquals(200, response.statusCode(), "status code mismatch");        var bodyJson = MAPPER.readTree(response.body());
        var expectedJson = MAPPER.readTree("{\"message\":\"Request accepted\",\"rate_limit_checked\":true}");
        assertEquals(expectedJson, bodyJson, "body mismatch");    }

}
