// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2534828255bb1a5de9beab37d340c54c3cbf79a56d04a664bf617567ad217e56
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
import Spikard
import RustBridge

/// E2e tests for category: http_methods.
final class HttpMethodsTests: XCTestCase {
    /// Tests DELETE method to remove a resource
    func testDeleteRemoveResource() throws {
        let _baseURL = AlefE2EMockServer.baseURL
        var _req = URLRequest(url: URL(string: _baseURL + "/fixtures/delete_remove_resource")!)
        _req.httpMethod = "DELETE"
        var response: HTTPURLResponse?
        var _responseData: Data?
        let _sema = DispatchSemaphore(value: 0)
        alefE2ESession.dataTask(with: _req) { data, resp, _ in
            response = resp as? HTTPURLResponse
            _responseData = data
            _sema.signal()
        }.resume()
        _sema.wait()
        let _resp = try XCTUnwrap(response)
        XCTAssertEqual(_resp.statusCode, 200)
        let _expected = try JSONSerialization.jsonObject(with: "{}".data(using: .utf8)!)
        let _actual = try JSONSerialization.jsonObject(with: XCTUnwrap(_responseData))
        XCTAssertEqual(NSDictionary(dictionary: _expected as? [String: AnyHashable] ?? [:]), NSDictionary(dictionary: _actual as? [String: AnyHashable] ?? [:]))
    }

    /// Tests DELETE on non-existent resource returns 404
    func testDeleteResourceNotFound() throws {
        let _baseURL = AlefE2EMockServer.baseURL
        var _req = URLRequest(url: URL(string: _baseURL + "/fixtures/delete_resource_not_found")!)
        _req.httpMethod = "DELETE"
        var response: HTTPURLResponse?
        var _responseData: Data?
        let _sema = DispatchSemaphore(value: 0)
        alefE2ESession.dataTask(with: _req) { data, resp, _ in
            response = resp as? HTTPURLResponse
            _responseData = data
            _sema.signal()
        }.resume()
        _sema.wait()
        let _resp = try XCTUnwrap(response)
        XCTAssertEqual(_resp.statusCode, 200)
        let _expected = try JSONSerialization.jsonObject(with: "{}".data(using: .utf8)!)
        let _actual = try JSONSerialization.jsonObject(with: XCTUnwrap(_responseData))
        XCTAssertEqual(NSDictionary(dictionary: _expected as? [String: AnyHashable] ?? [:]), NSDictionary(dictionary: _actual as? [String: AnyHashable] ?? [:]))
    }

    /// Tests DELETE returning deleted resource data
    func testDeleteWithResponseBody() throws {
        let _baseURL = AlefE2EMockServer.baseURL
        var _req = URLRequest(url: URL(string: _baseURL + "/fixtures/delete_with_response_body")!)
        _req.httpMethod = "DELETE"
        var response: HTTPURLResponse?
        var _responseData: Data?
        let _sema = DispatchSemaphore(value: 0)
        alefE2ESession.dataTask(with: _req) { data, resp, _ in
            response = resp as? HTTPURLResponse
            _responseData = data
            _sema.signal()
        }.resume()
        _sema.wait()
        let _resp = try XCTUnwrap(response)
        XCTAssertEqual(_resp.statusCode, 200)
        let _expected = try JSONSerialization.jsonObject(with: "{\"id\":1,\"message\":\"Item deleted successfully\",\"name\":\"Deleted Item\"}".data(using: .utf8)!)
        let _actual = try JSONSerialization.jsonObject(with: XCTUnwrap(_responseData))
        XCTAssertEqual(NSDictionary(dictionary: _expected as? [String: AnyHashable] ?? [:]), NSDictionary(dictionary: _actual as? [String: AnyHashable] ?? [:]))
    }

    /// Tests HEAD method returns headers without response body
    func testHeadGetMetadataWithoutBody() throws {
        let _baseURL = AlefE2EMockServer.baseURL
        var _req = URLRequest(url: URL(string: _baseURL + "/fixtures/head_get_metadata_without_body")!)
        _req.httpMethod = "HEAD"
        var response: HTTPURLResponse?
        var _responseData: Data?
        let _sema = DispatchSemaphore(value: 0)
        alefE2ESession.dataTask(with: _req) { data, resp, _ in
            response = resp as? HTTPURLResponse
            _responseData = data
            _sema.signal()
        }.resume()
        _sema.wait()
        let _resp = try XCTUnwrap(response)
        XCTAssertEqual(_resp.statusCode, 200)
        XCTAssertEqual(_resp.value(forHTTPHeaderField: "content-length"), "85")
        XCTAssertEqual(_resp.value(forHTTPHeaderField: "content-type"), "application/json")
    }

    /// Tests PATCH method for partial resource updates
    func testPatchPartialUpdate() throws {
        let _baseURL = AlefE2EMockServer.baseURL
        var _req = URLRequest(url: URL(string: _baseURL + "/fixtures/patch_partial_update")!)
        _req.httpMethod = "PATCH"
        _req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        _req.httpBody = "{\"price\":79.99}".data(using: .utf8)
        _req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        var response: HTTPURLResponse?
        var _responseData: Data?
        let _sema = DispatchSemaphore(value: 0)
        alefE2ESession.dataTask(with: _req) { data, resp, _ in
            response = resp as? HTTPURLResponse
            _responseData = data
            _sema.signal()
        }.resume()
        _sema.wait()
        let _resp = try XCTUnwrap(response)
        XCTAssertEqual(_resp.statusCode, 200)
        let _expected = try JSONSerialization.jsonObject(with: "{\"id\":1,\"in_stock\":true,\"name\":\"Existing Item\",\"price\":79.99}".data(using: .utf8)!)
        let _actual = try JSONSerialization.jsonObject(with: XCTUnwrap(_responseData))
        XCTAssertEqual(NSDictionary(dictionary: _expected as? [String: AnyHashable] ?? [:]), NSDictionary(dictionary: _actual as? [String: AnyHashable] ?? [:]))
    }

    /// Tests PATCH updating multiple fields at once
    func testPatchUpdateMultipleFields() throws {
        let _baseURL = AlefE2EMockServer.baseURL
        var _req = URLRequest(url: URL(string: _baseURL + "/fixtures/patch_update_multiple_fields")!)
        _req.httpMethod = "PATCH"
        _req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        _req.httpBody = "{\"in_stock\":false,\"name\":\"Updated Name\",\"price\":89.99}".data(using: .utf8)
        _req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        var response: HTTPURLResponse?
        var _responseData: Data?
        let _sema = DispatchSemaphore(value: 0)
        alefE2ESession.dataTask(with: _req) { data, resp, _ in
            response = resp as? HTTPURLResponse
            _responseData = data
            _sema.signal()
        }.resume()
        _sema.wait()
        let _resp = try XCTUnwrap(response)
        XCTAssertEqual(_resp.statusCode, 200)
        let _expected = try JSONSerialization.jsonObject(with: "{\"id\":1,\"in_stock\":false,\"name\":\"Updated Name\",\"price\":89.99}".data(using: .utf8)!)
        let _actual = try JSONSerialization.jsonObject(with: XCTUnwrap(_responseData))
        XCTAssertEqual(NSDictionary(dictionary: _expected as? [String: AnyHashable] ?? [:]), NSDictionary(dictionary: _actual as? [String: AnyHashable] ?? [:]))
    }

    /// Tests PUT method for complete resource replacement
    func testPutCompleteResourceReplacement() throws {
        let _baseURL = AlefE2EMockServer.baseURL
        var _req = URLRequest(url: URL(string: _baseURL + "/fixtures/put_complete_resource_replacement")!)
        _req.httpMethod = "PUT"
        _req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        _req.httpBody = "{\"description\":\"Completely replaced\",\"id\":1,\"in_stock\":true,\"name\":\"Updated Item\",\"price\":99.99}".data(using: .utf8)
        _req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        var response: HTTPURLResponse?
        var _responseData: Data?
        let _sema = DispatchSemaphore(value: 0)
        alefE2ESession.dataTask(with: _req) { data, resp, _ in
            response = resp as? HTTPURLResponse
            _responseData = data
            _sema.signal()
        }.resume()
        _sema.wait()
        let _resp = try XCTUnwrap(response)
        XCTAssertEqual(_resp.statusCode, 200)
        let _expected = try JSONSerialization.jsonObject(with: "{\"description\":\"Completely replaced\",\"id\":1,\"in_stock\":true,\"name\":\"Updated Item\",\"price\":99.99}".data(using: .utf8)!)
        let _actual = try JSONSerialization.jsonObject(with: XCTUnwrap(_responseData))
        XCTAssertEqual(NSDictionary(dictionary: _expected as? [String: AnyHashable] ?? [:]), NSDictionary(dictionary: _actual as? [String: AnyHashable] ?? [:]))
    }

    /// Tests PUT creating new resource at specific URI
    func testPutCreateResourceIfDoesnTExist() throws {
        let _baseURL = AlefE2EMockServer.baseURL
        var _req = URLRequest(url: URL(string: _baseURL + "/fixtures/put_create_resource_if_doesn_t_exist")!)
        _req.httpMethod = "PUT"
        _req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        _req.httpBody = "{\"id\":999,\"name\":\"New Item\",\"price\":49.99}".data(using: .utf8)
        _req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        var response: HTTPURLResponse?
        var _responseData: Data?
        let _sema = DispatchSemaphore(value: 0)
        alefE2ESession.dataTask(with: _req) { data, resp, _ in
            response = resp as? HTTPURLResponse
            _responseData = data
            _sema.signal()
        }.resume()
        _sema.wait()
        let _resp = try XCTUnwrap(response)
        XCTAssertEqual(_resp.statusCode, 200)
        let _expected = try JSONSerialization.jsonObject(with: "{\"id\":999,\"name\":\"New Item\",\"price\":49.99}".data(using: .utf8)!)
        let _actual = try JSONSerialization.jsonObject(with: XCTUnwrap(_responseData))
        XCTAssertEqual(NSDictionary(dictionary: _expected as? [String: AnyHashable] ?? [:]), NSDictionary(dictionary: _actual as? [String: AnyHashable] ?? [:]))
    }

    /// Tests PUT idempotency - repeated calls produce same result
    func testPutIdempotentOperation() throws {
        let _baseURL = AlefE2EMockServer.baseURL
        var _req = URLRequest(url: URL(string: _baseURL + "/fixtures/put_idempotent_operation")!)
        _req.httpMethod = "PUT"
        _req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        _req.httpBody = "{\"id\":1,\"name\":\"Fixed Name\",\"price\":50.0}".data(using: .utf8)
        _req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        var response: HTTPURLResponse?
        var _responseData: Data?
        let _sema = DispatchSemaphore(value: 0)
        alefE2ESession.dataTask(with: _req) { data, resp, _ in
            response = resp as? HTTPURLResponse
            _responseData = data
            _sema.signal()
        }.resume()
        _sema.wait()
        let _resp = try XCTUnwrap(response)
        XCTAssertEqual(_resp.statusCode, 200)
        let _expected = try JSONSerialization.jsonObject(with: "{\"id\":1,\"name\":\"Fixed Name\",\"price\":50.0}".data(using: .utf8)!)
        let _actual = try JSONSerialization.jsonObject(with: XCTUnwrap(_responseData))
        XCTAssertEqual(NSDictionary(dictionary: _expected as? [String: AnyHashable] ?? [:]), NSDictionary(dictionary: _actual as? [String: AnyHashable] ?? [:]))
    }

    /// Tests PUT with missing required fields returns 422
    func testPutMissingRequiredField() throws {
        let _baseURL = AlefE2EMockServer.baseURL
        var _req = URLRequest(url: URL(string: _baseURL + "/fixtures/put_missing_required_field")!)
        _req.httpMethod = "PUT"
        _req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        _req.httpBody = "{\"id\":1,\"name\":\"Item Name\"}".data(using: .utf8)
        _req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        var response: HTTPURLResponse?
        var _responseData: Data?
        let _sema = DispatchSemaphore(value: 0)
        alefE2ESession.dataTask(with: _req) { data, resp, _ in
            response = resp as? HTTPURLResponse
            _responseData = data
            _sema.signal()
        }.resume()
        _sema.wait()
        let _resp = try XCTUnwrap(response)
        XCTAssertEqual(_resp.statusCode, 422)
        let _expected = try JSONSerialization.jsonObject(with: "{\"detail\":\"1 validation error in request\",\"errors\":[{\"input\":{\"id\":1,\"name\":\"Item Name\"},\"loc\":[\"body\",\"price\"],\"msg\":\"Field required\",\"type\":\"missing\"}],\"status\":422,\"title\":\"Request Validation Failed\",\"type\":\"https://spikard.dev/errors/validation-error\"}".data(using: .utf8)!)
        let _actual = try JSONSerialization.jsonObject(with: XCTUnwrap(_responseData))
        XCTAssertEqual(NSDictionary(dictionary: _expected as? [String: AnyHashable] ?? [:]), NSDictionary(dictionary: _actual as? [String: AnyHashable] ?? [:]))
    }

    /// Tests PUT with invalid data returns 422
    func testPutValidationError() throws {
        let _baseURL = AlefE2EMockServer.baseURL
        var _req = URLRequest(url: URL(string: _baseURL + "/fixtures/put_validation_error")!)
        _req.httpMethod = "PUT"
        _req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        _req.httpBody = "{\"id\":1,\"name\":\"X\",\"price\":-10}".data(using: .utf8)
        _req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        var response: HTTPURLResponse?
        var _responseData: Data?
        let _sema = DispatchSemaphore(value: 0)
        alefE2ESession.dataTask(with: _req) { data, resp, _ in
            response = resp as? HTTPURLResponse
            _responseData = data
            _sema.signal()
        }.resume()
        _sema.wait()
        let _resp = try XCTUnwrap(response)
        XCTAssertEqual(_resp.statusCode, 422)
        let _expected = try JSONSerialization.jsonObject(with: "{\"detail\":\"2 validation errors in request\",\"errors\":[{\"ctx\":{\"min_length\":3},\"input\":\"X\",\"loc\":[\"body\",\"name\"],\"msg\":\"String should have at least 3 characters\",\"type\":\"string_too_short\"},{\"ctx\":{\"gt\":0},\"input\":-10,\"loc\":[\"body\",\"price\"],\"msg\":\"Input should be greater than 0\",\"type\":\"greater_than\"}],\"status\":422,\"title\":\"Request Validation Failed\",\"type\":\"https://spikard.dev/errors/validation-error\"}".data(using: .utf8)!)
        let _actual = try JSONSerialization.jsonObject(with: XCTUnwrap(_responseData))
        XCTAssertEqual(NSDictionary(dictionary: _expected as? [String: AnyHashable] ?? [:]), NSDictionary(dictionary: _actual as? [String: AnyHashable] ?? [:]))
    }

}
