# This file is auto-generated by alef. DO NOT EDIT.
defmodule Spikard.JsonRpcConfig do
  @moduledoc "JSON-RPC server configuration"

  defstruct enabled: true,
            endpoint_path: "",
            enable_batch: false,
            max_batch_size: 0
end
