# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9325e9e82f8380b2349db1276cfcb86c957900d16930fdee510ea9155358c796
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Spikard.JsonRpcConfig do
  @moduledoc "JSON-RPC server configuration"

  @typedoc "JSON-RPC server configuration"
  @type t :: %__MODULE__{
          enabled: boolean(),
          endpoint_path: String.t() | nil,
          enable_batch: boolean(),
          max_batch_size: non_neg_integer()
        }

  defstruct enabled: true,
            endpoint_path: nil,
            enable_batch: false,
            max_batch_size: 0
end
