# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b558c667bbf52a4cc550988bbbcc498b734b0b0c37e57bec0aeef3f372239ccf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Spikard.JwtConfig do
  @moduledoc "JWT authentication configuration"

  defstruct secret: "",
            algorithm: "",
            audience: nil,
            issuer: nil,
            leeway: 0
end
