# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4da1fb2f5b8fdb88635e4b10076e5afdf94574092af51a0dfd315c5f2aa72b34
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Spikard.JwtConfig do
  @moduledoc "JWT authentication configuration"

  @typedoc "JWT authentication configuration"
  @type t :: %__MODULE__{
          secret: String.t() | nil,
          algorithm: String.t() | nil,
          audience: [String.t()] | nil,
          issuer: String.t() | nil,
          leeway: non_neg_integer()
        }

  defstruct secret: nil,
            algorithm: nil,
            audience: nil,
            issuer: nil,
            leeway: 0
end
