# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e15799d9c470bee944e92a07d5b845023c70a3bd15f2070d5ee8cc1b24bc7399
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Spikard.ParseRequest do
  @moduledoc "Request body for `POST /asyncapi/parse`"

  @typedoc "Request body for `POST /asyncapi/parse`"
  @type t :: %__MODULE__{
          spec: String.t() | nil
        }

  defstruct spec: nil
end
