# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dae9864c492f1647728324f9cd4ec5cfdf8d3c00fa1635b94158c0ccaf326f91
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Spikard.ParsedChannel do
  @moduledoc "A single channel extracted from an AsyncAPI spec"

  defstruct name: "",
            address: "",
            messages: [],
            bindings: nil
end
