# This file is auto-generated by alef. DO NOT EDIT.
defmodule Spikard.StaticAsset do
  @moduledoc "Pre-rendered static asset produced by the CLI bundler."

  defstruct route: "",
            headers: %{},
            body: ""
end
