// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1108e9679ef664f6d9dd02c986b4fd875a8db5973473c9a02b1ab3183fa74a5a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import XCTest
import Spikard

/// E2e tests for category: validation_errors.
final class ValidationErrorsTests: XCTestCase {
    func test09MultipleValidationErrors() async throws {
        // Multiple validation errors should be returned together in batch
        let response = try await handleRequest()
    }

    func test10NestedErrorPath() async throws {
        // Validation error in nested object should have correct path in loc
        let response = try await handleRequest()
    }

    func testArrayItemValidationError() async throws {
        // Tests validation error for invalid item within array
        let response = try await handleRequest()
    }

    func testArrayMaxItemsConstraintViolation() async throws {
        // Tests validation error when array has more items than max_items
        let response = try await handleRequest()
    }

    func testArrayMinItemsConstraintViolation() async throws {
        // Tests validation error when array has fewer items than min_items
        let response = try await handleRequest()
    }

    func testBodyFieldTypeErrorStringForFloat() async throws {
        // Tests validation error when body field has wrong type
        let response = try await handleRequest()
    }

    func testHeaderValidationError() async throws {
        // Tests validation error when required header is missing
        let response = try await handleRequest()
    }

    func testInvalidBooleanValue() async throws {
        // Tests validation error when boolean value is invalid
        let response = try await handleRequest()
    }

    func testInvalidDatetimeFormat() async throws {
        // Tests validation error when datetime format is invalid
        let response = try await handleRequest()
    }

    func testInvalidEnumValue() async throws {
        // Tests validation error when value is not in allowed enum values
        let response = try await handleRequest()
    }

    func testInvalidUuidFormat() async throws {
        // Tests validation error when UUID format is invalid
        let response = try await handleRequest()
    }

    func testMalformedJsonBody() async throws {
        // Tests validation error when request body contains malformed JSON
        let response = try await handleRequest()
    }

    func testMissingRequiredBodyField() async throws {
        // Tests validation error when required body field is missing
        let response = try await handleRequest()
    }

    func testMissingRequiredQueryParameter() async throws {
        // Tests validation error when required query param is missing
        let response = try await handleRequest()
    }

    func testMultipleValidationErrors2() async throws {
        // Tests multiple validation errors returned in single response
        let response = try await handleRequest()
    }

    func testNestedObjectValidationError() async throws {
        // Tests validation error in nested object field
        let response = try await handleRequest()
    }

    func testNumericConstraintViolationGtGreaterThan() async throws {
        // Tests validation error when value violates gt constraint
        let response = try await handleRequest()
    }

    func testNumericConstraintViolationLeLessThanOrEqual() async throws {
        // Tests validation error when value violates le constraint
        let response = try await handleRequest()
    }

    func testQueryParamTypeErrorStringProvidedForInt() async throws {
        // Tests validation error when string is provided for integer query param
        let response = try await handleRequest()
    }

    func testStringMaxLengthConstraintViolation() async throws {
        // Tests validation error when string exceeds max_length
        let response = try await handleRequest()
    }

    func testStringMinLengthConstraintViolation() async throws {
        // Tests validation error when string is shorter than min_length
        let response = try await handleRequest()
    }

    func testStringRegexPatternMismatch() async throws {
        // Tests validation error when string doesn't match regex pattern
        let response = try await handleRequest()
    }

}
