// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fdd3a0970d060049a5e224c20f4e8c42cb8ae106bbedb4c7b72f058c0d013e75
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import gleeunit
import gleeunit/should
import gleam/httpc
import gleam/http
import gleam/http/request
import gleam/list
import gleam/result
import gleam/string
import envoy

// Multiple validation errors should be returned together in batch
pub fn multiple_validation_errors_test() {
  let base_url = case envoy.get("MOCK_SERVER_URL") {
    Ok(u) -> u
    Error(_) -> "http://localhost:8080"
  }
  let assert Ok(req) = request.to(base_url <> "/fixtures/09_multiple_validation_errors")
  let req = request.set_method(req, http.Post)
  let req = request.set_header(req, "content-type", "application/json")
  let req = request.set_body(req, "{\"age\":15,\"email\":\"invalid-email\",\"name\":\"ab\"}")
  let assert Ok(resp) = httpc.send(req)
  resp.status |> should.equal(422)
  resp.body |> string.trim |> should.equal("{\"detail\":\"3 validation errors in request\",\"errors\":[{\"ctx\":{\"ge\":18},\"input\":15,\"loc\":[\"body\",\"age\"],\"msg\":\"Input should be greater than or equal to 18\",\"type\":\"greater_than_equal\"},{\"ctx\":{\"pattern\":\"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\\\.[a-zA-Z0-9-.]+$\"},\"input\":\"invalid-email\",\"loc\":[\"body\",\"email\"],\"msg\":\"String should match pattern '^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\\\.[a-zA-Z0-9-.]+$'\",\"type\":\"string_pattern_mismatch\"},{\"ctx\":{\"min_length\":3},\"input\":\"ab\",\"loc\":[\"body\",\"name\"],\"msg\":\"String should have at least 3 characters\",\"type\":\"string_too_short\"}],\"status\":422,\"title\":\"Request Validation Failed\",\"type\":\"https://spikard.dev/errors/validation-error\"}")
}

// Validation error in nested object should have correct path in loc
pub fn nested_error_path_test() {
  let base_url = case envoy.get("MOCK_SERVER_URL") {
    Ok(u) -> u
    Error(_) -> "http://localhost:8080"
  }
  let assert Ok(req) = request.to(base_url <> "/fixtures/10_nested_error_path")
  let req = request.set_method(req, http.Post)
  let req = request.set_header(req, "content-type", "application/json")
  let req = request.set_body(req, "{\"profile\":{\"contact\":{\"email\":\"invalid\"}}}")
  let assert Ok(resp) = httpc.send(req)
  resp.status |> should.equal(422)
  resp.body |> string.trim |> should.equal("{\"detail\":\"1 validation error in request\",\"errors\":[{\"ctx\":{\"pattern\":\"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\\\.[a-zA-Z0-9-.]+$\"},\"input\":\"invalid\",\"loc\":[\"body\",\"profile\",\"contact\",\"email\"],\"msg\":\"String should match pattern '^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\\\.[a-zA-Z0-9-.]+$'\",\"type\":\"string_pattern_mismatch\"}],\"status\":422,\"title\":\"Request Validation Failed\",\"type\":\"https://spikard.dev/errors/validation-error\"}")
}

// Tests validation error for invalid item within array
pub fn array_item_validation_error_test() {
  let base_url = case envoy.get("MOCK_SERVER_URL") {
    Ok(u) -> u
    Error(_) -> "http://localhost:8080"
  }
  let assert Ok(req) = request.to(base_url <> "/fixtures/array_item_validation_error")
  let req = request.set_method(req, http.Post)
  let req = request.set_header(req, "content-type", "application/json")
  let req = request.set_header(req, "Content-Type", "application/json")
  let req = request.set_body(req, "{\"name\":\"Item\",\"price\":10.0,\"tags\":[\"tag1\",\"tag2\",123]}")
  let assert Ok(resp) = httpc.send(req)
  resp.status |> should.equal(422)
  resp.body |> string.trim |> should.equal("{\"detail\":\"1 validation error in request\",\"errors\":[{\"input\":123,\"loc\":[\"body\",\"tags\",\"2\"],\"msg\":\"Input should be a valid unknown\",\"type\":\"type_error\"}],\"status\":422,\"title\":\"Request Validation Failed\",\"type\":\"https://spikard.dev/errors/validation-error\"}")
}

// Tests validation error when array has more items than max_items
pub fn array_max_items_constraint_violation_test() {
  let base_url = case envoy.get("MOCK_SERVER_URL") {
    Ok(u) -> u
    Error(_) -> "http://localhost:8080"
  }
  let assert Ok(req) = request.to(base_url <> "/fixtures/array_max_items_constraint_violation")
  let req = request.set_method(req, http.Post)
  let req = request.set_header(req, "content-type", "application/json")
  let req = request.set_header(req, "Content-Type", "application/json")
  let req = request.set_body(req, "{\"name\":\"Item\",\"price\":10.0,\"tags\":[\"tag1\",\"tag2\",\"tag3\",\"tag4\",\"tag5\",\"tag6\",\"tag7\",\"tag8\",\"tag9\",\"tag10\",\"tag11\"]}")
  let assert Ok(resp) = httpc.send(req)
  resp.status |> should.equal(422)
  resp.body |> string.trim |> should.equal("{\"detail\":\"1 validation error in request\",\"errors\":[{\"ctx\":{\"max_length\":10},\"input\":[\"tag1\",\"tag2\",\"tag3\",\"tag4\",\"tag5\",\"tag6\",\"tag7\",\"tag8\",\"tag9\",\"tag10\",\"tag11\"],\"loc\":[\"body\",\"tags\"],\"msg\":\"List should have at most 10 items after validation\",\"type\":\"too_long\"}],\"status\":422,\"title\":\"Request Validation Failed\",\"type\":\"https://spikard.dev/errors/validation-error\"}")
}

// Tests validation error when array has fewer items than min_items
pub fn array_min_items_constraint_violation_test() {
  let base_url = case envoy.get("MOCK_SERVER_URL") {
    Ok(u) -> u
    Error(_) -> "http://localhost:8080"
  }
  let assert Ok(req) = request.to(base_url <> "/fixtures/array_min_items_constraint_violation")
  let req = request.set_method(req, http.Post)
  let req = request.set_header(req, "content-type", "application/json")
  let req = request.set_header(req, "Content-Type", "application/json")
  let req = request.set_body(req, "{\"name\":\"Item\",\"price\":10.0,\"tags\":[]}")
  let assert Ok(resp) = httpc.send(req)
  resp.status |> should.equal(422)
  resp.body |> string.trim |> should.equal("{\"detail\":\"1 validation error in request\",\"errors\":[{\"ctx\":{\"min_length\":1},\"input\":[],\"loc\":[\"body\",\"tags\"],\"msg\":\"List should have at least 1 item after validation\",\"type\":\"too_short\"}],\"status\":422,\"title\":\"Request Validation Failed\",\"type\":\"https://spikard.dev/errors/validation-error\"}")
}

// Tests validation error when body field has wrong type
pub fn body_field_type_error_string_for_float_test() {
  let base_url = case envoy.get("MOCK_SERVER_URL") {
    Ok(u) -> u
    Error(_) -> "http://localhost:8080"
  }
  let assert Ok(req) = request.to(base_url <> "/fixtures/body_field_type_error_string_for_float")
  let req = request.set_method(req, http.Post)
  let req = request.set_header(req, "content-type", "application/json")
  let req = request.set_header(req, "Content-Type", "application/json")
  let req = request.set_body(req, "{\"name\":\"Item\",\"price\":\"not_a_float\"}")
  let assert Ok(resp) = httpc.send(req)
  resp.status |> should.equal(422)
  resp.body |> string.trim |> should.equal("{\"detail\":\"1 validation error in request\",\"errors\":[{\"input\":\"not_a_float\",\"loc\":[\"body\",\"price\"],\"msg\":\"Input should be a valid number, unable to parse string as a number\",\"type\":\"float_parsing\"}],\"status\":422,\"title\":\"Request Validation Failed\",\"type\":\"https://spikard.dev/errors/validation-error\"}")
}

// Tests validation error when required header is missing
pub fn header_validation_error_test() {
  let base_url = case envoy.get("MOCK_SERVER_URL") {
    Ok(u) -> u
    Error(_) -> "http://localhost:8080"
  }
  let assert Ok(req) = request.to(base_url <> "/fixtures/header_validation_error")
  let req = request.set_method(req, http.Get)
  let assert Ok(resp) = httpc.send(req)
  resp.status |> should.equal(422)
  resp.body |> string.trim |> should.equal("{\"detail\":\"1 validation error in request\",\"errors\":[{\"input\":null,\"loc\":[\"headers\",\"x-token\"],\"msg\":\"Field required\",\"type\":\"missing\"}],\"status\":422,\"title\":\"Request Validation Failed\",\"type\":\"https://spikard.dev/errors/validation-error\"}")
}

// Tests validation error when boolean value is invalid
pub fn invalid_boolean_value_test() {
  let base_url = case envoy.get("MOCK_SERVER_URL") {
    Ok(u) -> u
    Error(_) -> "http://localhost:8080"
  }
  let assert Ok(req) = request.to(base_url <> "/fixtures/invalid_boolean_value")
  let req = request.set_method(req, http.Get)
  let req = request.set_header(req, "x-token", "test-token")
  let assert Ok(resp) = httpc.send(req)
  resp.status |> should.equal(422)
  resp.body |> string.trim |> should.equal("{\"detail\":\"1 validation error in request\",\"errors\":[{\"input\":\"maybe\",\"loc\":[\"query\",\"is_active\"],\"msg\":\"Input should be a valid boolean, unable to interpret input\",\"type\":\"bool_parsing\"}],\"status\":422,\"title\":\"Request Validation Failed\",\"type\":\"https://spikard.dev/errors/validation-error\"}")
}

// Tests validation error when datetime format is invalid
pub fn invalid_datetime_format_test() {
  let base_url = case envoy.get("MOCK_SERVER_URL") {
    Ok(u) -> u
    Error(_) -> "http://localhost:8080"
  }
  let assert Ok(req) = request.to(base_url <> "/fixtures/invalid_datetime_format")
  let req = request.set_method(req, http.Post)
  let req = request.set_header(req, "content-type", "application/json")
  let req = request.set_header(req, "Content-Type", "application/json")
  let req = request.set_body(req, "{\"created_at\":\"not-a-datetime\",\"name\":\"Item\",\"price\":10.0}")
  let assert Ok(resp) = httpc.send(req)
  resp.status |> should.equal(422)
  resp.body |> string.trim |> should.equal("{\"detail\":\"1 validation error in request\",\"errors\":[{\"input\":\"not-a-datetime\",\"loc\":[\"body\",\"created_at\"],\"msg\":\"Input should be a valid datetime\",\"type\":\"datetime_parsing\"}],\"status\":422,\"title\":\"Request Validation Failed\",\"type\":\"https://spikard.dev/errors/validation-error\"}")
}

// Tests validation error when value is not in allowed enum values
pub fn invalid_enum_value_test() {
  let base_url = case envoy.get("MOCK_SERVER_URL") {
    Ok(u) -> u
    Error(_) -> "http://localhost:8080"
  }
  let assert Ok(req) = request.to(base_url <> "/fixtures/invalid_enum_value")
  let req = request.set_method(req, http.Get)
  let assert Ok(resp) = httpc.send(req)
  resp.status |> should.equal(422)
  resp.body |> string.trim |> should.equal("{\"detail\":\"1 validation error in request\",\"errors\":[{\"ctx\":{\"expected\":\"'alexnet', 'resnet' or 'lenet'\"},\"input\":\"invalid_model\",\"loc\":[\"path\",\"model_name\"],\"msg\":\"Input should be 'alexnet', 'resnet' or 'lenet'\",\"type\":\"enum\"}],\"status\":422,\"title\":\"Request Validation Failed\",\"type\":\"https://spikard.dev/errors/validation-error\"}")
}

// Tests validation error when UUID format is invalid
pub fn invalid_uuid_format_test() {
  let base_url = case envoy.get("MOCK_SERVER_URL") {
    Ok(u) -> u
    Error(_) -> "http://localhost:8080"
  }
  let assert Ok(req) = request.to(base_url <> "/fixtures/invalid_uuid_format")
  let req = request.set_method(req, http.Get)
  let assert Ok(resp) = httpc.send(req)
  resp.status |> should.equal(422)
  resp.body |> string.trim |> should.equal("{\"detail\":\"1 validation error in request\",\"errors\":[{\"input\":\"not-a-uuid\",\"loc\":[\"path\",\"item_id\"],\"msg\":\"Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `n` at 0\",\"type\":\"uuid_parsing\"}],\"status\":422,\"title\":\"Request Validation Failed\",\"type\":\"https://spikard.dev/errors/validation-error\"}")
}

// Tests validation error when request body contains malformed JSON
pub fn malformed_json_body_test() {
  let base_url = case envoy.get("MOCK_SERVER_URL") {
    Ok(u) -> u
    Error(_) -> "http://localhost:8080"
  }
  let assert Ok(req) = request.to(base_url <> "/fixtures/malformed_json_body")
  let req = request.set_method(req, http.Post)
  let req = request.set_header(req, "content-type", "application/json")
  let req = request.set_header(req, "Content-Type", "application/json")
  let req = request.set_body(req, "\"{\\\"name\\\": \\\"Item\\\", \\\"price\\\": }\"")
  let assert Ok(resp) = httpc.send(req)
  resp.status |> should.equal(400)
  resp.body |> string.trim |> should.equal("{\"detail\":\"Invalid request format\"}")
}

// Tests validation error when required body field is missing
pub fn missing_required_body_field_test() {
  let base_url = case envoy.get("MOCK_SERVER_URL") {
    Ok(u) -> u
    Error(_) -> "http://localhost:8080"
  }
  let assert Ok(req) = request.to(base_url <> "/fixtures/missing_required_body_field")
  let req = request.set_method(req, http.Post)
  let req = request.set_header(req, "content-type", "application/json")
  let req = request.set_header(req, "Content-Type", "application/json")
  let req = request.set_body(req, "{\"name\":\"Item\"}")
  let assert Ok(resp) = httpc.send(req)
  resp.status |> should.equal(422)
  resp.body |> string.trim |> should.equal("{\"detail\":\"1 validation error in request\",\"errors\":[{\"input\":{\"name\":\"Item\"},\"loc\":[\"body\",\"price\"],\"msg\":\"Field required\",\"type\":\"missing\"}],\"status\":422,\"title\":\"Request Validation Failed\",\"type\":\"https://spikard.dev/errors/validation-error\"}")
}

// Tests validation error when required query param is missing
pub fn missing_required_query_parameter_test() {
  let base_url = case envoy.get("MOCK_SERVER_URL") {
    Ok(u) -> u
    Error(_) -> "http://localhost:8080"
  }
  let assert Ok(req) = request.to(base_url <> "/fixtures/missing_required_query_parameter")
  let req = request.set_method(req, http.Get)
  let req = request.set_header(req, "x-token", "test-token")
  let assert Ok(resp) = httpc.send(req)
  resp.status |> should.equal(422)
  resp.body |> string.trim |> should.equal("{\"detail\":\"1 validation error in request\",\"errors\":[{\"input\":null,\"loc\":[\"query\",\"q\"],\"msg\":\"Field required\",\"type\":\"missing\"}],\"status\":422,\"title\":\"Request Validation Failed\",\"type\":\"https://spikard.dev/errors/validation-error\"}")
}

// Tests multiple validation errors returned in single response
pub fn multiple_validation_errors_2_test() {
  let base_url = case envoy.get("MOCK_SERVER_URL") {
    Ok(u) -> u
    Error(_) -> "http://localhost:8080"
  }
  let assert Ok(req) = request.to(base_url <> "/fixtures/multiple_validation_errors_2")
  let req = request.set_method(req, http.Post)
  let req = request.set_header(req, "content-type", "application/json")
  let req = request.set_header(req, "Content-Type", "application/json")
  let req = request.set_body(req, "{\"name\":\"X\",\"price\":-10,\"quantity\":\"not_a_number\"}")
  let assert Ok(resp) = httpc.send(req)
  resp.status |> should.equal(422)
  resp.body |> string.trim |> should.equal("{\"detail\":\"3 validation errors in request\",\"errors\":[{\"ctx\":{\"min_length\":3},\"input\":\"X\",\"loc\":[\"body\",\"name\"],\"msg\":\"String should have at least 3 characters\",\"type\":\"string_too_short\"},{\"ctx\":{\"gt\":0},\"input\":-10,\"loc\":[\"body\",\"price\"],\"msg\":\"Input should be greater than 0\",\"type\":\"greater_than\"},{\"input\":\"not_a_number\",\"loc\":[\"body\",\"quantity\"],\"msg\":\"Input should be a valid integer, unable to parse string as an integer\",\"type\":\"int_parsing\"}],\"status\":422,\"title\":\"Request Validation Failed\",\"type\":\"https://spikard.dev/errors/validation-error\"}")
}

// Tests validation error in nested object field
pub fn nested_object_validation_error_test() {
  let base_url = case envoy.get("MOCK_SERVER_URL") {
    Ok(u) -> u
    Error(_) -> "http://localhost:8080"
  }
  let assert Ok(req) = request.to(base_url <> "/fixtures/nested_object_validation_error")
  let req = request.set_method(req, http.Post)
  let req = request.set_header(req, "content-type", "application/json")
  let req = request.set_header(req, "Content-Type", "application/json")
  let req = request.set_body(req, "{\"name\":\"Product\",\"price\":10.0,\"seller\":{\"address\":{\"city\":\"SF\",\"zip_code\":\"123\"},\"name\":\"Jo\"}}")
  let assert Ok(resp) = httpc.send(req)
  resp.status |> should.equal(422)
  resp.body |> string.trim |> should.equal("{\"detail\":\"3 validation errors in request\",\"errors\":[{\"ctx\":{\"min_length\":3},\"input\":\"SF\",\"loc\":[\"body\",\"seller\",\"address\",\"city\"],\"msg\":\"String should have at least 3 characters\",\"type\":\"string_too_short\"},{\"ctx\":{\"min_length\":5},\"input\":\"123\",\"loc\":[\"body\",\"seller\",\"address\",\"zip_code\"],\"msg\":\"String should have at least 5 characters\",\"type\":\"string_too_short\"},{\"ctx\":{\"min_length\":3},\"input\":\"Jo\",\"loc\":[\"body\",\"seller\",\"name\"],\"msg\":\"String should have at least 3 characters\",\"type\":\"string_too_short\"}],\"status\":422,\"title\":\"Request Validation Failed\",\"type\":\"https://spikard.dev/errors/validation-error\"}")
}

// Tests validation error when value violates gt constraint
pub fn numeric_constraint_violation_gt_greater_than_test() {
  let base_url = case envoy.get("MOCK_SERVER_URL") {
    Ok(u) -> u
    Error(_) -> "http://localhost:8080"
  }
  let assert Ok(req) = request.to(base_url <> "/fixtures/numeric_constraint_violation_gt_greater_than")
  let req = request.set_method(req, http.Get)
  let req = request.set_header(req, "x-token", "test-token")
  let assert Ok(resp) = httpc.send(req)
  resp.status |> should.equal(422)
  resp.body |> string.trim |> should.equal("{\"detail\":\"1 validation error in request\",\"errors\":[{\"ctx\":{\"gt\":0},\"input\":\"0\",\"loc\":[\"query\",\"price\"],\"msg\":\"Input should be greater than 0\",\"type\":\"greater_than\"}],\"status\":422,\"title\":\"Request Validation Failed\",\"type\":\"https://spikard.dev/errors/validation-error\"}")
}

// Tests validation error when value violates le constraint
pub fn numeric_constraint_violation_le_less_than_or_equal_test() {
  let base_url = case envoy.get("MOCK_SERVER_URL") {
    Ok(u) -> u
    Error(_) -> "http://localhost:8080"
  }
  let assert Ok(req) = request.to(base_url <> "/fixtures/numeric_constraint_violation_le_less_than_or_equal")
  let req = request.set_method(req, http.Get)
  let req = request.set_header(req, "x-token", "test-token")
  let assert Ok(resp) = httpc.send(req)
  resp.status |> should.equal(422)
  resp.body |> string.trim |> should.equal("{\"detail\":\"1 validation error in request\",\"errors\":[{\"ctx\":{\"le\":100},\"input\":\"101\",\"loc\":[\"query\",\"limit\"],\"msg\":\"Input should be less than or equal to 100\",\"type\":\"less_than_equal\"}],\"status\":422,\"title\":\"Request Validation Failed\",\"type\":\"https://spikard.dev/errors/validation-error\"}")
}

// Tests validation error when string is provided for integer query param
pub fn query_param_type_error_string_provided_for_int_test() {
  let base_url = case envoy.get("MOCK_SERVER_URL") {
    Ok(u) -> u
    Error(_) -> "http://localhost:8080"
  }
  let assert Ok(req) = request.to(base_url <> "/fixtures/query_param_type_error_string_provided_for_int")
  let req = request.set_method(req, http.Get)
  let req = request.set_header(req, "x-token", "test-token")
  let assert Ok(resp) = httpc.send(req)
  resp.status |> should.equal(422)
  resp.body |> string.trim |> should.equal("{\"detail\":\"1 validation error in request\",\"errors\":[{\"input\":\"not_a_number\",\"loc\":[\"query\",\"skip\"],\"msg\":\"Input should be a valid integer, unable to parse string as an integer\",\"type\":\"int_parsing\"}],\"status\":422,\"title\":\"Request Validation Failed\",\"type\":\"https://spikard.dev/errors/validation-error\"}")
}

// Tests validation error when string exceeds max_length
pub fn string_max_length_constraint_violation_test() {
  let base_url = case envoy.get("MOCK_SERVER_URL") {
    Ok(u) -> u
    Error(_) -> "http://localhost:8080"
  }
  let assert Ok(req) = request.to(base_url <> "/fixtures/string_max_length_constraint_violation")
  let req = request.set_method(req, http.Get)
  let req = request.set_header(req, "x-token", "test-token")
  let assert Ok(resp) = httpc.send(req)
  resp.status |> should.equal(422)
  resp.body |> string.trim |> should.equal("{\"detail\":\"1 validation error in request\",\"errors\":[{\"ctx\":{\"max_length\":50},\"input\":\"this_is_a_very_long_query_string_that_exceeds_maximum_length_limit_for_this_parameter\",\"loc\":[\"query\",\"q\"],\"msg\":\"String should have at most 50 characters\",\"type\":\"string_too_long\"}],\"status\":422,\"title\":\"Request Validation Failed\",\"type\":\"https://spikard.dev/errors/validation-error\"}")
}

// Tests validation error when string is shorter than min_length
pub fn string_min_length_constraint_violation_test() {
  let base_url = case envoy.get("MOCK_SERVER_URL") {
    Ok(u) -> u
    Error(_) -> "http://localhost:8080"
  }
  let assert Ok(req) = request.to(base_url <> "/fixtures/string_min_length_constraint_violation")
  let req = request.set_method(req, http.Get)
  let req = request.set_header(req, "x-token", "test-token")
  let assert Ok(resp) = httpc.send(req)
  resp.status |> should.equal(422)
  resp.body |> string.trim |> should.equal("{\"detail\":\"1 validation error in request\",\"errors\":[{\"ctx\":{\"min_length\":3},\"input\":\"ab\",\"loc\":[\"query\",\"q\"],\"msg\":\"String should have at least 3 characters\",\"type\":\"string_too_short\"}],\"status\":422,\"title\":\"Request Validation Failed\",\"type\":\"https://spikard.dev/errors/validation-error\"}")
}

// Tests validation error when string doesn't match regex pattern
pub fn string_regex_pattern_mismatch_test() {
  let base_url = case envoy.get("MOCK_SERVER_URL") {
    Ok(u) -> u
    Error(_) -> "http://localhost:8080"
  }
  let assert Ok(req) = request.to(base_url <> "/fixtures/string_regex_pattern_mismatch")
  let req = request.set_method(req, http.Get)
  let req = request.set_header(req, "x-token", "test-token")
  let assert Ok(resp) = httpc.send(req)
  resp.status |> should.equal(422)
  resp.body |> string.trim |> should.equal("{\"detail\":\"1 validation error in request\",\"errors\":[{\"ctx\":{\"pattern\":\"^[a-zA-Z0-9_-]+$\"},\"input\":\"invalid!\",\"loc\":[\"query\",\"q\"],\"msg\":\"String should match pattern '^[a-zA-Z0-9_-]+$'\",\"type\":\"string_pattern_mismatch\"}],\"status\":422,\"title\":\"Request Validation Failed\",\"type\":\"https://spikard.dev/errors/validation-error\"}")
}
