// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8de1f40fab59d6a4476dac196e1ca8fef7f43839be55bd0a9e6358fb8ca8003a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

import { describe, expect, it } from "vitest";

describe("background", () => {
  it("background_event_logging: Enqueues a background job that appends the posted event to shared state", async () => {
    const sutUrl = process.env.SUT_URL || "http://127.0.0.1:8001";
    const url = `${sutUrl}/fixtures/background_event_logging/background/events`;
    const response = await fetch(url, {
      method: "POST",
      redirect: "manual",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ event: "alpha" }),
    });
    expect(response.status).toBe(202);
    expect(response.headers.get("content-type")).toBe("application/json");
  });

  it("background_event_logging_second_payload: Ensures background jobs handle different payloads", async () => {
    const sutUrl = process.env.SUT_URL || "http://127.0.0.1:8001";
    const url = `${sutUrl}/fixtures/background_event_logging_second_payload/background/events`;
    const response = await fetch(url, {
      method: "POST",
      redirect: "manual",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ event: "beta" }),
    });
    expect(response.status).toBe(202);
    expect(response.headers.get("content-type")).toBe("application/json");
  });
});
