name: Build Python Binding
description: Build spikard-python binding with maturin

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: ./.github/actions/setup-python-env
      with:
        python-version: "3.14"
        cache-prefix: benchmark-python

    - name: Setup Rust
      uses: ./.github/actions/setup-rust
      with:
        cache-key-prefix: benchmark-python-binding

    - name: Install maturin
      shell: bash
      run: uv pip install maturin

    - name: Build spikard-python
      shell: bash
      run: cd crates/spikard-py && uv run maturin develop --release --features extension-module
