// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0c34db3a76b3d86110ecc1192b5908af00eff83118169b258336326c2ffbc158
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import 'package:test/test.dart';
import 'dart:io';
import 'dart:async';
import 'dart:convert';

HttpClient _httpClient = HttpClient()..maxConnectionsPerHost = 1;

var _lock = Future<void>.value();

Future<T> _serialized<T>(Future<T> Function() fn) async {
  final current = _lock;
  final next = Completer<void>();
  _lock = next.future;
  try {
    await current;
    return await fn();
  } finally {
    next.complete();
  }
}

Future<T> _withRetry<T>(Future<T> Function() fn) async {
  try {
    return await fn();
  } on SocketException {
    _httpClient.close(force: true);
    _httpClient = HttpClient()..maxConnectionsPerHost = 1;
    return fn();
  } on HttpException {
    _httpClient.close(force: true);
    _httpClient = HttpClient()..maxConnectionsPerHost = 1;
    return fn();
  }
}

// E2e tests for category: graphql_schema
void main() {
  tearDownAll(() => _httpClient.close());

  test('Tests GraphQL authentication error when auth fails', () => _serialized(() => _withRetry(() async {
    final baseUrl = Platform.environment['MOCK_SERVER_URL'] ?? 'http://localhost:8080';
    final uri = Uri.parse('$baseUrl/fixtures/graphql_authentication_error_variant');
    final ioReq = await _httpClient.openUrl('POST', uri);
    ioReq.headers.set('content-type', 'application/json');
    final bodyBytes = utf8.encode('{"query":"{ user { id } }"}');
    ioReq.add(bodyBytes);
    final ioResp = await ioReq.close();
    expect(ioResp.statusCode, equals(401), reason: 'status code mismatch');
    final bodyStr = await ioResp.transform(utf8.decoder).join();
    final bodyJson = jsonDecode(bodyStr);
    final expectedJson = jsonDecode('{"error":"<<present>>"}');
    expect(bodyJson, equals(expectedJson), reason: 'body mismatch');
  })));

  test('Tests GraphQL authorization error when access denied', () => _serialized(() => _withRetry(() async {
    final baseUrl = Platform.environment['MOCK_SERVER_URL'] ?? 'http://localhost:8080';
    final uri = Uri.parse('$baseUrl/fixtures/graphql_authorization_error_variant');
    final ioReq = await _httpClient.openUrl('POST', uri);
    ioReq.headers.set('content-type', 'application/json');
    ioReq.headers.set('authorization', 'Bearer invalid');
    final bodyBytes = utf8.encode('{"query":"{ admin { id } }"}');
    ioReq.add(bodyBytes);
    final ioResp = await ioReq.close();
    expect(ioResp.statusCode, equals(403), reason: 'status code mismatch');
    final bodyStr = await ioResp.transform(utf8.decoder).join();
    final bodyJson = jsonDecode(bodyStr);
    final expectedJson = jsonDecode('{"error":"<<present>>"}');
    expect(bodyJson, equals(expectedJson), reason: 'body mismatch');
  })));

  test('Tests GraphQL query complexity validation rejects overly complex queries', () => _serialized(() => _withRetry(() async {
    final baseUrl = Platform.environment['MOCK_SERVER_URL'] ?? 'http://localhost:8080';
    final uri = Uri.parse('$baseUrl/fixtures/graphql_complexity_limit_exceeded');
    final ioReq = await _httpClient.openUrl('POST', uri);
    ioReq.headers.set('content-type', 'application/json');
    final bodyBytes = utf8.encode('{"query":"{ user { id name email posts { id title comments { id text } } } }"}');
    ioReq.add(bodyBytes);
    final ioResp = await ioReq.close();
    expect(ioResp.statusCode, equals(200), reason: 'status code mismatch');
    final bodyStr = await ioResp.transform(utf8.decoder).join();
    final bodyJson = jsonDecode(bodyStr);
    final expectedJson = jsonDecode('{"errors":[{"message":"Query complexity limit exceeded"}]}');
    expect(bodyJson, equals(expectedJson), reason: 'body mismatch');
  })));

  test('Tests GraphQL route configured at custom endpoint', () => _serialized(() => _withRetry(() async {
    final baseUrl = Platform.environment['MOCK_SERVER_URL'] ?? 'http://localhost:8080';
    final uri = Uri.parse('$baseUrl/fixtures/graphql_custom_endpoint_configuration');
    final ioReq = await _httpClient.openUrl('POST', uri);
    ioReq.headers.set('content-type', 'application/json');
    final bodyBytes = utf8.encode('{"query":"{ user { id } }"}');
    ioReq.add(bodyBytes);
    final ioResp = await ioReq.close();
    expect(ioResp.statusCode, equals(200), reason: 'status code mismatch');
    final bodyStr = await ioResp.transform(utf8.decoder).join();
    final bodyJson = jsonDecode(bodyStr);
    final expectedJson = jsonDecode('{"data":{"user":{"id":"1"}}}');
    expect(bodyJson, equals(expectedJson), reason: 'body mismatch');
  })));

  test('Tests GraphQL query depth validation rejects deeply nested queries', () => _serialized(() => _withRetry(() async {
    final baseUrl = Platform.environment['MOCK_SERVER_URL'] ?? 'http://localhost:8080';
    final uri = Uri.parse('$baseUrl/fixtures/graphql_depth_limit_exceeded');
    final ioReq = await _httpClient.openUrl('POST', uri);
    ioReq.headers.set('content-type', 'application/json');
    final bodyBytes = utf8.encode('{"query":"{ user { posts { comments { author { posts { title } } } } } }"}');
    ioReq.add(bodyBytes);
    final ioResp = await ioReq.close();
    expect(ioResp.statusCode, equals(200), reason: 'status code mismatch');
    final bodyStr = await ioResp.transform(utf8.decoder).join();
    final bodyJson = jsonDecode(bodyStr);
    final expectedJson = jsonDecode('{"errors":[{"message":"Query depth limit exceeded"}]}');
    expect(bodyJson, equals(expectedJson), reason: 'body mismatch');
  })));

  test('Tests GraphQL error response format with correct structure', () => _serialized(() => _withRetry(() async {
    final baseUrl = Platform.environment['MOCK_SERVER_URL'] ?? 'http://localhost:8080';
    final uri = Uri.parse('$baseUrl/fixtures/graphql_error_response_format');
    final ioReq = await _httpClient.openUrl('POST', uri);
    ioReq.headers.set('content-type', 'application/json');
    final bodyBytes = utf8.encode('{"query":"{ invalidField }"}');
    ioReq.add(bodyBytes);
    final ioResp = await ioReq.close();
    expect(ioResp.statusCode, equals(200), reason: 'status code mismatch');
    final bodyStr = await ioResp.transform(utf8.decoder).join();
    final bodyJson = jsonDecode(bodyStr);
    final expectedJson = jsonDecode('{"errors":[{"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"},"message":"Cannot query field \'invalidField\' on type \'Query\'"}]}');
    expect(bodyJson, equals(expectedJson), reason: 'body mismatch');
  })));

  test('Tests GraphQL execution error response', () => _serialized(() => _withRetry(() async {
    final baseUrl = Platform.environment['MOCK_SERVER_URL'] ?? 'http://localhost:8080';
    final uri = Uri.parse('$baseUrl/fixtures/graphql_execution_error_variant');
    final ioReq = await _httpClient.openUrl('POST', uri);
    ioReq.headers.set('content-type', 'application/json');
    final bodyBytes = utf8.encode('{"query":"{ invalidField }"}');
    ioReq.add(bodyBytes);
    final ioResp = await ioReq.close();
    expect(ioResp.statusCode, equals(200), reason: 'status code mismatch');
    final bodyStr = await ioResp.transform(utf8.decoder).join();
    final bodyJson = jsonDecode(bodyStr);
    final expectedJson = jsonDecode('{"errors":[{"message":"<<present>>"}]}');
    expect(bodyJson, equals(expectedJson), reason: 'body mismatch');
  })));

  test('Tests GraphQL schema with queries, mutations, and subscriptions', () => _serialized(() => _withRetry(() async {
    final baseUrl = Platform.environment['MOCK_SERVER_URL'] ?? 'http://localhost:8080';
    final uri = Uri.parse('$baseUrl/fixtures/graphql_full_schema_with_subscriptions');
    final ioReq = await _httpClient.openUrl('POST', uri);
    ioReq.headers.set('content-type', 'application/json');
    final bodyBytes = utf8.encode('{"query":"{ __typename }"}');
    ioReq.add(bodyBytes);
    final ioResp = await ioReq.close();
    expect(ioResp.statusCode, equals(200), reason: 'status code mismatch');
    final bodyStr = await ioResp.transform(utf8.decoder).join();
    final bodyJson = jsonDecode(bodyStr);
    final expectedJson = jsonDecode('{"data":{"__typename":"Query"}}');
    expect(bodyJson, equals(expectedJson), reason: 'body mismatch');
  })));

  test('Tests GraphQL introspection returns error when disabled', () => _serialized(() => _withRetry(() async {
    final baseUrl = Platform.environment['MOCK_SERVER_URL'] ?? 'http://localhost:8080';
    final uri = Uri.parse('$baseUrl/fixtures/graphql_introspection_disabled');
    final ioReq = await _httpClient.openUrl('POST', uri);
    ioReq.headers.set('content-type', 'application/json');
    final bodyBytes = utf8.encode('{"query":"{ __schema { types { name } } }"}');
    ioReq.add(bodyBytes);
    final ioResp = await ioReq.close();
    expect(ioResp.statusCode, equals(200), reason: 'status code mismatch');
    final bodyStr = await ioResp.transform(utf8.decoder).join();
    final bodyJson = jsonDecode(bodyStr);
    final expectedJson = jsonDecode('{"errors":[{"message":"GraphQL introspection is disabled"}]}');
    expect(bodyJson, equals(expectedJson), reason: 'body mismatch');
  })));

  test('Tests GraphQL introspection is available', () => _serialized(() => _withRetry(() async {
    final baseUrl = Platform.environment['MOCK_SERVER_URL'] ?? 'http://localhost:8080';
    final uri = Uri.parse('$baseUrl/fixtures/graphql_introspection_enabled');
    final ioReq = await _httpClient.openUrl('POST', uri);
    ioReq.headers.set('content-type', 'application/json');
    final bodyBytes = utf8.encode('{"query":"{ __schema { types { name } } }"}');
    ioReq.add(bodyBytes);
    final ioResp = await ioReq.close();
    expect(ioResp.statusCode, equals(200), reason: 'status code mismatch');
    final bodyStr = await ioResp.transform(utf8.decoder).join();
    final bodyJson = jsonDecode(bodyStr);
    final expectedJson = jsonDecode('{"data":{"__schema":{"types":null}}}');
    expect(bodyJson, equals(expectedJson), reason: 'body mismatch');
  })));

  test('Tests GraphQL invalid input error', () => _serialized(() => _withRetry(() async {
    final baseUrl = Platform.environment['MOCK_SERVER_URL'] ?? 'http://localhost:8080';
    final uri = Uri.parse('$baseUrl/fixtures/graphql_invalid_input_error_variant');
    final ioReq = await _httpClient.openUrl('POST', uri);
    ioReq.headers.set('content-type', 'application/json');
    final bodyBytes = utf8.encode('{"query":"mutation { createUser(age: -5) { id } }"}');
    ioReq.add(bodyBytes);
    final ioResp = await ioReq.close();
    expect(ioResp.statusCode, equals(200), reason: 'status code mismatch');
    final bodyStr = await ioResp.transform(utf8.decoder).join();
    final bodyJson = jsonDecode(bodyStr);
    final expectedJson = jsonDecode('{"errors":[{"message":"<<present>>"}]}');
    expect(bodyJson, equals(expectedJson), reason: 'body mismatch');
  })));

  test('Tests GraphQL not found error for missing resource', () => _serialized(() => _withRetry(() async {
    final baseUrl = Platform.environment['MOCK_SERVER_URL'] ?? 'http://localhost:8080';
    final uri = Uri.parse('$baseUrl/fixtures/graphql_not_found_error_variant');
    final ioReq = await _httpClient.openUrl('POST', uri);
    ioReq.headers.set('content-type', 'application/json');
    final bodyBytes = utf8.encode('{"query":"{ user(id: \\"nonexistent\\") { id } }"}');
    ioReq.add(bodyBytes);
    final ioResp = await ioReq.close();
    expect(ioResp.statusCode, equals(200), reason: 'status code mismatch');
    final bodyStr = await ioResp.transform(utf8.decoder).join();
    final bodyJson = jsonDecode(bodyStr);
    final expectedJson = jsonDecode('{"errors":[{"message":"<<present>>"}]}');
    expect(bodyJson, equals(expectedJson), reason: 'body mismatch');
  })));

  test('Tests GraphQL schema with queries and mutations', () => _serialized(() => _withRetry(() async {
    final baseUrl = Platform.environment['MOCK_SERVER_URL'] ?? 'http://localhost:8080';
    final uri = Uri.parse('$baseUrl/fixtures/graphql_query_and_mutation_schema');
    final ioReq = await _httpClient.openUrl('POST', uri);
    ioReq.headers.set('content-type', 'application/json');
    final bodyBytes = utf8.encode('{"query":"mutation { createUser(name: \\"New\\") { id name } }"}');
    ioReq.add(bodyBytes);
    final ioResp = await ioReq.close();
    expect(ioResp.statusCode, equals(200), reason: 'status code mismatch');
    final bodyStr = await ioResp.transform(utf8.decoder).join();
    final bodyJson = jsonDecode(bodyStr);
    final expectedJson = jsonDecode('{"data":{"createUser":{"id":"2","name":"New"}}}');
    expect(bodyJson, equals(expectedJson), reason: 'body mismatch');
  })));

  test('Tests GraphQL schema configured with queries only', () => _serialized(() => _withRetry(() async {
    final baseUrl = Platform.environment['MOCK_SERVER_URL'] ?? 'http://localhost:8080';
    final uri = Uri.parse('$baseUrl/fixtures/graphql_query_only_schema');
    final ioReq = await _httpClient.openUrl('POST', uri);
    ioReq.headers.set('content-type', 'application/json');
    final bodyBytes = utf8.encode('{"query":"{ user { id name } }"}');
    ioReq.add(bodyBytes);
    final ioResp = await ioReq.close();
    expect(ioResp.statusCode, equals(200), reason: 'status code mismatch');
    final bodyStr = await ioResp.transform(utf8.decoder).join();
    final bodyJson = jsonDecode(bodyStr);
    final expectedJson = jsonDecode('{"data":{"user":{"id":"1","name":"Test User"}}}');
    expect(bodyJson, equals(expectedJson), reason: 'body mismatch');
  })));

  test('Tests GraphQL rate limit exceeded error', () => _serialized(() => _withRetry(() async {
    final baseUrl = Platform.environment['MOCK_SERVER_URL'] ?? 'http://localhost:8080';
    final uri = Uri.parse('$baseUrl/fixtures/graphql_rate_limit_error_variant');
    final ioReq = await _httpClient.openUrl('POST', uri);
    ioReq.headers.set('content-type', 'application/json');
    final bodyBytes = utf8.encode('{"query":"{ user { id } }"}');
    ioReq.add(bodyBytes);
    final ioResp = await ioReq.close();
    expect(ioResp.statusCode, equals(200), reason: 'status code mismatch');
    final bodyStr = await ioResp.transform(utf8.decoder).join();
    final bodyJson = jsonDecode(bodyStr);
    final expectedJson = jsonDecode('{"data":"<<present>>"}');
    expect(bodyJson, equals(expectedJson), reason: 'body mismatch');
  })));

  test('Tests GraphQL schema build error', () => _serialized(() => _withRetry(() async {
    final baseUrl = Platform.environment['MOCK_SERVER_URL'] ?? 'http://localhost:8080';
    final uri = Uri.parse('$baseUrl/fixtures/graphql_schema_build_error_variant');
    final ioReq = await _httpClient.openUrl('POST', uri);
    ioReq.headers.set('content-type', 'application/json');
    final bodyBytes = utf8.encode('{"query":"{ test }"}');
    ioReq.add(bodyBytes);
    final ioResp = await ioReq.close();
    expect(ioResp.statusCode, equals(500), reason: 'status code mismatch');
    final bodyStr = await ioResp.transform(utf8.decoder).join();
    final bodyJson = jsonDecode(bodyStr);
    final expectedJson = jsonDecode('{"error":"<<present>>"}');
    expect(bodyJson, equals(expectedJson), reason: 'body mismatch');
  })));

  test('Tests GraphQL serialization error for invalid response', () => _serialized(() => _withRetry(() async {
    final baseUrl = Platform.environment['MOCK_SERVER_URL'] ?? 'http://localhost:8080';
    final uri = Uri.parse('$baseUrl/fixtures/graphql_serialization_error_variant');
    final ioReq = await _httpClient.openUrl('POST', uri);
    ioReq.headers.set('content-type', 'application/json');
    final bodyBytes = utf8.encode('{"query":"{ user { id } }"}');
    ioReq.add(bodyBytes);
    final ioResp = await ioReq.close();
    expect(ioResp.statusCode, equals(200), reason: 'status code mismatch');
    final bodyStr = await ioResp.transform(utf8.decoder).join();
    final bodyJson = jsonDecode(bodyStr);
    final expectedJson = jsonDecode('{"data":"<<present>>"}');
    expect(bodyJson, equals(expectedJson), reason: 'body mismatch');
  })));

}
