#!/usr/bin/env bash
# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:25945609773117fe16dad951ff7c2b463ca36ee2f642a055611ceb789c46651b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: websocket
set -euo pipefail

test_ws_upgrade_handshake() {
  # Tests WebSocket upgrade returns 101 Switching Protocols with correct Sec-WebSocket-Accept header
    >/dev/null

}

run_tests_websocket() {
  run_test test_ws_upgrade_handshake
}
