#!/usr/bin/env bash
# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:059d0b466bb3ce8ad08140b7e0721a1e0c0fed5ef09e12c835620d726544a19b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: websocket
set -euo pipefail

test_ws_upgrade_handshake() {
  # Tests WebSocket upgrade returns 101 Switching Protocols with correct Sec-WebSocket-Accept header
    >/dev/null

}

run_tests_websocket() {
  run_test test_ws_upgrade_handshake
}
